### PR TITLE
BINARY TO DECIMAL CONVERSION IMPLEMENTED SUCCESSFULLY 

### LINKED ISSUE #4281: DECIMAL TO BINARY CONVERSION USING STACK IN C
DECIMAL TO BINARY CONVERSION USING STACK IN C
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes !

AIM :: **DECIMAL TO BINARY CONVERSION USING STACK IN C**

## Motivation

As i didn't found DECIMAL TO BINARY CONVERSION USING STACK IN C, So i am willing to contribute it...

## Pitch

Hi I am GSSoC'21 participant,
"I am looking to work on the DECIMAL TO BINARY CONVERSION USING STACK IN C"
I will write the clean and optimized code , by keeping best case time and space complexity in mind and 

I will use C language.

### PR DESCRIPTION
**Pull request by ananddasani**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes !

### Description

I have implemented the solution of issue DECIMAL TO BINARY CONVERSION 
I would request @HarshCasper , @ankitaggarwal23 , @bhav09 to please review my PR.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

No :)

Fixes #4281

### CODE REVIEW

**Comment by ankitaggarwal23** [comment]
@ananddasani Don't do such type of things mentioning other PR in the same PR.

Capture

**Review by ankitaggarwal23 — COMMENTED** [review]
@ananddasani Don't do such type of things mentioning other PR in the same PR.

Capture

Don't push more than one code file in a single PR.

**Comment by ananddasani** [comment]
> @ananddasani Don't do such type of things mentioning other PR in the same PR.
> 
> Capture
> 
> Don't push more than one code file in a single PR.

@ankitaggarwal23 but there is only one code file 

i have deleted the second code file ...... 
(which was added due to issue was already present but in other directory , which was not suppose to be there :(     )

**Comment by ankitaggarwal23** [comment]
Okay

**Comment by ankitaggarwal23** [comment]
@ananddasani don't worry open a new one and don't link other pr in the same PR. We will review

**Comment by ananddasani** [comment]
> @ananddasani don't worry open a new one and don't link other pr in the same PR. We will review

sure

**Pull request closed without merging**
