### PR TITLE
Connect links of pending programs in README.md

### PR DESCRIPTION
**Pull request by narayan2111**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Added respective Programs to their corresponding folder and updated readme file with respect to that

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#945

### CODE REVIEW

**Comment by narayan2111** [comment]
kindly review this PR @iamrajiv 

Before updating the readme file , i made pull request from master branch of TessaractCoding so that i can access every file added till now,so that it have all the files added recently

**Review by iamrajiv — CHANGES_REQUESTED** [review]
@narayan2111 Format the code like this
```
<p align="center">
    <img src="../img/neo_algo.png"><br>
    <img src="https://img.shields.io/github/license/tesseractcoding/neoalgo?style=flat">
    <a href="http://makeapullrequest.com" target="_blank"><img src="https://img.shields.io/badge/PRs-welcome-brightgreen.svg?style=flat" alt="PRs Welcome"></a>
    <img alt="GitHub pull requests" src="https://img.shields.io/github/issues-pr/tesseractcoding/neoalgo">
    <img alt="GitHub issues" src="https://img.shields.io/github/issues/tesseractcoding/neoalgo">
    <img alt="Github All Contributors" src="https://img.shields.io/github/all-contributors/tesseractcoding/neoalgo">
</p>

# Codes in the C++ language

## Data Structures

- [Binary Search Tree](ds/BinarySearchTree.cpp)
- [Binary Tree](ds/BinaryTree.cpp)
- [Doubly Linked List](ds/DoublyLinkedList.cpp)
- [Hashtable with separate chaining](ds/Hashing_with_chaining.cpp)
- [Heap Sort](ds/heap_sort.cpp)
- [Linked List](ds/LinkedList.cpp)
- [Max and Min heap Implementation](ds/max_min_heap.cpp)
- [Nodes At A Distance K From A Given Target Node In A Binary Tree](ds\K_Distance_Nodes_Binary_Tree.cpp)
- [Priority Queue](ds/Priority_Queue.cpp)
- [Queue](ds/Queue.cpp)
- [Queue Linked list](ds/QueueLinkedList.cpp)
- [Red-Black Tree](ds/RED-BLACK-TREE.cpp)
- [Singly Linked List](ds/singly_linked_list.cpp)
- [Stack Using Array](ds/Stack_using_Array.cpp)
- [Stack Using Linked List](ds/Stack_using_LinkedList.cpp)
- [Tim Sort](ds/Tim_Sort.cpp)
- [Trie Implementation](ds/Trie_implementation.cpp)
- [Updated Reverse Linked List](ds/Reverse_linked_list.cpp)

## Searching

- [Binary Search](search/Binary_Search.cpp)
- [Interpolation Search](search/Interpolation_Search.cpp)
- [Jump Search](search/Jump_Search.cpp)
- [Linear Search](search/Linear_Search.cpp)

## Sorting

- [Bubble Sort](sort/Bubble_Sort.cpp)
- [Counting Sort](sort/countsort.cpp)
- [Heap Sort](sort/HeapSort.cpp)
- [Insertion Sort](sort/insertion.cpp)
- [Merge Sort](sort/Merge_Sort.cpp)
- [Quick Sort](sort/Quick_Sort.cpp)
- [Randomized Quick Sort](sort/Randomized_Quick_Sort.cpp)
- [Selection Sort](sort/selection_sort.cpp)
- [Shell Sort](sort/ShellSort.cpp)
- [Topological Sort](sort/Topological_Sorting_DFS.cpp)

## Graphs

- [Breadth First Search Tree Traversal](graphs/bfs.cpp)
- [Dijkstra's Algorithm](graphs/Dijkstra_algorithm.cpp)
- [In-order (LNR) Tree Traversal](graphs/inorder-traversal.cpp)
- [Kosaraju's Algorithm](graphs/Kosaraju_Algorithm.cpp)
- [Kruskal's Algorithm](graphs/kruskal_Algorithm.cpp)
- [Post-order (LRN) Tree Traversal](graphs/Postorder_Traversal.cpp)
- [Pre-order (NLR) Tree Traversal](/graphs/Preorder_Traversal.cpp)
- [Prim's Algorithm](graphs/Prim_Algorithm.cpp)

## Machine Learning

_add list here_

## Mathematics

- [Ackermann_Function](math/Ackermann_function.cpp)
- [Binary Exponentiation](math/Binary_Exponentiation.cpp)
- [Euler's_Totient_Function](math/Euler's_Totient_function.cpp)
- [Extended Euclidean Algorithm](math/Extended_Euclidean_Algorithm.cpp)
- [Sieve of Eratosthenes](math/Sieve_of_Eratosthenes.cpp)

## Dynamic Programming

- [Coin Change Problem](dp/Coin_Change_Problem.cpp)
- [Edit Distance](dp/edit_distance.cpp)
- [Fibonacci number with bottom-up approach](dp/fibonacci_bottom_up.cpp)
- [Fibonacci number with top-down approach](dp/fibonacci_top_down.cpp)
- [Longest increasing subsequence](dp/longest_increasing_subsequence.cpp)
- [Longest common subsequence](dp/longest_common_subsequence.cpp)
- [String permutations](dp/string_permutations.cpp)

## Blockchain

_add list here_

## Cryptography

- [Affine substitution Cipher](cryptography/Affine_substitution_Cipher.cpp)

## Competitive Programming

- [Array Right Rotation Naive Approach](cp/Array_Right_Rotate.cpp)
- [Check whether two strings are anagrams or not](cp/check_anagrams.cpp)
- [Contiguous Sub Array with Given Sum](cp/SubArrayWithGivenSum.cpp)
- [Elements Occurrence using Binary Search](cp/ElementsOccurrence_BinarySearch.cpp)
- [Find number of digits in an integer](cp/find_no_of_digits_in_int.cpp)
- [Intersection Point of Y shaped LinkedList](cp/Intersection Point of Y shaped LinkedList.cpp)
- [Infix to Postfix](C-Plus-Plus/cp/infix_to_postfix.cpp)
- [Kadane's Algorithm for max sum subArray](cp/Kadane_Alogorithm.cpp)
- [Knuth–Morris–Pratt_algorithm](cp/Knuth–Morris–Pratt.cpp)
- [Maximum in Array](cp/Maximum_In_Array.cpp)
- [Reverse words in Given String](cp/Reverse_Words_in_String.cpp)
- [Infix to Postfix](cp/infix_to_postfix.cpp)
- [Target sum triplets](cp/target_sum_triplets.cpp)
- [2-D MatrixSorting algorithm](cp/2-D_MatrixSorting.cpp)

## Other

- [String Rotation based on Queries](other/string_rotation.cpp)
- [First Missing Positive Number](other/First_Missing_Positive_Number.cpp)

```

**Review by iamrajiv — CHANGES_REQUESTED** [review]
@narayan2111 Remove `Python/README.md` file.

**Comment by narayan2111** [comment]
> @narayan2111 Remove `Python/README.md` file.

Done Sir @iamrajiv

**Review by iamrajiv — CHANGES_REQUESTED** [review]
@narayan2111 Remove `Longest_Palindrome_Substring.py`.

**Comment by narayan2111** [comment]
> @narayan2111 Remove `Longest_Palindrome_Substring.py`.

Done Sir @iamrajiv

**Review by iamrajiv — APPROVED** [review]

**Pull request merged**
