### PR TITLE
Remove outermost paranthesis

### PR DESCRIPTION
**Pull request by salonishah01**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Added python code for 'Remove Outermost Paranthesis'

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#955

### CODE REVIEW

**Comment by salonishah01** [comment]
@HarshCasper @iamrajiv @siddharth25pandey  Please review this Pull Request

**Review by vatsalkesarwani12 — APPROVED** [review]
👍🏻

**Review by atarax665 — APPROVED** [review]
LGTM :)

**Review by siddharth25pandey — APPROVED** [review]
@salonishah01 Good to go
Able to merge
Thanks!

**Pull request merged**
