### PR TITLE
Added Max topology Short

### PR DESCRIPTION
**Pull request by codeakki**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

yes

### Description

Added maximum topology Short

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#4389 #4654

### CODE REVIEW

**Review by bhav09 — CHANGES_REQUESTED** [review]
Can you please remove the redundant lines, add complexity above Sample I/O and add a new line at EOF.

**Review by ankitaggarwal23 — CHANGES_REQUESTED** [review]
Resolve merge conflicts

**Review by codeakki — COMMENTED** [review]
removed merge conflict

**Comment by codeakki** [comment]
hey @ankitaggarwal23 can u please tell me what changes i have to do now bcz i have made all changes as per suggested by u

**Review by bhav09 — CHANGES_REQUESTED** [review]
The code seems good but the driver code is really very dense. Can you prune it to calling functions only? That would really be light and good looking. Thanks!

**Review by bhav09 — APPROVED** [review]
Reviewed

**Pull request merged**
