### PR TITLE
Finding number of digits in an integer(TesseractCoding#406)

### PR DESCRIPTION
**Pull request by infoarpit**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

### Description

(Write your answer here.)

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

### CODE REVIEW

**Comment by infoarpit** [comment]
I have completed the task in java 
Finding the number of digits in an integer #406

**Review by vatsalkesarwani12 — CHANGES_REQUESTED** [review]
Your Code works well just do a change create a folder named the countDigits and add 3 .java file name with iterative, recursive, and string. This will make code easy to read and run.

**Comment by infoarpit** [comment]
I did the changes accordingly
Created the new folder countDigits which have 3 .java files each consisting iterative, recursive, and string method respectively.
Also added the same change to README folder.

**Comment by infoarpit** [comment]
> Your Code works well just do a change create a folder named the countDigits and add 3 .java file name with iterative, recursive, and string. This will make code easy to read and run.

I have done the changes now
Created the new folder countDigits which have 3 .java files each consisting iterative, recursive, and string method respectively.
Also added the same change to README folder.

**Review by vatsalkesarwani12 — APPROVED** [review]
Good work 🎉

**Comment by infoarpit** [comment]
@HarshCasper @siddharth25pandey

**Review by siddharth25pandey — APPROVED** [review]
@infoarpit Looks fine to me
Able to merge
Thanks!

**Comment by infoarpit** [comment]
@HarshCasper 
Please review it

**Comment by infoarpit** [comment]
@HarshCasper

**Comment by infoarpit** [comment]
@HarshCasper

**Pull request merged**
