### PR TITLE
House Robber problem #1312

### PR DESCRIPTION
**Pull request by limitless-Sky**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes, I had read the guidelines for pull-request and made changes in branch not in master.  

### Description
Solved House Robber problem #1312 in Java language using DP.

### Checklist

- [Y] I've read the contribution guidelines.
- [Y] I've checked the issue list before deciding what to submit.
- [Y] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Find the code in Solution.java file which is checked by upload on leetcode.
leetcode

### CODE REVIEW

**Review by iamrajiv — CHANGES_REQUESTED** [review]
@limitless-Sky Add sample input-output, space complexity and time complexity. Also, update the README file.

**Comment by limitless-Sky** [comment]
Requested Chances have been made. Thanks for your guidance.

**Review by iamrajiv — CHANGES_REQUESTED** [review]
@limitless-Sky Add your program link to `Java/README.md`.

**Comment by limitless-Sky** [comment]
Added House Robber Problem in readme file in other section linked with House_Robber_Problem.java

**Review by iamrajiv — CHANGES_REQUESTED** [review]
@limitless-Sky No need to make #1413 and #1414 you can update the README in this PR only. Also, change the program name `Solution.java` to `House_Robber-problem.java`.

**Review by vatsalkesarwani12 — APPROVED** [review]

**Comment by HarshCasper** [comment]
Add proper README changes as well.

**Comment by HarshCasper** [comment]
@limitless-Sky Are you still working on it?

**Comment by limitless-Sky** [comment]
@HarshCasper yes

**Comment by HarshCasper** [comment]
I'm closing the PR due to no activity. If you would like to reopen this PR to be reviewed please join the [Slack](https://join.slack.com/t/tesseractcodi-bxq5968/shared_invite/zt-ju6c0nqq-KgkTvFyxjNVbDRBIjADanw) and drop me a message.

**Pull request closed without merging**
