### PR TITLE
Added Mo's Algo in cpp

### PR DESCRIPTION
**Pull request by Jassi10000-zz**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)
Yes

### Description

Mo's Algo is very popular problem b/w Competitive Programmers and also and Important Interview Question, so I thought that this can be a nice addition to NeoAlgo as it's the future's one stop solution of DS and Algo

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)
Yes

### CODE REVIEW

**Comment by Jassi10000-zz** [comment]
Successfully added the PR 
Pls review @shraddhavp @srimani-programmer

**Review by atarax665 — COMMENTED** [review]
The code is copied from [here](https://www.geeksforgeeks.org/mos-algorithm-query-square-root-decomposition-set-1-introduction/).

**Comment by Jassi10000-zz** [comment]
Sir @atarax665  its not copied , I study from GFG only , that's why, Actually for this algo , I learned it so that it can remembered for long time  and that's the reason maybe my code matches

**Comment by Jassi10000-zz** [comment]
No issues , I will change it and write in some different way  and then submit the PR

**Pull request closed without merging**
