### PR TITLE
Full implementation of AVL tree and stock Span Problem 

### PR DESCRIPTION
**Pull request by codeakki**
1.implement AVL tree in .c full working with proper comments #3806 
2.Implemet of Stock span problem #3987

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

### Description

(Write your answer here.)

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

### CODE REVIEW

**Review by codeakki — COMMENTED** [review]
#3806

**Review by codeakki — COMMENTED** [review]
#3806 #3811

**Comment by codeakki** [comment]
#3987 Stock span problem

**Review by HarshCasper — CHANGES_REQUESTED** [review]
Don't push more than one code file in a single PR

**Pull request closed without merging**
