### PR TITLE
Create calendar.cpp

### PR DESCRIPTION
**Pull request by himanshu007-creator**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)
yes

(Write your answer here.)

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

https://github.com/TesseractCoding/NeoAlgo/issues/2038

### CODE REVIEW

**Comment by himanshu007-creator** [comment]
please add <code>DWOC</code> label to this pull request and add a <code>label-4</code> tag as well

**Comment by atarax665** [comment]
Please do mention the issue that this PR fixes.

**Comment by himanshu007-creator** [comment]
done sir.

**Comment by atarax665** [comment]
Sorry, but this program doesn't fit in any of the domain that we cover in this repository.

**Pull request closed without merging**
