### PR TITLE
Create smallest positive missing number.cpp

### PR DESCRIPTION
**Pull request by priyanka001tech**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

smallest positive missing number in array

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

issue #2995

### CODE REVIEW

**Comment by priyanka001tech** [comment]
[README.txt](https://github.com/TesseractCoding/NeoAlgo/files/6189299/README.txt)

**Comment by priyanka001tech** [comment]
Please review it..

**Review by HarshCasper — CHANGES_REQUESTED** [review]
Make markdown updates

**Review by ankitaggarwal23 — CHANGES_REQUESTED** [review]
Few changes: 

- Add Multi-Line Comments 
- Add a beginner-friendly description at the top
- Use proper code Format 
- Remove extra lines of code and spaces
- Add sample I/O at the end of the Code
- Add Time and Space Complexity at the end of the Code   
- Add new line at the EOF
- Shift the logic to another function and use main for driver code
- Update the Readme.md file

**Comment by priyanka001tech** [comment]
#4584 updated code

**Comment by priyanka001tech** [comment]
[README (4).txt](https://github.com/TesseractCoding/NeoAlgo/files/6227441/README.4.txt)

**Review by ankitaggarwal23 — COMMENTED** [review]
Code plagiarized from [here](https://www.geeksforgeeks.org/find-the-smallest-positive-number-missing-from-an-unsorted-array/).

**Pull request closed without merging**
