### PR TITLE
Reverse Linked List 283

### PR DESCRIPTION
**Pull request by Alifbhanvadiya14**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description
A problem in reversing LinkedList 

### Checklist

- [✔️] I've read the contribution guidelines.
- [✔️] I've checked the issue list before deciding what to submit.
- [✔️] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
Reversing Linked list was not possible using a single Linked List for both approaches. So created a new Linked List

### CODE REVIEW

**Comment by Alifbhanvadiya14** [comment]
@siddharth25pandey Please review the code

**Review by siddharth25pandey — CHANGES_REQUESTED** [review]
@Alifbhanvadiya14 please add the **readme** file details.
Also write sample input and output at the end of the code.

**Comment by Alifbhanvadiya14** [comment]
@siddharth25pandey Please review the changes

**Comment by Alifbhanvadiya14** [comment]
@siddharth25pandey  @SKAUL05 @hushee69 @mechiragjain  please review the pr

**Comment by siddharth25pandey** [comment]
@Alifbhanvadiya14 Readme file is not updated yet.

**Comment by Alifbhanvadiya14** [comment]
Now see I have updated

**Comment by Alifbhanvadiya14** [comment]
@siddharth25pandey  now see I have updated

**Comment by siddharth25pandey** [comment]
@Alifbhanvadiya14 Please resolve merge Conflict Error

**Comment by Alifbhanvadiya14** [comment]
@siddharth25pandey  @SKAUL05  @hushee69  @mechiragjain  please review . Merge conflict resolved

**Comment by siddharth25pandey** [comment]
@Alifbhanvadiya14 **README** file is missing.

**Comment by Alifbhanvadiya14** [comment]
@siddharth25pandey  no it is there

**Comment by siddharth25pandey** [comment]
> @siddharth25pandey no it is there

@Alifbhanvadiya14 Only One file is showing
Have a look again.
Thanks!

**Comment by Alifbhanvadiya14** [comment]
@siddharth25pandey  there are two file one with commit updated Linked list and other with Updated Readme

**Pull request closed without merging**
