### PR TITLE
Vigenere cipher code python

### PR DESCRIPTION
**Pull request by rutujadhanawade**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

yes

### Description
Added code for Vigenere cipher in python #974 

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#974

### CODE REVIEW

**Comment by rutujadhanawade** [comment]
@iamrajiv @Kajol-Kumari please review this.

**Review by iamrajiv — CHANGES_REQUESTED** [review]
@rutujadhanawade Format the code according to PEP 8 rules. Refer this http://pep8online.com/

**Comment by rutujadhanawade** [comment]
Done @iamrajiv

**Review by iamrajiv — APPROVED** [review]

**Review by atarax665 — APPROVED** [review]
LGTM :+1:

**Review by Kajol-Kumari — APPROVED** [review]
Good to Go! :+1:

**Pull request merged**
