### PR TITLE
Added Binary Search Tree under C++ folder

### PR DESCRIPTION
**Pull request by GudlaArunKumar**
* [x] Have you followed the guidelines in our Contributing document?
* [x] Have you checked the issues to see if your request isn't assigned to someone else?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
* [ ] If your submission is to improve an existing code, have you created an issue to specify that?
* [x] Don't tag anyone unless specifically requested to do so
* [x] Don't create any subfolders unless specifically requested to do so.

1. [x] Does your code work locally?
2. [x] Have you cleaned your code for better readability? (no extra unnecessary lines, etc.)
3. [x] Have you updated the README.md file to add the link to your code?

### CODE REVIEW

**Comment by sparkingdark** [comment]
@GudlaArunKumar  please check all the boxes.

**Comment by GudlaArunKumar** [comment]
Updated the check boxes

**Comment by GudlaArunKumar** [comment]
But same issue is assigned Yesterday to other programmer. So, Please close my PR

**Comment by GudlaArunKumar** [comment]
Added Stack DS in C++

**Review by mar-galho — APPROVED** [review]
Amazing! Thanks a lot!

**Comment by GudlaArunKumar** [comment]
welcome!

**Pull request merged**
