### PR TITLE
Added Solution of the problem

### PR DESCRIPTION
**Pull request by rcoder23**
Added Solution of the problem #1311

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes 

### Description

I am try to solve issue #1311 ,by adding solution of the problem 

### Checklist

- [ y] I've read the contribution guidelines.
- [ y] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)
#1311  solved .
Please review it and merged . Thank you

### CODE REVIEW

**Comment by HarshCasper** [comment]
Please add proper Comments to the Code and add the Code Link on the README File as well.

**Review by rcoder23 — COMMENTED** [review]
Comments are added

**Comment by HarshCasper** [comment]
I don't see any proper comments. Please format your Code properly, make proper README changes and make the code look more meaningful.

**Comment by HarshCasper** [comment]
Are you still working on it @rcoder23 ?

**Review by rcoder23 — COMMENTED** [review]
Please merge it

**Review by rcoder23 — COMMENTED** [review]
Updated

**Review by rcoder23 — COMMENTED** [review]
Added

**Comment by rcoder23** [comment]
close this issue sir . @HarshCasper thank you

**Pull request closed without merging**
