### PR TITLE
Stable marriage

### PR DESCRIPTION
**Pull request by salonishah01**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Added python code for stable marriage problem

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#1134

### CODE REVIEW

**Comment by salonishah01** [comment]
@HarshCasper Please review this pull request

**Comment by siddharth25pandey** [comment]
@salonishah01 Resolve the merge conflict

**Comment by salonishah01** [comment]
@siddharth25pandey resolved merge conflict.

**Review by siddharth25pandey — APPROVED** [review]
@salonishah01 LGTM
Able to merge
Thanks!

**Review by vatsalkesarwani12 — APPROVED** [review]
👍🏻

**Pull request merged**
