### PR TITLE
added huffman code issue-3306

### PR DESCRIPTION
**Pull request by kavyasree-123**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

yes

### Description

Huffman coding works on data stream that makes up the file to be compressed
output for input "testing code with inputs"  is:
huffcode first printed in row                                                                                                                                               
element printed in second row                                                                                                                                               
weights are printed last of row                                                                                                                                             
00        t 4                                                                                                                                                               
100         4                                                                                                                                                               
011       i 3                                                                                                                                                               
1011      e 2                                                                                                                                                               
1101      n 2                                                                                                                                                               
1111      s 2                                                                                                                                                               
0100      u 1                                                                                                                                                               
0101      w 1                                                                                                                                                               
10100     c 1                                                                                                                                                               
10101     d 1                                                                                                                                                               
11000     g 1                                                                                                                                                               
11001     h 1                                                                                                                                                               
11100     o 1                                                                                                                                                               
11101     p 1

### Checklist

- [yes ] I've read the contribution guidelines.
- [ yes] I've checked the issue list before deciding what to submit.
- [ yes] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
please verify

### CODE REVIEW

**Comment by kavyasree-123** [comment]
@bhav09 , @siddharth25pandey @HarshCasper , @ankitaggarwal23Kindly review the PR

**Comment by ankitaggarwal23** [comment]
@kavyasree-123 We don't accept PRs without any corresponding Issue. It is difficult for us to find your issue in tons of issues available. We can't review and merged incomplete PR's.

**Comment by ankitaggarwal23** [comment]
@kavyasree-123 Kindly open a new PR add the proper details and Link the issue no. in the description properly.

**Comment by kavyasree-123** [comment]
Hello I'm not able to create a new issue even though we have closes
including brncahes issues and pr it's still saying I'm having 2 open what
to do..

**Comment by ankitaggarwal23** [comment]
@kavyasree-123 I said to create a new PR not the issue. It's correct bot will close your issue because you are creating a new issue not the PR.

**Pull request closed without merging**
