### PR TITLE
Create Readme.md

### PR DESCRIPTION
**Pull request by Aanisha**
Please read [how to contribute](CONTRIBUTING.md) first!
# Description
Submission description here

Checklist
* [x] I've checked the issue list __BEFORE__ deciding what to submit
* [x] I've read the contribution guidelines
* [x] I've edited the README.md link to my code

## Don't forget to visit our [website](http://www.tesseractcoding.tech)!

Feel free to add this badge after your submission is accepted!

```
<a href=https://github.com/TesseractCoding/NeoAlgo>
   <img src=https://img.shields.io/badge/NeoAlgo-Contributor-brightgreen>
</a>
```

### CODE REVIEW

**Comment by Aanisha** [comment]
The readme file, for the problems branch.

**Comment by Aanisha** [comment]
Added few problems.

**Review by Vanshikagarg17 — APPROVED** [review]

**Review by Vanshikagarg17 — APPROVED** [review]

**Review by Vanshikagarg17 — APPROVED** [review]

**Comment by iamrajiv** [comment]
@all-contributors please add @Aanisha  for code

**Comment by iamrajiv** [comment]
@all-contributors please add @Aanisha for doc

**Comment by iamrajiv** [comment]
@all-contributors please add @Aanisha for documentation

**Pull request merged**
