### PR TITLE
Linear Regression added in python

### PR DESCRIPTION
**Pull request by kauravankit25**
Linear regression from scratch in python

### CODE REVIEW

**Comment by mar-galho** [comment]
Hi!

I have just two small requests, that will help us organizing the list. The first, if you could do us a favor and rename the file to remove the whitespace character, to allow it to be linked; the second, to edit the list README.md including "Linear Regression" in a bullet point list, as a link to the file you've submitted :)

Please let me know if you need further assistance with any of these tasks and I'll be more than glad to help!

**Comment by kauravankit25** [comment]
Sure, no problem.

**Comment by mar-galho** [comment]
Thanks for your contribution! It is much appreciated!

**Comment by mar-galho** [comment]
@all-contributors, please add @kauravankit25 for code

**Pull request merged**
