### PR TITLE
Anagram String code updated for issue #1969.

### PR DESCRIPTION
**Pull request by RuchiGitHu**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)
Yes
### Description

(Write your answer here.)

### Checklist

- [✓] I've read the contribution guidelines.
- [✓] I've checked the issue list before deciding what to submit.
- [✓] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)
I have updated anagram String code....
I have removed the package name and added a beginner description of the problem also in the end of the code I have included sample input/output and time, space complexity of my solution.

### CODE REVIEW

**Comment by pganguli** [comment]
> ### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?
> 
> (Write your answer here.)
> Yes
> ### Description
> 
> (Write your answer here.)
> ### Checklist
> 
>     * [✓] I've read the contribution guidelines.
> 
>     * [✓] I've checked the issue list before deciding what to submit.
> 
>     * [✓] I've edited the `README.md` and link to my code.
> 
> 
> ## Related Issues or Pull Requests
> 
> (Write your answer here.)
> I have updated anagram String code....
> I have removed the package name and added a beginner description of the problem also in the end of the code I have included sample input/output and time, space complexity of my solution.

Hey, just some quick advice: Try removing the "(Write your answer here)" from your response to the pull request template. Also, since it uses the markdown format, "[X]" is better than those "[unicode_tick_mark]" boxes in your checklist. :)

**Comment by HarshCasper** [comment]
@RuchiGitHu 

Please add the Issue Number in your PR Description, not on the PR title. Use `Fixes #XXX` and replace `XXX` with the Issue number you were supposed to work on. 

Second, you mentioned: `I've edited the README.md and link to my code.` No, you have not. Please don't give us a false impression on the same. I would really suggest you to take time to study the PRs that have been merged previously before the start of the coding period. Every Code File should have a corresponding README updates, that you have not made. 

Third, PRs made for GSSoC would only be reviewed once the Coding period starts. Thanks!

**Comment by RuchiGitHu** [comment]
> @RuchiGitHu
> 
> Please add the Issue Number in your PR Description, not on the PR title. Use `Fixes #XXX` and replace `XXX` with the Issue number you were supposed to work on.
> 
> Second, you mentioned: `I've edited the README.md and link to my code.` No, you have not. Please don't give us a false impression on the same. I would really suggest you to take time to study the PRs that have been merged previously before the start of the coding period. Every Code File should have a corresponding README updates, that you have not made.
> 
> Third, PRs made for GSSoC would only be reviewed once the Coding period starts. Thanks!

I apologize for inconvenience caused by me and for mistakes that I have made. I am beginner to contribute in open source but have desire to learn it.
As per your required changes, I will do it.

**Comment by HarshCasper** [comment]
> > @RuchiGitHu
> > Please add the Issue Number in your PR Description, not on the PR title. Use `Fixes #XXX` and replace `XXX` with the Issue number you were supposed to work on.
> > Second, you mentioned: `I've edited the README.md and link to my code.` No, you have not. Please don't give us a false impression on the same. I would really suggest you to take time to study the PRs that have been merged previously before the start of the coding period. Every Code File should have a corresponding README updates, that you have not made.
> > Third, PRs made for GSSoC would only be reviewed once the Coding period starts. Thanks!
> 
> I apologize for inconvenience caused by me and for mistakes that I have made. I am beginner to contribute in open source but have desire to learn it.
> As per your required changes, I will do it.

Really appreciate it. We are working on a handbook for contributions that would be ready before the start of the coding period. Please reach out to us if you are doubtful about anything and need some help. We would be more than happy to assist you.

**Comment by RuchiGitHu** [comment]
> > > @RuchiGitHu
> > > Please add the Issue Number in your PR Description, not on the PR title. Use `Fixes #XXX` and replace `XXX` with the Issue number you were supposed to work on.
> > > Second, you mentioned: `I've edited the README.md and link to my code.` No, you have not. Please don't give us a false impression on the same. I would really suggest you to take time to study the PRs that have been merged previously before the start of the coding period. Every Code File should have a corresponding README updates, that you have not made.
> > > Third, PRs made for GSSoC would only be reviewed once the Coding period starts. Thanks!
> > 
> > 
> > I apologize for inconvenience caused by me and for mistakes that I have made. I am beginner to contribute in open source but have desire to learn it.
> > As per your required changes, I will do it.
> 
> Really appreciate it. We are working on a handbook for contributions that would be ready before the start of the coding period. Please reach out to us if you are doubtful about anything and need some help. We would be more than happy to assist you.

Thanks for your support and guidance @HarshCasper @atarax665. Here is an edited readme file with updated PR for review. 
 https://github.com/TesseractCoding/NeoAlgo/pull/2217

**Pull request closed without merging**
