### PR TITLE
Implemented Counting Sort in Java

### PR DESCRIPTION
**Pull request by samir-0711**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Added Counting Sort in Java.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Issue #1776

### CODE REVIEW

**Review by srimanikantapalakollu — CHANGES_REQUESTED** [review]
Take the Array input Dynamically through the console.

**Comment by samir-0711** [comment]
@srimani-programmer Requested changes implemented in code. Please review it.

**Comment by samir-0711** [comment]
@srimani-programmer Please review it.

**Comment by samir-0711** [comment]
@shraddhavp please review this pr. And also add DWOC and level label.

**Review by iamrajiv — CHANGES_REQUESTED** [review]
@samir-0711 Add sample input-output.

**Comment by samir-0711** [comment]
@iamrajiv Sample input-output added. Please review it. Thanks

**Review by iamrajiv — APPROVED** [review]

**Pull request merged**
