### PR TITLE
Reverse2585

### PR DESCRIPTION
**Pull request by taruni-always**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes
### Description
Implementation of reversing individual words of a string using stacks. 
(Issue #2585)
I wanted to contribute under GSSoC '21. 

### Checklist

- [ yes] I've read the contribution guidelines.
- [yes ] I've checked the issue list before deciding what to submit.
- [yes ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

In referrence with: https://github.com/TesseractCoding/NeoAlgo/pull/2684#issuecomment-797569213

### CODE REVIEW

**Comment by taruni-always** [comment]
Please review this

**Comment by HarshCasper** [comment]
Don't push more than one code file in one single PR.

**Comment by taruni-always** [comment]
But u have pushed only one code file right? @HarshCasper

**Comment by taruni-always** [comment]
does this mean I've to make different PRs for C and Python? @HarshCasper

**Pull request closed without merging**
