### PR TITLE
C code issue #6711

### PR DESCRIPTION
**Pull request by TechSpiritSS**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

There was no C code for LCM in maths, so I write one here.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

issue #6711

### CODE REVIEW

**Comment by TechSpiritSS** [comment]
To Admin 
I really want to contribute but all existing issues are taken and I am not so much experienced in coding to do some advance stuff.

**Review by bhav09 — CHANGES_REQUESTED** [review]
Hey, can you please comment the code? And also update the markdown file with the file you are adding to the repo? Thanks!

**Comment by TechSpiritSS** [comment]
@bhav09 Added the comments and that Content File has its own separate PR which is PR #6714

**Review by ankitaggarwal23 — COMMENTED** [review]
We don't accept such code. It falls neither as a Data Structure not as an algorithm.

**Comment by TechSpiritSS** [comment]
But there is LCM so why HCF isn't accepted?

**Pull request closed without merging**
