### PR TITLE
Reversing individual words in a sentence in C++

### LINKED ISSUE #5799: Reversing individual words in a sentence
## 💥 Proposal

I want to add the code for reversing each individual word in a sentence without using stacks in C++

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

### PR DESCRIPTION
**Pull request by SAY-droid427**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Code for reversing individual words in a string without using stacks in C++.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Fixes https://github.com/TesseractCoding/NeoAlgo/issues/5799

### CODE REVIEW

**Comment by SAY-droid427** [comment]
@iamrajiv @HarshCasper Please review this PR

**Review by iamrajiv — APPROVED** [review]

**Comment by SAY-droid427** [comment]
@ankitaggarwal23 Please review.

**Comment by SAY-droid427** [comment]
@ankitaggarwal23 Please please review this PR.

**Review by ankitaggarwal23 — CHANGES_REQUESTED** [review]
Remove the .json file

**Review by ankitaggarwal23 — APPROVED** [review]

**Pull request merged**
