### PR TITLE
Caesar Cipher -Cryptography (Python)

### PR DESCRIPTION
**Pull request by ghost**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description
I have implemented Caesar Cipher in PYTHON
To shed some light on cryptographic algorithms, we begin with coding the basic Caesar Cipher which encrypts and decrypts messages with a specific shift value

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#422

### CODE REVIEW

**Comment by ghost** [comment]
@HarshCasper  @Kajol-Kumari please do review .. 😄

**Comment by ghost** [comment]
@atarax665 @SKAUL05 @siddharth25pandey I have resolved the merge conflicts, do review please

**Review by SKAUL05 — CHANGES_REQUESTED** [review]
Change variable names from alphabets to meaningful names.
Include docstrings in functions and add sample I/O

**Comment by ghost** [comment]
I have made the requested changes to the code and readme. Please review @SKAUL05 @siddharth25pandey @Kajol-Kumari @atarax665

**Pull request closed without merging**
