### PR TITLE
count no. of bits in a number in c++ added

### PR DESCRIPTION
**Pull request by shivammahajancse**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Yes)

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(#6198 )

### CODE REVIEW

**Comment by shivammahajancse** [comment]
Please review sir @HarshCasper @ankitaggarwal23 @atarax665 @gat786

**Review by ankitaggarwal23 — COMMENTED** [review]
Read the instructions mentioned on Gssoc discord yesterday. Do the changes as per that.

**Comment by shivammahajancse** [comment]
All changes done sir @ankitaggarwal23

**Review by ankitaggarwal23 — COMMENTED** [review]
We don't accept such code. It falls neither as a Data Structure not as an algorithm.

**Pull request closed without merging**
