### PR TITLE
Double factorial code in Python

### PR DESCRIPTION
**Pull request by rutujadhanawade**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

This is python code for finding Double factorial.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

 #930

### CODE REVIEW

**Comment by rutujadhanawade** [comment]
@Kajol-Kumari @iamrajiv @siddharth25pandey Please review this as a part of CH20.

**Review by iamrajiv — CHANGES_REQUESTED** [review]
@rutujadhanawade Format the according to PEP 8 rules. Refer this http://pep8online.com/

**Comment by rutujadhanawade** [comment]
I have done the changes . @iamrajiv

**Review by iamrajiv — APPROVED** [review]

**Review by atarax665 — APPROVED** [review]
LGTM :)

**Review by iamrajiv — CHANGES_REQUESTED** [review]
@rutujadhanawade Resolve the merge conflicts so that I can merge the PR.

**Comment by rutujadhanawade** [comment]
Why the Readme.md file in Python section has been removed? That's why I am getting merge conflicts. since it is complex so I am not able to solve it?
so should I just remove readme from my code?

**Comment by rutujadhanawade** [comment]
@iamrajiv done.

**Review by iamrajiv — CHANGES_REQUESTED** [review]
@rutujadhanawade Do not delete the `Python/README.md ` file.

**Comment by rutujadhanawade** [comment]
> @rutujadhanawade Do not delete the `Python/README.md ` file.

Actually in main repo `Python/README.md ` file doesnt exist thats why I was getting merge conflicts.  So what should I do now?

**Comment by iamrajiv** [comment]
@rutujadhanawade I think `Python/README.md` file got deleted due to #963. I have added `Python/README.md` in the main repo, please make the requested changes.

**Comment by rutujadhanawade** [comment]
@iamrajiv Please merge it.

**Review by iamrajiv — APPROVED** [review]

**Comment by iamrajiv** [comment]
@all-contributors please add @rutujadhanawade for code

**Pull request merged**
