### PR TITLE
Update README.md file of Python & C++

### PR DESCRIPTION
**Pull request by saatviknagpal**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Updated README.md of C++ having 2 Linked List programs , one of python and one of c++ itself. Also added the python "singly linked list" program to it's corresponding README.md

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Related Issue - #2872

### CODE REVIEW

**Comment by saatviknagpal** [comment]
@bhav09 Kindly review this PR.

**Comment by bhav09** [comment]
You are only updating the readme? And not the program files or you have done that already?

**Comment by saatviknagpal** [comment]
> You are only updating the readme? And not the program files or you have done that already?

Sir there is no problem in the program files, they work correctly. I just updated the README file because the Python program of "Singly Linked List" was in C++ programs.

**Comment by bhav09** [comment]
Okay, can you share the link to the PR that was merged in contrast to the program files that you had requested. Thanks

**Comment by saatviknagpal** [comment]
> Okay, can you share the link to the PR that was merged in contrast to the program files that you had requested. Thanks

Sir I can only find the link to "Singly Linked List in Python" PR - #435.

Can't find the link to "Singly linked list in c++"

**Review by HarshCasper — APPROVED** [review]

**Comment by saatviknagpal** [comment]
@HarshCasper Can you please assign level label to this PR ??

**Pull request merged**
