### PR TITLE
Avl tree

### PR DESCRIPTION
**Pull request by saimanoharhm**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)
Yes

### Description

(Write your answer here.)
I have added code for avl tree which includes insertion using recursive method and all the four rotations.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

### CODE REVIEW

**Comment by ankitaggarwal23** [comment]
@saimanoharhm We don't accept PRs without any corresponding Issue.

**Comment by ankitaggarwal23** [comment]
Capture

It is very difficult for us to review so I'm closing this. Kindly open a new pull request and link the issue.

**Review by ankitaggarwal23 — COMMENTED** [review]
Invalid PR, without an issue number.

**Comment by saimanoharhm** [comment]
@ankitaggarwal23 I have already created issue pls check issue #2903

**Pull request closed without merging**
