### PR TITLE
Dijktra

### PR DESCRIPTION
**Pull request by Amit366**
issue: #2365

### Have you read the [Contributing Guidelines on Pull Requests]
Yes

### Description

I have implemented Dijktra's Algorithm in Java

### CODE REVIEW

**Review by HarshCasper — CHANGES_REQUESTED** [review]
Code plagiarized from [here](https://www.geeksforgeeks.org/fast-io-in-java-in-competitive-programming/)

**Comment by Amit366** [comment]
@HarshCasper only the first FastReader is same but the remaining code is totally different. 
I used it as the code was giving runtime error in Hackerrank.

**Comment by HarshCasper** [comment]
Still the case for plagiarism stands!

**Comment by Amit366** [comment]
So what can I do? Should I change the variables? @HarshCasper

**Comment by Amit366** [comment]
@HarshCasper please reopen this issue

**Comment by HarshCasper** [comment]
Plagiarism is taken seriously and shows a malicious intent that can harm the overall health of the project. We will not reopen the Issue/PR and you can feel free to take up other Issues and work on them.

**Pull request closed without merging**
