### PR TITLE
added stack problem

### PR DESCRIPTION
**Pull request by reerajput930**
#4326

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

yes

## Related Issues or Pull Requests

issue no =  #4326

### CODE REVIEW

**Review by ankitaggarwal23 — CHANGES_REQUESTED** [review]
Few changes: 

- Add Multi-Line Comments 
- Add a beginner-friendly description at the top
- Use proper code Format 
- Remove extra lines of code and spaces
- Add sample I/O at the end of the Code
- Add Time and Space Complexity at the end of the Code   
- Add new line at the EOF

Readme.md file update missing.

**Comment by reerajput930** [comment]
@ankitaggarwal23, I have made the changes, plz review it and merge it, so that I can move on.

**Review by HarshCasper — CHANGES_REQUESTED** [review]
Make README updates

**Comment by reerajput930** [comment]
@HarshCasper sure

**Comment by reerajput930** [comment]
@HarshCasper I have committed, plz review it and merge it.

**Review by ankitaggarwal23 — COMMENTED** [review]
Someone already did this issue here #3481. Kindly check before opening an issue.

**Pull request closed without merging**
