### PR TITLE
Prime Number #1372 #1410

### PR DESCRIPTION
**Pull request by sayantan1413**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes I have read the contributing guidelines

### Description

Solved Prime Number problem #1372 in C-Sharp language.

### Checklist

- [ Y ] I've read the contribution guidelines.
- [ Y ] I've checked the issue list before deciding what to submit.
- [ Y ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#1372 #1410

### CODE REVIEW

**Comment by sayantan1413** [comment]
In the second commit I have reduced the time complexity and mentioned the time complexity and space complexity

**Comment by sayantan1413** [comment]
@atarax665 can you suggest me what more changes I need to do?

**Comment by charlie219** [comment]
@sayantan1413 update the `README.md` file under C-sharp folder under Mathematics section

**Comment by HarshCasper** [comment]
I'm closing the PR due to no activity. If you would like to reopen this PR to be reviewed please join the [Slack](https://join.slack.com/t/tesseractcodi-bxq5968/shared_invite/zt-ju6c0nqq-KgkTvFyxjNVbDRBIjADanw) and drop me a message.

**Pull request closed without merging**
