### PR TITLE
Queue issue- #1780 #DWOC

### PR DESCRIPTION
**Pull request by shloka-gupta**
It is in PEP8 format (as far as my research on PEP8 goes) and I made the basic changes asked

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

### Description

(Write your answer here.)

### Checklist

- [ YES] I've read the contribution guidelines.
- [YES ] I've checked the issue list before deciding what to submit.
- [YES ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

It'a the queue part of issue #1780 .

### CODE REVIEW

**Comment by shloka-gupta** [comment]
Let me know, if any changes are required

**Comment by shloka-gupta** [comment]
@atarax665

**Review by atarax665 — APPROVED** [review]
LGTM :+1:

**Comment by shloka-gupta** [comment]
Could you add the DWOC label?
@HarshCasper

**Pull request merged**
