### PR TITLE
check image analysis

### PR DESCRIPTION
**Pull request by Vrindagupta6828**
Please read [how to contribute](CONTRIBUTING.md) first!
# Description
Submission description here

Checklist
* [ ] I've checked the issue list __BEFORE__ deciding what to submit
* [ ] I've read the contribution guidelines
* [ ] I've edited the README.md link to my code

## Don't forget to visit our [website](http://www.tesseractcoding.tech)!

Feel free to add this badge after your submission is accepted!

```
<a href=https://github.com/TesseractCoding/NeoAlgo>
   <img src=https://img.shields.io/badge/NeoAlgo-Contributor-brightgreen>
</a>
```

### CODE REVIEW

**Comment by Vrindagupta6828** [comment]
I have added Image analysis using numpy and also updated the readme.
Please merge it.

**Comment by mar-galho** [comment]
@VijayaGB98 could you review this?

**Comment by mar-galho** [comment]
@Vrindagupta6828 there is a conflict with the README.md file. Could you solve it?

Thanks!

**Comment by Vrindagupta6828** [comment]
Sorry i am not able to resolve the conflict it is in the README. @ricardoprins

**Comment by vgb-codes** [comment]
@ricardoprins will take a look at this.

**Comment by vgb-codes** [comment]
@Vrindagupta6828 Can you first try to fix the README? Remove your entries from the README and check if that resolves the conflict. Make sure to pull beforehand.

**Comment by Vrindagupta6828** [comment]
@VijayaGB98 yes done now there are no conflicts.Now you can merge it.

**Pull request merged**
