### PR TITLE
rabinkarp algo in c

### PR DESCRIPTION
**Pull request by kavyasree-123**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

yes

### Description

I have added the new rabin karp algorithm which is very helpful in c lang into ds in code

### Checklist

- [ yes] I've read the contribution guidelines.
- [ yes ] I've checked the issue list before deciding what to submit.
- [ yes ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

I created a pull request on issue [#2943 ](https://github.com/TesseractCoding/NeoAlgo/issues/2943) and added the algorithm into c in ds

### CODE REVIEW

**Comment by kavyasree-123** [comment]
**added rabin karp algo issue#2943** with
 **well written description** as well as **inputs and outputs**

**Comment by kavyasree-123** [comment]
updated code with well description and tired to solve on own

**Review by siddharth25pandey — APPROVED** [review]
@kavyasree-123 Well formatted & structured code 💯 
LGTM, able to merge.
We are looking forward for your ahead contribution

**Comment by siddharth25pandey** [comment]
@all-contributors please add @kavyasree-123 for her code

**Pull request merged**
