### PR TITLE
Manacher's algorithm in Java

### PR DESCRIPTION
**Pull request by ritvij14**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?
Yes
(Write your answer here.)

### Description
Manacher's algorithm is an algorithm to find the largest palindromic substring in a string in O(n) time. It revolves around the concept of not rechecking each element if it already exists as a smaller palindrome, as a suffix/prefix of a bigger palindrome.
(Write your answer here.)

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
Issue #667 
(Write your answer here.)

### CODE REVIEW

**Comment by ritvij14** [comment]
@siddharth25pandey @Kajol-Kumari @plazzy99 @SKAUL05 @iamrajiv please review and tell me what I should change. I have pulled the latest code from the master branch and it doesn't show any conflicts in terminal/VSCode.

**Comment by vatsalkesarwani12** [comment]
Please remove the merge conflicts.

**Comment by ritvij14** [comment]
@plazzy99 how to do this?? Both GitHub and VS Code say that there are no merge conflicts.

**Comment by vatsalkesarwani12** [comment]
try removing you edit in readme file 
might be it is conflicting

**Comment by ritvij14** [comment]
@plazzy99 I removed the edits in README.md and now it's passing the tests. So should I not put any changes in README.md for the path of the algorithm?

**Comment by iamrajiv** [comment]
@ritvij14 Do not worry about Merge Conflicts Labeler like it does not check merge conflicts but add labels to the PR if the PR has merge conflicts. So if Merge Conflicts Labeler is failing it does not mean that the branch has conflicts. If there are merge conflicts it will show like this 
.

**Comment by vatsalkesarwani12** [comment]
> @plazzy99 I removed the edits in README.md and now it's passing the tests. So should I not put any changes in README.md for the path of the algorithm?

If you find merge conflicts then don't make an edit in readme file instead mention it in the pr

**Comment by ritvij14** [comment]
@iamrajiv ok understood. But should I put changes in README for the path to the Java program I have written?

**Comment by iamrajiv** [comment]
@ritvij14 please update the readme

**Comment by ritvij14** [comment]
@iamrajiv done.

**Review by vatsalkesarwani12 — CHANGES_REQUESTED** [review]
```
Enter a string:
bdabkaplhaahlpahdbc
Length of longest substring: 10
lhaahlpa

Length of longest substring: 10
```
Test Case Failing

**Comment by ritvij14** [comment]
@plazzy99 but it's showing correctly on mine

image

**Review by vatsalkesarwani12 — APPROVED** [review]

**Review by iamrajiv — APPROVED** [review]

**Review by siddharth25pandey — APPROVED** [review]
Good to go
Able to merge
Thanks!

**Pull request merged**
