### PR TITLE
Window sliding technique(#452)

### PR DESCRIPTION
**Pull request by sukritidawar**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Added the solution in cp folder.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

### CODE REVIEW

**Comment by sukritidawar** [comment]
@Kajol-Kumari @plazzy99 Please review

**Comment by vatsalkesarwani12** [comment]
One pull request for one issue

**Comment by sukritidawar** [comment]
> One pull request for one issue

Yeh, I figured that but wasn't able to understand how should I separate them....because I don't know that how did both of the branches merged together...could you please guide me?

**Comment by vatsalkesarwani12** [comment]
> > One pull request for one issue
> 
> Yeh, I figured that but wasn't able to understand how should I separate them....because I don't know that how did both of the branches merged together...could you please guide me?

you have to create branch from the head branch 
what you are doing is after making a pr, you are making another branch from that branch

don't worry follow few youtube git tutorial and make changes 
take time to understand concepts

**Comment by HarshCasper** [comment]
Add the Issue you are trying to solve

**Pull request closed without merging**
