### PR TITLE
Evaluation of polynomial using linked list in C 

### PR DESCRIPTION
**Pull request by Vishruta-Patil**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?
yes
(Write your answer here.)

### Description
Create , Display and evaluate polynomial using linked list in C
(Write your answer here.)

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
#2625
(Write your answer here.)

### CODE REVIEW

**Comment by Vishruta-Patil** [comment]
@iamrajiv I have added the code. But the checks are not getting passed . Please help me with it.

**Comment by iamrajiv** [comment]
> @iamrajiv I have added the code. But the checks are not getting passed . Please help me with it.

@Vishruta-Patil Do not worry about it you can ignore it, there is some glitch from DeepSource end.

**Review by iamrajiv — CHANGES_REQUESTED** [review]
@Vishruta-Patil Please remove the unnecessary files. Also, add the issue number.

**Comment by Vishruta-Patil** [comment]
> @Vishruta-Patil Please remove the unnecessary files. Also, add the issue number.

@iamrajiv I have added issue number. Can you pls mention which files do I have to remove

**Comment by Vishruta-Patil** [comment]
I have removed the heapify file

**Review by HarshCasper — CHANGES_REQUESTED** [review]
Don't push more than one code file in a single PR

**Pull request closed without merging**
