### PR TITLE
Sudoku Solver in C

### PR DESCRIPTION
**Pull request by mahimagoyalx**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Code for Sudoku Solver in C. 
It uses backtracking to solve the given sudoku board.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#976

### CODE REVIEW

**Comment by mahimagoyalx** [comment]
@iamrajiv @siddharth25pandey Please review.

**Review by iamrajiv — APPROVED** [review]

**Comment by mahimagoyalx** [comment]
@plazzy99 @siddharth25pandey please review.

**Review by siddharth25pandey — APPROVED** [review]
@mahimagoyalx Looks fine to me
Able to merge
Thanks!

**Comment by mahimagoyalx** [comment]
@Kajol-Kumari @SKAUL05 @atarax665 please review.

**Review by SKAUL05 — APPROVED** [review]

**Comment by mahimagoyalx** [comment]
@iamrajiv Kindly merge this pull request, it has got 3 approvals.

**Comment by siddharth25pandey** [comment]
@all-contributors please add @mahimagoyalx  for her code.

**Pull request merged**
