### PR TITLE
Small fixes in Automorphic number code in dart.

### PR DESCRIPTION
**Pull request by ritvij14**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Fixes to dart code indicated by VS Code tool. Typecasting and null-safety.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

### CODE REVIEW

**Comment by bhav09** [comment]
@ritvij14,  Can you share the replit link so that mentors can review the working of the code. Thanks

**Comment by ritvij14** [comment]
> @ritvij14, Can you share the replit link so that mentors can review the working of the code. Thanks

@bhav09 https://replit.com/@ritvij14/DSA-NeoAlgo#main.dart
One thing about repl, it does not have 'non-nullable' for dart yet, so cannot add `!` to input in that. But VS Code extension shows an error there.

**Comment by bhav09** [comment]
image
Pops this error. Please have a look at it and get back to me/any other mentor for the review. Thanks :)

**Comment by ritvij14** [comment]
@bhav09 yes corrected it please have a look.

**Pull request merged**
