### PR TITLE
Added Tim Sort Implementation in Python 3

### PR DESCRIPTION
**Pull request by amulya-0706**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Tim Sort is a sorting algorithm that is a hybrid of merge sort and binary insertion sort algorithm. It is a stable algorithm and works best on real-time data. In this, the list that needs to be sorted is first analyzed, and based on that it is divided into blocks known as Run. These runs are sorted using insertion sort one by one and then by merging these runs using the combine function used in merge sort. If the size of the Array is less than run, then Array gets sorted just by using Insertion Sort. The size of the run may vary from 32 to 64 depending upon the size of the array.

Code file is added and Documentation is updated for 'TimSort.py'.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

The PR is with reference to issue #7284

### CODE REVIEW

**Comment by amulyavarshney** [comment]
@ankitaggarwal23 @HarshCasper Can you please review my PR

**Comment by amulya-0706** [comment]
@ankitaggarwal23 @iamrajiv @anushkrishnav Please review my PR.

**Review by iamrajiv — APPROVED** [review]

**Review by siddharth25pandey — APPROVED** [review]
@amulyavarshney LGTM 💯 Able to merge

**Comment by amulya-0706** [comment]
Thanks!!

**Pull request merged**
