### PR TITLE
Kosaraju's Algorithm added C++

### PR DESCRIPTION
**Pull request by devanshiv123**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description
Kosaraju's Algorithm added C++

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

### CODE REVIEW

**Review by siddharth25pandey — APPROVED** [review]
@devanshiv123 I already reviewed the same [previous one](https://github.com/TesseractCoding/NeoAlgo/pull/768)
Looks fine to me.

**Comment by devanshiv123** [comment]
> @devanshiv123 I already reviewed the same previous [one](https://github.com/TesseractCoding/NeoAlgo/pull/768)
> Looks fine to me.

@siddharth25pandey  The merge conflict Labeler is still showing the conflicts but the branch is even with the origin.

**Comment by siddharth25pandey** [comment]
> > @devanshiv123 I already reviewed the same previous [one](https://github.com/TesseractCoding/NeoAlgo/pull/768)
> > Looks fine to me.
> 
> @siddharth25pandey The merge conflict Labeler is still showing the conflicts but the branch is even with the origin.

@devanshiv123  Yeah I saw, but this branch has no conflicts with base branch.
Will see after approval of other two mentors

**Comment by devanshiv123** [comment]
> > > @devanshiv123 I already reviewed the same previous [one](https://github.com/TesseractCoding/NeoAlgo/pull/768)
> > > Looks fine to me.
> > 
> > 
> > @siddharth25pandey The merge conflict Labeler is still showing the conflicts but the branch is even with the origin.
> 
> @devanshiv123 Yeah I saw, but this branch has no conflicts with base branch.
> Will see after approval of other two mentors

Okay Thanks!

**Review by iamrajiv — APPROVED** [review]

**Comment by iamrajiv** [comment]
@devanshiv123 I think this is duplicate of #768.

**Comment by devanshiv123** [comment]
> @devanshiv123 I think this is duplicate of #768.

@iamrajiv Yes it is as I was asked to make a new PR because there were a lot of conflicts in previous one.

**Comment by iamrajiv** [comment]
@devanshiv123 I do not see any conflicts in #768.

**Comment by iamrajiv** [comment]
@devanshiv123 Do not worry about Merge Conflicts Labeler like it does not check merge conflicts but add labels to the PR if the PR has merge conflicts. So if Merge Conflicts Labeler is failing it does not mean that the branch has conflicts. If there are merge conflicts it will show like this 
.

**Comment by iamrajiv** [comment]
@devanshiv123 I am closing this PR as a duplicate of #768

**Comment by devanshiv123** [comment]
> @devanshiv123 I do not see any conflicts in #768.

@iamrajiv Actually a mentor had only commented that there are conflicts in #768 .

**Comment by iamrajiv** [comment]
@devanshiv123 Both this PR and #768 has no merge conflicts and #768 got 3 approval so I have merged #768 and closed this PR.

**Comment by devanshiv123** [comment]
Okay Thanks!

**Pull request closed without merging**
