### PR TITLE
Added the code for Converting decimal number to binary in C++ Problem

### PR DESCRIPTION
**Pull request by SrishtiArya07**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)
yes

### Description

(Write your answer here.)

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#2612

### CODE REVIEW

**Review by iamrajiv — APPROVED** [review]

**Review by iamrajiv — CHANGES_REQUESTED** [review]
@SrishtiArya07 Update the readme file.

**Comment by SrishtiArya07** [comment]
> @SrishtiArya07 Update the readme file.

I've already updated the readme file 11d24c26e8bc9beaf0aa03a77b33569ec2e990a0

**Review by atarax665 — APPROVED** [review]
Update README.md
Possible challenge: Support negative decimal numbers as well :)

**Review by iamrajiv — APPROVED** [review]

**Comment by iamrajiv** [comment]
@all-contributors bot please add @SrishtiArya07 for code

**Pull request merged**
