### PR TITLE
Spiral Matrix in Java

### PR DESCRIPTION
**Pull request by raksha009**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes
### Description

Code added for Spiral Matrix in java
### Checklist

- [X] I've read the contribution guidelines.
- [X] I've checked the issue list before deciding what to submit.
- [X] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Issue #792

### CODE REVIEW

**Review by iamrajiv — CHANGES_REQUESTED** [review]
@raksha009 update the readme and remove unnecessary line breaks from the program. Also, add time and space complexity.

**Review by iamrajiv — CHANGES_REQUESTED** [review]
@raksha009 Your code is not running fine. Many of the variables are not been initialized with values like `i`, `j`, `k1`, `k2`.

**Review by iamrajiv — APPROVED** [review]

**Review by Kajol-Kumari — APPROVED** [review]
Codewise LGTM :+1:  @raksha009 you should do a little bit of commenting on your code for better organization. Rest is good to go.

**Comment by raksha009** [comment]
@atarax665 plz review my pr and merge it. Only the last review is pending. Thanks

**Pull request merged**
