### PR TITLE
Least Common Multiple for large numbers

### PR DESCRIPTION
**Pull request by narayan2111**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

The least common multiple of two positive integers 𝑎 and 𝑏 is the least positive integer 𝑚 that is divisible by both 𝑎 and 𝑏.

Task. Given two integers 𝑎 and 𝑏, find their least common multiple.
Input Format. The two integers 𝑎 and 𝑏 are given in the same line separated by space.
Constraints. 1≤𝑎, 𝑏≤107.
Output Format. Output the least common multiple of 𝑎 and 𝑏

### Checklist

- [Y] I've read the contribution guidelines.
- [Y] I've checked the issue list before deciding what to submit.
- [Y] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#1300

### CODE REVIEW

**Comment by narayan2111** [comment]
kindly review this PR @iamrajiv @SKAUL05 @plazzy99

**Review by vatsalkesarwani12 — APPROVED** [review]
👍🏻

**Review by iamrajiv — APPROVED** [review]

**Comment by narayan2111** [comment]
Kindly review this PR @SKAUL05

**Review by SKAUL05 — APPROVED** [review]

**Comment by narayan2111** [comment]
Kindly merge this PR  sir and also label it hacktoberfest added. @iamrajiv

**Pull request merged**
