### PR TITLE
Refactored code of Armstrong Number

### PR DESCRIPTION
**Pull request by deeptea22**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes.

### Description

Refactored the code to find if a number is an Armstrong Number

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

### CODE REVIEW

**Review by bhav09 — CHANGES_REQUESTED** [review]
Please add comments to your code. 
Complexity and Sample I/O is also missing from your code sample.

**Comment by deeptea22** [comment]
@bhav09 Hey, The Complexity Analysis  Sample I/O are already present and i didnt write the original code. I refactored this as instructed by @HarshCasper in NeoAlgo-Docs.

**Comment by bhav09** [comment]
My bad. Had to review a lot of lots, hence made an error.

**Comment by deeptea22** [comment]
> My bad. Had to review a lot of lots, hence made an error.

No problem :)

**Review by HarshCasper — APPROVED** [review]

**Pull request merged**
