### PR TITLE
 Added Prims Algo in python

### PR DESCRIPTION
**Pull request by Yuvraj-kadale**
issue #479 solved
Graphs vertex inputs to be given by the user

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)
YES
### Description
The output of the Algo

Capture

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

### CODE REVIEW

**Review by siddharth25pandey — APPROVED** [review]
@Yuvraj-kadale Looks fine to me, just add the **README** file details

**Review by SKAUL05 — APPROVED** [review]

**Review by Kajol-Kumari — APPROVED** [review]
LGTM :)

@Yuvraj-kadale  Please add this file path in `readme.md` and it will be good to go :)

**Comment by Yuvraj-kadale** [comment]
> 
> 
> @Yuvraj-kadale Looks fine to me, just add the **README** file details
@siddharth25pandey @Kajol-Kumari I think by mistake, the branch from where I sent this PR got deleted.
Is there any way to recover? or update the Readme file!?
or shall i send a new pr again?

**Comment by siddharth25pandey** [comment]
@Yuvraj-kadale Please add the **README** file details in this PR only & change your branch name (Presently showing **unknown repo**)
Except this everything is fine

**Comment by Yuvraj-kadale** [comment]
> 
> 
> @Yuvraj-kadale Please add the **README** file details in this PR only & change your branch name (Presently showing **unknown repo**)
> Except this everything is fine

@siddharth25pandey it is showing **unknown repo** because the branch got deleted. is there any way to recover?
i apologise for the in convince caused.

**Comment by siddharth25pandey** [comment]
> > @Yuvraj-kadale Please add the **README** file details in this PR only & change your branch name (Presently showing **unknown repo**)
> > Except this everything is fine
> 
> @siddharth25pandey it is showing **unknown repo** because the branch got deleted. is there any way to recover?
> i apologise for the in convince caused.

@Yuvraj-kadale There is no way to recover the branch you deleted. 
Only way is, do [this](https://github.com/TesseractCoding/NeoAlgo/pull/572#issuecomment-678625962) or close this PR & create a fresh one.

**Comment by Yuvraj-kadale** [comment]
> 
> 
> > > @Yuvraj-kadale Please add the **README** file details in this PR only & change your branch name (Presently showing **unknown repo**)
> > > Except this everything is fine
> > 
> > 
> > @siddharth25pandey it is showing **unknown repo** because the branch got deleted. is there any way to recover?
> > i apologise for the in convince caused.
> 
> @Yuvraj-kadale There is no way to recover the branch you deleted.
> Only way is, do [this](https://github.com/TesseractCoding/NeoAlgo/pull/572#issuecomment-678625962) or close this PR & create a fresh one.

@siddharth25pandey @SKAUL05 @Kajol-Kumari  @atarax665  closing this pr and sent a new PR #683

**Pull request closed without merging**
