### PR TITLE
Copy set bits in a range in C++

### PR DESCRIPTION
**Pull request by scortier**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

YES

### Description

Fixed #6144 

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Issue #6144

### CODE REVIEW

**Comment by anushkrishnav** [comment]
Please attach the issue that you made for this PR

**Comment by scortier** [comment]
Attached ,please check.

**Review by ankitaggarwal23 — COMMENTED** [review]
Read the instructions mentioned on Gssoc discord yesterday. Do the changes as per that.

**Comment by scortier** [comment]
Can you name the channel ,where the new instructions have been mentioned, i am unable to find those.

**Comment by ankitaggarwal23** [comment]
> Can you name the channel ,where the new instructions have been mentioned, i am unable to find those.

#neo-algo

**Comment by ankitaggarwal23** [comment]
> > Can you name the channel ,where the new instructions have been mentioned, i am unable to find those.
> 
> #neo-algo

Are you a gssoc participant or not?

**Comment by scortier** [comment]
> > > Can you name the channel ,where the new instructions have been mentioned, i am unable to find those.
> > 
> > 
> > #neo-algo
> 
> Are you a gssoc participant or not?

Yes ,but i can't see any neo-algo section in GSSOC. I can see it in Tesseract Coding server

**Comment by scortier** [comment]
> > > > Can you name the channel ,where the new instructions have been mentioned, i am unable to find those.
> > > 
> > > 
> > > #neo-algo
> > 
> > 
> > Are you a gssoc participant or not?
> 
> Yes ,but i can't see any neo-algo section in GSSOC. I can see it in Tesseract Coding server

Can you tell me ,what changes are further required in this PR ?

**Review by ankitaggarwal23 — CHANGES_REQUESTED** [review]
Few changes: 

- Add Multi-Line Comments 
- Add a beginner-friendly description at the top
- Use proper code Format 
- Remove extra lines of code and spaces
- Add sample I/O at the end of the Code
- Add Time and Space Complexity at the end of the Code   
- Add new line at the EOF
- Use proper display message how you are reading and writing outputs
- Add input-output prompts to make the program more interactive.

**Comment by scortier** [comment]
@ankitaggarwal23 i have made the required changes .Please have a look.

**Review by ankitaggarwal23 — CHANGES_REQUESTED** [review]
Few changes: 

- Add Multi-Line Comments 
- Add a beginner-friendly description at the top
- Use proper code Format 
- Remove extra lines of code and spaces
- Add sample I/O at the end of the Code
- Add Time and Space Complexity at the end of the Code   
- Add a new line at the EOF
- Use proper display message how you are reading and writing outputs
- Add input-output prompts to make the program more interactive.

**Review by ankitaggarwal23 — COMMENTED** [review]
Closing this due to inactivity. Thank you for your valuable time.😊

**Pull request closed without merging**
