### PR TITLE
Implementation of N-Queen Problem in C

### PR DESCRIPTION
**Pull request by subhayu99**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Implemented the *N-Queen* Problem in *C*, added it to the dp folder of C directory and updated the README.md of C directory.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Corresponding issue can be found [here](https://github.com/TesseractCoding/NeoAlgo/issues/424).

### CODE REVIEW

**Review by siddharth25pandey — APPROVED** [review]
@subhayu99 Looks fine to me.
Able to merge.
Thanks!

**Review by iamrajiv — APPROVED** [review]

**Review by subhayu99 — COMMENTED** [review]
Corresponding Issue: https://github.com/TesseractCoding/NeoAlgo/issues/424

**Review by siddharth25pandey — APPROVED** [review]

**Review by Abhijit2505 — APPROVED** [review]
Looking Good To me.

**Review by subhayu99 — COMMENTED** [review]
Thanks for merging

**Comment by iamrajiv** [comment]
@all-contributors please add @subhayu99  for code

**Pull request merged**
