### PR TITLE
Added the code for quick sorting in C by taking pivot element

### PR DESCRIPTION
**Pull request by Sakshi2517**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

### Description
quick sorting of array 
here we will take end element as a pivot element of an array so we will get the position to interchange the pivot with index so that all the elements greater than pivot wil be right side and lesser than pivot will be left side

### Checklist

- [yes ] I've read the contribution guidelines.
- [ yes] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

### CODE REVIEW

**Review by ankitaggarwal23 — CHANGES_REQUESTED** [review]
Few changes: 

- Add Multi-Line Comments 
- Add a beginner-friendly description at the top
- Use proper code Format
- Edit the README.md and link to your code.
- Remove extra lines of code and spaces
- Add sample I/O at the end of the Code
- Add Time and Space Complexity at the end of the Code

**Review by Sakshi2517 — COMMENTED** [review]
I have added Multi line comments with a description on top,removed extra lines of codes and spaces.added  a sample input at the end of the code.
@ankitaggarwal23 Kindly go through it 
if there is more changes required please tell me

**Comment by ankitaggarwal23** [comment]
> I have added Multi line comments with a description on top,removed extra lines of codes and spaces.added a sample input at the end of the code.
> @ankitaggarwal23 Kindly go through it
> if there is more changes required please tell me
     
You did the same mistake now as well.

**Review by ankitaggarwal23 — CHANGES_REQUESTED** [review]
Few changes: 

- Add Multi-Line Comments 
- Add a beginner-friendly description at the top
- Use proper code Format
- Edit the README.md and link to your code.
- Remove extra lines of code and spaces
- Add sample I/O at the end of the Code
- Add Time and Space Complexity at the end of the Code

**Comment by ankitaggarwal23** [comment]
If you are not getting these things I'm suggesting you to please have a look into any merge PR you will get some idea how they are following all those steps [here](https://github.com/TesseractCoding/NeoAlgo/pull/2971/files)

**Comment by atarax665** [comment]
Closing due to inactivity.

**Pull request closed without merging**
