### PR TITLE
Added the code for Bucket Sort in Python

### PR DESCRIPTION
**Pull request by Aarushi3113**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes, I have read and understood the contributing guidelines on Pull Requests.

### Description

Added Bucket Sort in Python Language

### Checklist

- [* ] I've read the contribution guidelines.
- [* ] I've checked the issue list before deciding what to submit.
- [*] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#2461

### CODE REVIEW

**Comment by siddharth25pandey** [comment]
@Aarushi3113 Add the Readme file changes.

**Comment by Aarushi3113** [comment]
I have added the changes in README file.

**Review by siddharth25pandey — APPROVED** [review]
@Aarushi3113 LGTM, Able to merge.
Thanks!

**Comment by siddharth25pandey** [comment]
all-contributors please add @Aarushi3113 for her code

**Comment by siddharth25pandey** [comment]
@all-contributors please add @Aarushi3113 for her code

**Pull request merged**
