### PR TITLE
Karatsuba Multiplication in Golang

### PR DESCRIPTION
**Pull request by GajjarMiten**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?
Yes, I have read the Contributing Guidelines on Pull Requests.

### Description

- Added implementation of the program for Karastuba Algorithm for multiplication in Golang 

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

the issue #704  for Go language

### CODE REVIEW

**Comment by GajjarMiten** [comment]
Hey @iamrajiv @plazzy99 @SKAUL05 @Kajol-Kumari 
could you please review this pr?

**Review by atarax665 — APPROVED** [review]
Looks good to me. :+1:

**Review by iamrajiv — APPROVED** [review]

**Review by siddharth25pandey — APPROVED** [review]
@GajjarMiten Looks fine to me
Able to merge
Thanks!

**Comment by siddharth25pandey** [comment]
@all-contributors please add @GajjarMiten for his code

**Pull request merged**
