### PR TITLE
Heap Sorting Python Code

### PR DESCRIPTION
**Pull request by nutanaarohi123**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Python Code for Heap Sorting.
Heap is a special case of a balanced binary tree data structure where the root-node key is compared with its children and arranged accordingly.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

### CODE REVIEW

**Comment by nutanaarohi123** [comment]
Kindly review @HarshCasper @SKAUL05 @iamrajiv  @siddharth25pandey

**Review by SKAUL05 — APPROVED** [review]

**Comment by anushkrishnav** [comment]
Hey, good work, From what I can understand you have just used heaq to achieve HeapSort. Is it possible for you to implement Heapsort so that people can learn and understand how heap sort works internally? :)

**Comment by nutanaarohi123** [comment]
> Hey, good work, From what I can understand you have just used heaq to achieve HeapSort. Is it possible for you to implement Heapsort so that people can learn and understand how heap sort works internally? :)

Sure.will create another PR for that..what I think one must also know use of heapq..this is something new..many of we are unaware that we have heapq function and unaware of its application..So..I would request you too let me create another PR.for that..

**Comment by nutanaarohi123** [comment]
> > Hey, good work, From what I can understand you have just used heaq to achieve HeapSort. Is it possible for you to implement Heapsort so that people can learn and understand how heap sort works internally? :)
> 
> Sure.will create another PR for that..what I think one must also know use of heapq..this is something new..many of we are unaware that we have heapq function and unaware of its application..So..I would request you too let me create another PR.for that.. @anushkrishnav

**Comment by nutanaarohi123** [comment]
> Hey, good work, From what I can understand you have just used heaq to achieve HeapSort. Is it possible for you to implement Heapsort so that people can learn and understand how heap sort works internally? :)

Okay..will change this.

**Comment by nutanaarohi123** [comment]
> > Hey, good work, From what I can understand you have just used heaq to achieve HeapSort. Is it possible for you to implement Heapsort so that people can learn and understand how heap sort works internally? :)
> 
> Okay..will add another file too related to that.

**Comment by anushkrishnav** [comment]
> > Hey, good work, From what I can understand you have just used heaq to achieve HeapSort. Is it possible for you to implement Heapsort so that people can learn and understand how heap sort works internally? :)
> 
> Okay..will change this.

No need to change just add implementation above or below will be helpful  to learn and understand .keep up the great work

**Comment by nutanaarohi123** [comment]
> > > Hey, good work, From what I can understand you have just used heaq to achieve HeapSort. Is it possible for you to implement Heapsort so that people can learn and understand how heap sort works internally? :)
> > 
> > 
> > Okay..will change this.
> 
> No need to change just add implementation above or below will be helpful to learn and understand .keep up the great work

@anushkrishnav ..kindly review.Updated file as required.

**Comment by nutanaarohi123** [comment]
Kindly review @iamrajiv  @HarshCasper

**Review by iamrajiv — CHANGES_REQUESTED** [review]
@nutanaarohi123 Your code is same as this https://www.geeksforgeeks.org/max-heap-in-python/

**Pull request closed without merging**
