### PR TITLE
#1175 cp sets question

### PR DESCRIPTION
**Pull request by imPGupta**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

CP Sets Question
[Problem Link](https://www.hackerrank.com/challenges/no-idea/problem)

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#1175

### CODE REVIEW

**Comment by imPGupta** [comment]
@iamrajiv Please review my PR

**Review by iamrajiv — APPROVED** [review]

**Comment by imPGupta** [comment]
@atarax665 Please review my PR

**Review by atarax665 — CHANGES_REQUESTED** [review]
Format your code as:
```
/* There is an array of n integers. There are also 2 disjoint sets, A and B, each containing m integers.
You like all the integers in set A and dislike all the integers in set B. Your initial happiness is 0. 
For each i integer in the array, if i e A , you add 1 to your happiness. If i e B, you add -1 to your happiness.
Otherwise, your happiness does not change. Output your final happiness at the end.

	Input Format
	
	The first line contains integers n and m separated by a space.
	The second line contains n integers, the elements of the array.
	The third and fourth lines contain m integers, A and B, respectively.
	
	Output Format
	
	Output a single integer, your total happiness.
*/

#include<stdio.h>

int countHappiness(int arr[], int n, int m, int A[], int B[]) {
  int happiness = 0, i, j;

  for (i = 0; i < n; i++) {
    for (j = 0; j < m; j++) {

      if (A[j] == arr[i]) {
        happiness += 1;
        break;
      }

      if (B[j] == arr[i]) {
        happiness -= 1;
        break;
      }
    }
  }
  return happiness;
}

int main() {
  int i, n, m, arr[100000], A[100000], B[100000], totalHappy;

  printf("Enter the value of n and m: ");
  scanf("%d%d", & n, & m);

  printf("Enter the elements of array: ");
  for (i = 0; i < n; i++)
    scanf("%d", & arr[i]);

  printf("Enter the elements of set A: ");
  for (i = 0; i < m; i++)
    scanf("%d", & A[i]);

  printf("Enter the elements of set B: ");
  for (i = 0; i < m; i++)
    scanf("%d", & B[i]);

  totalHappy = countHappiness(arr, n, m, A, B);
  printf("Total happiness= %d", totalHappy);

  return 0;
}

/*
	Sample input/output
	Enter the value of n and m: 3 2
	Enter the elements of array: 1 5 3
	Enter the elements of set A: 3 1
	Enter the elements of set B: 5 7
	Total happiness= 1
	
	Time Complexity= O(n^2) 
	Space Complexity= O(1)
*/
```
Also add link of the problem after the problem description.

**Comment by imPGupta** [comment]
@atarax665 Code is updated

**Review by atarax665 — APPROVED** [review]
LGTM :)

**Review by vatsalkesarwani12 — APPROVED** [review]
👍🏻

**Comment by vatsalkesarwani12** [comment]
remove conflict

**Comment by imPGupta** [comment]
Conflicts are resolved.

**Pull request merged**
