### PR TITLE
Array wave

### PR DESCRIPTION
**Pull request by shivangi-pandey**
Hello, I have  contributed  array_wave.cpp code in C++ others folder.  This is my first open source contribution. 
Thankyou for giving this opportunity. 
Regards
Please review this for me. 

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

### Description

(Write your answer here.)

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

### CODE REVIEW

**Comment by gat786** [comment]
You first must create an issue and then when it is assigned to you then you must create a PR. Without an Issue we cannot move forward with merging this PR.

**Comment by shivangi-pandey** [comment]
But the issue already exist with the name wave array

I had created that before working
Please  check

**Comment by shivangi-pandey** [comment]
please check now I have made a new issue with same name .

**Review by ankitaggarwal23 — COMMENTED** [review]
@shivangi-pandey We don't accept PRs without any corresponding Issue. It is difficult for us to find your issue in tons of issues available. We can't review and merged incomplete PR's. 

Capture

**Comment by shivangi-pandey** [comment]
Leave that issue

Can you please review these two for me

I have mentioned the issue numbers a s well in their comment section.


https://github.com/TesseractCoding/NeoAlgo/pull/4492

https://github.com/TesseractCoding/NeoAlgo/pull/4486




>

**Pull request closed without merging**
