### PR TITLE
Add left most non-repeating char TesseractCoding#868

### PR DESCRIPTION
**Pull request by Anshoo-Rajput**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes.

### Description

C program solution for finding left most non-repeating character in string. 

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

issue: #868

### CODE REVIEW

**Comment by Anshoo-Rajput** [comment]
@plazzy99 @siddharth25pandey @Kajol-Kumari @iamrajiv please review this.

**Review by iamrajiv — APPROVED** [review]

**Review by atarax665 — APPROVED** [review]
LGTM :)

**Review by vatsalkesarwani12 — APPROVED** [review]
👍🏻

**Comment by iamrajiv** [comment]
@all-contributors please add @rajanshoo25 for code

**Pull request merged**
