### PR TITLE
Matrix addition in javascript

### PR DESCRIPTION
**Pull request by aaadddiii**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

yes

### Description

issue #5437 

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

issue #5437

### CODE REVIEW

**Comment by aaadddiii** [comment]
@gat786  @ankitaggarwal23  @HarshCasper  please review my pr

**Comment by rohanbabbar04** [comment]
@aaadddiii Go to Deepsource: Javascript and correct your code

**Comment by aaadddiii** [comment]
@rohanbabbar04  I have made the changes can you please review and merge my pr

**Comment by rohanbabbar04** [comment]
Do review @bhav09 @gat786 @HarshCasper

**Review by rohanbabbar04 — APPROVED** [review]

**Review by ankitaggarwal23 — APPROVED** [review]

**Pull request merged**
