### PR TITLE
Added Single occurring element in an array by bitwise operation

### LINKED ISSUE #3815: Single occurring element in an array by bitwise operation
## 🚀 Feature

(A clear and concise description of what the feature is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

YES.

## Motivation

As a GSSOC'21 participant I would like to contribute to this project.

## Pitch

Given an array of N elements, where each element occurs twice except one.
we can found that element with the help of Bitwise XOR operator.

### PR DESCRIPTION
**Pull request by RaiyanMahin**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

YES.

### Description

Given an array of N elements, where each element occurs twice except one.
we can found that element with the help of Bitwise XOR operator.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

fixed #3815

### CODE REVIEW

**Comment by RaiyanMahin** [comment]
@iamrajiv @ankitaggarwal23  kindly review

**Comment by RaiyanMahin** [comment]
@iamrajiv @ankitaggarwal23 kindly review.

**Review by iamrajiv — APPROVED** [review]

**Comment by RaiyanMahin** [comment]
@iamrajiv  I guess , he is  busy. whom should I request  for review?

**Review by iamrajiv — APPROVED** [review]

**Comment by RaiyanMahin** [comment]
@iamrajiv  Thanks <3

**Pull request merged**
