### PR TITLE
added prim's algo in cpp issue-3307

### PR DESCRIPTION
**Pull request by kavyasree-123**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

yes

### Description

added prim's algorithm in cpp

### Checklist

- 

- [yes ]  I've read the contribution guidelines.
- [yes ] I've checked the issue list before deciding what to submit.
- [yes] I've edited the `README.md` and link to my code.

### CODE REVIEW

**Comment by kavyasree-123** [comment]
please review my pr and merge prim's algorithm
@bhav09 , @siddharth25pandey @HarshCasper , @ankitaggarwal23

**Comment by kavyasree-123** [comment]
please add label for level for this code

**Comment by ankitaggarwal23** [comment]
@kavyasree-123 We don't accept PRs without any corresponding Issue. It is difficult for us to find your issue in tons of issues available. We can't review and merged incomplete PR's.   

Capture
     
Kindly don't add just a issue number make that to a link

**Comment by kavyasree-123** [comment]
Ok sorry for that I create another pr.

**Comment by kavyasree-123** [comment]
Hey in Mobile it's not visible but I have written once you see in the laptop

**Comment by ankitaggarwal23** [comment]
@kavyasree-123 Kindly open a new PR add the proper details and Link the issue no. in the description properly.
Use # along with issue no. Ex- #3410

**Pull request closed without merging**
