### PR TITLE
Maximum Score

### PR DESCRIPTION
**Pull request by Sakshi1007**
Added code for maximum score in cp.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

It is problem of CP. it is very good problem for a beginner to start with. 

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#4508

### CODE REVIEW

**Comment by Sakshi1007** [comment]
@HarshCasper @ankitaggarwal23

**Review by ankitaggarwal23 — CHANGES_REQUESTED** [review]
Few changes: 

- Add Multi-Line Comments 
- Add a beginner-friendly description at the top
- Use proper code Format 
- Remove extra lines of code and spaces
- Add sample I/O at the end of the Code
- Add Time and Space Complexity at the end of the Code   
- Add new line at the EOF
- Remove one tab space

**Comment by Sakshi1007** [comment]
I have added sample input as well as time complexity. And this is the format told by ur project admin which I am following so can you explain a bit what do you mean by proper format, I am not getting it.

**Comment by ankitaggarwal23** [comment]
> I have added sample input as well as time complexity. And this is the format told by ur project admin which I am following so can you explain a bit what do you mean by proper format, I am not getting it.

Code formatting means Align your code properly.
Add the TC and SC you added is not the time and space complexity. You have written what your compiler has shown.

**Comment by Sakshi1007** [comment]
@ankitaggarwal23 review PR

**Comment by Sakshi1007** [comment]
@ankitaggarwal23  and @HarshCasper  plz review PR

**Comment by Sakshi1007** [comment]
@ankitaggarwal23  plz  review

**Review by ankitaggarwal23 — CHANGES_REQUESTED** [review]
- Use proper code Format 
- Remove extra lines of code and spaces
- Add sample I/O at the end of the Code with proper display message how you are reading and writing I/P and O/P
- Add new line at the EOF

**Review by ankitaggarwal23 — COMMENTED** [review]
Are you still working on it.

**Review by ankitaggarwal23 — COMMENTED** [review]
Closing this due to inactivity since last 21 days. Thank you for your valuable time.😊

**Pull request closed without merging**
