### PR TITLE
finding duplicate elements(using XOR)

### PR DESCRIPTION
**Pull request by kanchi12P**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

YES

### Description

add a CPP file

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Issue#3032

### CODE REVIEW

**Review by shraiyanshdugar — CHANGES_REQUESTED** [review]
@kanchi12P  please shift sample input and output, space and time complexity at the end of the code. Also, remove indentation across the code.

**Comment by kanchi12P** [comment]
@shraiyanshdugar @ankitaggarwal23 
 previously i have added a pr but as that contained two cpp files hence the pr was closed by@ankitaggarwal23 
I made this new pr with one cpp file 
but this new pr show 4 commits the two commits are of previous one what to do now 
how to remove previous commits?

**Comment by kanchi12P** [comment]
> @kanchi12P please shift sample input and output, space and time complexity at the end of the code. Also, remove indentation across the code.
so I need to make a new pr???

**Comment by kanchi12P** [comment]
> @kanchi12P please shift sample input and output, space and time complexity at the end of the code. Also, remove indentation across the code.

Done 
Please review 
@shraiyanshdugar 
And why 4 commits are showing the two are of my previous pr which is closed
How to remove them

**Comment by kanchi12P** [comment]
Created new pr #3617
@shraiyanshdugar

**Pull request closed without merging**
