### PR TITLE
Double Factorial in Java

### PR DESCRIPTION
**Pull request by ritvij14**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?
Yes
(Write your answer here.)

### Description
This is code for finding the double factorial of a number in Java. I have used both the Recursive and Iterative approach for this code. The time complexity for both is O(n).
(Write your answer here.)

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
Issue #930 
(Write your answer here.)

### CODE REVIEW

**Comment by ritvij14** [comment]
@iamrajiv @Kajol-Kumari @siddharth25pandey @plazzy99 Please review this.

@iamrajiv I have added both the approaches as you mentioned in the issue. I have also made the code interactive by giving the choice to the user as to what approach do they want to see.

**Review by iamrajiv — CHANGES_REQUESTED** [review]
@ritvij14 Move this program to `math` section. I have formatted the code according to https://google.github.io/styleguide/javaguide.html please update the code like this
```
import java.util.*;

public class DoubleFactorial {

    // Recursive approach
    private static int recursiveDoubleFactorial(int num) {
        // checking for 1 and 0
        if (num == 0 || num == 1) {
            return 1;
        }

        // using recursion
        return num * recursiveDoubleFactorial(num - 2);
    }

    // Iterative approach
    private static int iterDoubleFactorial(int num) {
        int result = 1;
        // using iterations
        for (int i = num; i >= 0; i = i - 2) {

            if (i == 0 || i == 1) {
                return result;
            } else {
                result *= i;
            }
        }

        return result;
    }

    public static void main(String[] args) {

        Scanner sc = new Scanner(System.in);
        System.out.println("Enter the number:");
        int num = sc.nextInt();
        System.out.println("Which approach would you like to use?");
        System.out.println("1. Recursive");
        System.out.println("2. Iterative");
        int ch = sc.nextInt();
        sc.close();

        int result;
        switch (ch) {
        case 1:
            result = recursiveDoubleFactorial(num);
            System.out.println("Double factorial:" + result);
            break;

        case 2:
            result = iterDoubleFactorial(num);
            System.out.println("Double factorial:" + result);
            break;

        default:
            System.out.println("Invalid choice.");
        }
    }
}
/**
 * Sample input/output
 * Enter the number:
 * 5
 * Which approach would you like to use?
 * 1. Recursive
 * 2. Iterative
 * 1
 * Double factorial:15
 *
 * Enter the number:
 * 6
 * Which approach would you like to use?
 * 1. Recursive
 * 2. Iterative
 * 2
 * Double factorial:48
 *
 * Time complexity for both the approaches is O(n)
 */

```

**Review by iamrajiv — CHANGES_REQUESTED** [review]
@ritvij14 Add description about Double factorial at top of the program. Refer to this https://en.wikipedia.org/wiki/Double_factorial.

**Comment by ritvij14** [comment]
@iamrajiv I have done the changes. Please have a look.

**Review by iamrajiv — APPROVED** [review]
@ritvij14 LGTM! Nice Work.

**Review by atarax665 — APPROVED** [review]

**Review by vatsalkesarwani12 — APPROVED** [review]
able to merge

**Pull request merged**
