### PR TITLE
Cpp -> min sum partition (DP+Recursion both separated)

### LINKED ISSUE #5824: git is not able to merge a file named minimum_sum_partition.cpp
git is not able to merge a file named minimum_sum_partition.cpp in `cpp/dp/` folder.

image

The image above represents the fresh copy of master branch of neoalgo repo. I believe all contributors are also facing this same conflict. this anomaly is still present in neoalgo repo

### PR DESCRIPTION
**Pull request by ashuvssut**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

YES

### Description 

I found 2 algorithms for Minimum Sum Partition 
-> first one used DP
-> second one used recursion

Both files had the same name and were placed under the same directory. So git was confused and was not able to merge. I was confused about this too until I found out this fact.

Then I created another file to keep recursive algo in cpp/others and dp algo in cpp/dp

Now that weird merge conflict was resolved. I found out the real problem when I tried to clone again
image

closes #5824

### CODE REVIEW

**Review by ankitaggarwal23 — COMMENTED** [review]
Problem already resolved and present No need to update again

**Comment by ashuvssut** [comment]
@ankitaggarwal23 I still think that my PR has the desirable changes

image

There are two minimum sum partition algorithms
1st - dp ( belongs to `cpp/dp`)
2nd - recursive (which does not belong to `cpp/dp`)<--- I have kept this algo in `cpp/others`

Since my changes has organized the both different algorithms separately you should consider reviewing these changes

**Comment by ankitaggarwal23** [comment]
> @ankitaggarwal23 I still think that my PR has the desirable changes
> 
> image
> 
> There are two minimum sum partition algorithms
> 1st - dp ( belongs to `cpp/dp`)
> 2nd - recursive (which does not belong to `cpp/dp`)<--- I have kept this algo in `cpp/others`
> 
> Since my changes has organized the both different algorithms separately you should consider reviewing these changes

Yes I understood but we did and renaming we are doing

**Comment by ashuvssut** [comment]
> Yes I understood but we did and renaming we are doing

ohk you are renaming from your side instead of directly merging. 
Ok no problem

👍

**Pull request closed without merging**
