### PR TITLE
Adding the birthday reminder 

### PR DESCRIPTION
**Pull request by soumikbaithalu**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes I read the contributing guidelines 

### Description

(Write your answer here.)

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

These issues related to the #3473

### CODE REVIEW

**Comment by ankitaggarwal23** [comment]
@soumik2012 Don't push more than one code file in a single PR.

**Comment by soumikbaithalu** [comment]
> @soumik2012 We can't review this PR.

so i need to resend this PR

**Comment by ankitaggarwal23** [comment]
@soumik2012 We can't review this PR.

**Comment by soumikbaithalu** [comment]
> @soumik2012 We can't review this PR.

I have to resend to the PR

**Comment by ankitaggarwal23** [comment]
> > @soumik2012 We can't review this PR.
> 
> I have to resend to the PR

Yes

**Comment by soumikbaithalu** [comment]
@ankitaggarwal23  please check my issues I updated it

**Pull request closed without merging**
