### PR TITLE
Create cosmic_number.cpp

### PR DESCRIPTION
**Pull request by priyanka001tech**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

yes

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

issue #3065

### CODE REVIEW

**Comment by ankitaggarwal23** [comment]
@priyanka001tech 

Capture

We don't accept PRs without any corresponding Issue. It is difficult for us to find your issue in tons of issues available. We can't review and merged incomplete PR's.  Closing this PR as of now. Open the new PR if you want this to be reviewed and add the proper details.

**Comment by priyanka001tech** [comment]
ok sir,I have editted it.please check it

**Comment by priyanka001tech** [comment]
or i have to do it again??

**Comment by priyanka001tech** [comment]
is it still invalid??

**Pull request closed without merging**
