### PR TITLE
Representation of graph using adjacency list in Java

### PR DESCRIPTION
**Pull request by anumshka**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)
YES

### Description

(Write your answer here.)
Representing graphs using adjacency list
(issue : #5934 )
### Checklist

- [✔] I've read the contribution guidelines.
- [✔] I've checked the issue list before deciding what to submit.
- [✔] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

### CODE REVIEW

**Review by HarshCasper — CHANGES_REQUESTED** [review]
Few changes required: 

- Modularize the comments and content
- Use comments above the line of code not beside it

**Review by ankitaggarwal23 — CHANGES_REQUESTED** [review]
Do the changes mentioned

**Review by ankitaggarwal23 — COMMENTED** [review]
Code plagiarized from [here](https://www.geeksforgeeks.org/graph-and-its-representations/)

**Review by ankitaggarwal23 — COMMENTED** [review]
Capture

**Pull request closed without merging**
