### PR TITLE
Added Inorder Traversal

### PR DESCRIPTION
**Pull request by Gaushikmr**
Please read [how to contribute](CONTRIBUTING.md) first!
# Description
Submission description here

Checklist
* [x] I've checked the issue list __BEFORE__ deciding what to submit
* [x] I've read the contribution guidelines
* [x] I've edited the README.md link to my code

## Don't forget to visit our [website](http://www.tesseractcoding.tech)!

Feel free to add this badge after your submission is accepted!

```
<a href=https://github.com/TesseractCoding/NeoAlgo>
   <img src=https://img.shields.io/badge/NeoAlgo-Contributor-brightgreen>
</a>
```

### CODE REVIEW

**Comment by mar-galho** [comment]
Would you pull the changes in the repo and update your files accordingly? You're using an older version of the files in your branch

**Review by mar-galho — CHANGES_REQUESTED** [review]
Could you upload your code to the right folder?

**Comment by Gaushikmr** [comment]
can u tell which folder under C.

**Comment by Gaushikmr** [comment]
can you explain to me how?

**Comment by anushkrishnav** [comment]
> can you explain to me how?

Hey . I hope you know how to Even your forked Repo with the [Source-Repo](https://github.com/TesseractCoding/NeoAlgo). <br>
No ? .No worries refer this [link](https://medium.com/@anush.venkatakrishna/how-to-even-your-forked-repo-with-the-source-51e17b7e464e?source=friends_link&sk=72a794d6faa797bac119e5832ad7837f)
Once your forked repo is even then check and move  your file to the apt location  and place it there .Edit README.md of that repository . 
You can undo your previous commit and issue a fresh PR .
Use this [link](https://medium.com/@anush.venkatakrishna/how-to-remove-undo-a-commit-from-your-pr-65e2e4e195af?sk=08b796b9b3dc5fbd94ef606618371214) to know how to Undo previous commit

**Review by Gaushikmr — COMMENTED** [review]
i have made the changes can u check

**Review by Gaushikmr — COMMENTED** [review]
I have made the changes requested can u check and verify.

**Comment by mar-galho** [comment]
Please pull/rebase your branch before resubmitting this issue. Your entire branch is outdated. Closing this -  it should be resubmitted.

**Pull request closed without merging**
