### PR TITLE
Unique Number using  Bitmasking in Java

### LINKED ISSUE #6055: Find a unique no. - Bitmasking in Java
## 💥 Proposal

I would like to add the code to find the unique number in the given array where all the elements are present twice except one.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes.

### PR DESCRIPTION
**Pull request by AnshikaAgrawal5501**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes.

### Description

We are given an array in which all the elements are present twice except one element. The program will find out that unique element.
[Link](https://replit.com/@Anshikaagrawal5/UniqueNumber)

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Fixes : #6055

### CODE REVIEW

**Comment by bhav09** [comment]
The code seems good but I would say to mention the replit link. Rest will review the rest. Thanks

**Comment by AnshikaAgrawal5501** [comment]
> The code seems good but I would say to mention the replit link. Rest will review the rest. Thanks

Hey @bhav09, I have mentioned the link in the description. Please check.

**Review by ankitaggarwal23 — CHANGES_REQUESTED** [review]
Header file missing

**Comment by AnshikaAgrawal5501** [comment]
Hey @ankitaggarwal23 ,
I have now included the header file. Please check.
Thanks.

**Review by bhav09 — CHANGES_REQUESTED** [review]
Can you add comments to your code.

**Comment by AnshikaAgrawal5501** [comment]
> Can you add comments to your code.

Hey @bhav09,
I have explained the entire concept in the comments. Please check.

**Pull request merged**
