### PR TITLE
Tarjan's Algo---->JAVA

### PR DESCRIPTION
**Pull request by U-c0de**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

YES

#7249 ----> FIXES

### CODE REVIEW

**Comment by U-c0de** [comment]
@ankitaggarwal23 @HarshCasper @siddharth25pandey @bhav09 
Do check

**Comment by U-c0de** [comment]
@ankitaggarwal23 @HarshCasper @siddharth25pandey @bhav09
Do check

**Review by ankitaggarwal23 — COMMENTED** [review]
Code plagiarized from [here](https://aprendiendoaprogramar.es/blog/tarjans-algorithm-with-implementation-in-java/)

**Comment by ankitaggarwal23** [comment]
We found that you have plagiarized more than 3 times and also you are opening the issue blindly even though code is present that is clearly against the rules and guidelines.

**Pull request closed without merging**
