### PR TITLE
Elements count

### PR DESCRIPTION
**Pull request by narayan2111**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Given an array and the size of a window (k), print the number of distinct elements for every window.
Example:

Input: arr[] = {10, 20, 20, 10, 30, 40, 10}, k = 4
Output: 2 3 4 3
Input: arr[] = {10, 10, 10, 10}, k = 3
Output: 1 1
Input: arr[] = {10, 20, 30, 40}, k = 3
Output: 3 3

### Checklist

- [Y] I've read the contribution guidelines.
- [Y] I've checked the issue list before deciding what to submit.
- [Y] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#1133

### CODE REVIEW

**Comment by narayan2111** [comment]
kindly review this PR @iamrajiv @Kajol-Kumari @SKAUL05

**Review by iamrajiv — APPROVED** [review]

**Comment by narayan2111** [comment]
Kindly review this PR @Kajol-Kumari @SKAUL05

**Review by SKAUL05 — APPROVED** [review]

**Review by Kajol-Kumari — APPROVED** [review]
LGTM :)

**Comment by narayan2111** [comment]
Kindly merge this PR @iamrajiv sir

**Comment by narayan2111** [comment]
kindly add hacktoberfest accepted label on this PR ,this PR is counted towards hacktobefest. @iamrajiv @plazzy99

**Pull request merged**
