### PR TITLE
Kotlin Algorithms

### PR DESCRIPTION
**Pull request by fomalhauting**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Kotlin algorithms for areas of 2D and 3D figures.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Issue Number: #1487

### CODE REVIEW

**Comment by fomalhauting** [comment]
@shraddhavp Can you check this?

**Comment by fomalhauting** [comment]
@iamrajiv Can you review this?

**Review by vatsalkesarwani12 — APPROVED** [review]
👍🏻

**Review by Neilblaze — APPROVED** [review]
LGTM :+1:

**Comment by iamrajiv** [comment]
@all-contributors please add @itsIapetus for code

**Pull request merged**
