### PR TITLE
Added Reverse Link List in C++ AND Interpolation Search In C

### PR DESCRIPTION
**Pull request by yashaswibiyahut**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

**YES**

### Description
**Reverse Link List -**
Reverse Link List in C++ in both Recursive and Iterative approach.
Clone of head pointer so that it can easily take the inputs.
Resolve errors and modify the code.

**Interpolation Search-**
The Interpolation Search is an improvement over Binary Search.
Implemented this algorithm in C language with iterative approach.
**Time Complexity** : If elements are uniformly distributed, then O (log log n)) 
                                   and in worst case it can take upto O(n).
**Auxiliary Space:** O(1)

_Below is the output of this algorithm._

### Checklist

- [x]  I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x]  I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

### CODE REVIEW

**Comment by yashaswibiyahut** [comment]
C__Users_yashaswi Biyahut_Desktop_Github Projects_NeoAlgo_C_search_Interpolation exe 8_18_2020 4_00_06 PM (2)

Output of the above Interpolation code.

**Comment by yashaswibiyahut** [comment]
@Kajol-Kumari @SKAUL05 @Abhijit2505 @plazzy99 @siddharth25pandey
please review my PR .

**Review by vatsalkesarwani12 — COMMENTED** [review]
update readme

**Comment by yashaswibiyahut** [comment]
C__Users_yashaswi Biyahut_Desktop_Github Projects_NeoAlgo_C-Plus-Plus_ds_Reverse_linked_list exe 8_19_2020 12_56_41 PM (2)
Output of Reverse Link List Code.

**Comment by yashaswibiyahut** [comment]
Done
Updated Readme file. @plazzy99

**Comment by siddharth25pandey** [comment]
@yashaswibiyahut Please make separate PR for different issue.
Also write the issue number in PR Template

**Pull request closed without merging**
