### PR TITLE
Added 'Amazon Alexa Reviews Analysis' Project

### PR DESCRIPTION
**Pull request by Manasi2001**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Folder Structure:

Amazon Alexa Reviews Analysis
- Dataset
-- amazon_alexa.csv
- Model
-- Amazon_Alexa_Reviews_Analysis.ipynb
-- AmazonAlexaReviewsAnalysis.pkl
- README.md

### Checklist

- ✅ I've read the contribution guidelines.
- ✅ I've checked the issue list before deciding what to submit.
- ✅ I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

This PR is with reference to issue #6818.

### CODE REVIEW

**Review by ankitaggarwal23 — COMMENTED** [review]
We don't accept PRs such corresponding Issue

**Comment by ankitaggarwal23** [comment]
Don't push more than one code file in a single PR.

**Comment by Manasi2001** [comment]
@ankitaggarwal23 cannot I just add my ipynb file under Python-->ml? People have worked on external datasets like [this](https://github.com/TesseractCoding/NeoAlgo/blob/master/Python/ml/Iris_Classifier_using_Keras.ipynb) one.

**Comment by Manasi2001** [comment]
@ankitaggarwal23 @bhav09 please give me some update on this.

**Pull request closed without merging**
