### PR TITLE
Bitmanipulation C++

### PR DESCRIPTION
**Pull request by JanhaviSoni**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Added algo for clearing the bit set at the given position in C++

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Issue #5311

### CODE REVIEW

**Review by ankitaggarwal23 — COMMENTED** [review]
Don't push more than one code file in a single PR.

**Comment by JanhaviSoni** [comment]
@ankitaggarwal23 I have just pushed 1 program file and before pushing I had pulled the changes into my repo , there was some unstaged file also but it was not mine . I had just pushed the code for clearing the ith bit. And the other issue I created was related to xor not this one . But why had these things changed , I have no idea about it. Should I make another pull request ?

**Comment by ankitaggarwal23** [comment]
Yes

**Comment by JanhaviSoni** [comment]
@ankitaggarwal23 So for another pull request do I have to push on the same branch again or make new branch and make the changes? Please tell me a little bit about it.

**Comment by ankitaggarwal23** [comment]
Do git pull always and then  start your work because every minute someone added their code so to update all the changes made do git pull and I would suggest delete branch and start with new one.

**Pull request closed without merging**
