### PR TITLE
Created ShellSort.java

### PR DESCRIPTION
**Pull request by iamvs-2002**
Added Priority Queue in the Datastructures in Java and Shell Sort in Java.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)
Yes

### Description

(Write your answer here.)

I have added the Shell sort implementation in Java.

### Checklist

- [x ] I've read the contribution guidelines.
- [x ] I've checked the issue list before deciding what to submit.
- [x ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
#1691 
(Write your answer here.)

### CODE REVIEW

**Comment by atarax665** [comment]
Please raise separate PR for ```Shell Sort``` and ```Heap Sort``` algorithms implementation.

**Comment by iamvs-2002** [comment]
I tried to so, but every time it makes the same pull request for every commit I make.

**Comment by iamvs-2002** [comment]
I deleted the Priority Queue and Heap Sort file from this pull request and will make a separate pull request for every new file from now on. Thanks for letting me know.

**Comment by shraddhavp** [comment]
conflicts to be resolved @iamvs-2002

**Comment by iamvs-2002** [comment]
@shraddhavp May I close this pull request and make a new one for the same? I do not know why are the conflicts.

**Comment by iamvs-2002** [comment]
@shraddhavp Ma'am I have created a new pull request for the same issue once again. Hence, just let me know if I should close this one.

**Pull request closed without merging**
