### PR TITLE
Rabinkarp algorithm in c issue-4475

### PR DESCRIPTION
**Pull request by kavyasree-123**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

yes i have

### Description

 RABIN KARP in c issue - 4475
Rabin-Karp is  pattern searching algorithm to find the pattern in a more efficient way

### Checklist

- [ yes] I've read the contribution guidelines.

- [ yes] I've checked the issue list before deciding what to submit.
- [yes] I've edited the `README.md` and link to my code.

## Related Issues or Pull Request
 [#4475](https://github.com/TesseractCoding/NeoAlgo/issues/4475) created pr on this issue please verify

### CODE REVIEW

**Review by ankitaggarwal23 — COMMENTED** [review]
@kavyasree-123 Someone is already working in this issue in C here #4052. Kindly check before opening an issue.

**Comment by kavyasree-123** [comment]
hi this is not duplicate first i created the issue and then the time for it to merge hsas few days left so i thought of creating the issue  as it takes time to merge

**Comment by ankitaggarwal23** [comment]
@kavyasree-123 Before you opened someone already working on it. Add Don't open such issue if you're not working on it.

**Comment by kavyasree-123** [comment]
no issues i  will work on my previous issue itself

**Pull request closed without merging**
