### PR TITLE
Longest Substring Without Repeating Characters in Golang

### PR DESCRIPTION
**Pull request by GajjarMiten**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?
Yes, I have read the Contributing Guidelines on Pull Requests.

### Description

- Added implementation of the program for Longest Substring Without Repeating Characters in Golang 

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

issue #563 for Go language

### CODE REVIEW

**Comment by GajjarMiten** [comment]
Hey @Kajol-Kumari @plazzy99 @SKAUL05 @siddharth25pandey @iamrajiv 
could you please review this pull request?

**Comment by GajjarMiten** [comment]
Hello, Could someone please review this PR?
@iamrajiv @siddharth25pandey @SKAUL05 
@plazzy99 @atarax665

**Comment by GajjarMiten** [comment]
@Abhijit2505 @atarax665 @iamrajiv 
could you review this pr?

**Review by iamrajiv — APPROVED** [review]

**Review by atarax665 — COMMENTED** [review]
Sorry for the delay, resolve the merge conflict ASAP so that I can merge this PR.

**Comment by GajjarMiten** [comment]
> Sorry for the delay, resolve the merge conflict ASAP so that I can merge this PR.
hey @atarax665  I have resolved conflicts

**Comment by GajjarMiten** [comment]
Hey @atarax665 @iamrajiv @SKAUL05 
could you please check this pr?

**Review by iamrajiv — APPROVED** [review]

**Pull request merged**
