### PR TITLE
Extended Euclidean Algorithm in python

### PR DESCRIPTION
**Pull request by atarax665**
ISSUE- #249 
# Description
Added implementation of Extended Euclidean Algorithm to find GCD in python.

Checklist
* [X] I've checked the issue list __BEFORE__ deciding what to submit
* [X] I've read the contribution guidelines
* [X] I've edited the README.md link to my code

## Don't forget to visit our [website](http://www.tesseractcoding.tech)!

Feel free to add this badge after your submission is accepted!

```
<a href=https://github.com/TesseractCoding/NeoAlgo>
   <img src=https://img.shields.io/badge/NeoAlgo-Contributor-brightgreen>
</a>
```

### CODE REVIEW

**Comment by mar-galho** [comment]
Hi! Could you fix the conflict with the README.md file before I can merge this?

**Comment by atarax665** [comment]
I don't know whats wrong with the readme.md file. When I make changes to it shows "Can't merge automatically".

**Comment by anushkrishnav** [comment]
Next time when it happends rebase it and drop unwanted commit statements . All you have to do it add the file ,update the README.md and then push . Issue PR . Good day . I will tc of the readme from my side

**Comment by anushkrishnav** [comment]
> I don't know whats wrong with the readme.md file. When I make changes to it shows "Can't merge automatically".

The problem was that Your forked repo wasnt even with our repo . You can learn how to keep a forked repo even  from [here ](https://medium.com/@anush.venkatakrishna/how-to-even-your-forked-repo-with-the-source-51e17b7e464e)

**Comment by atarax665** [comment]
@anushkrishnav Tysm. I got it now.

**Pull request merged**
