### PR TITLE
Possible Code Recursion

### PR DESCRIPTION
**Pull request by narayan2111**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Given a string s, and assuming that a=1, b=2, c=3, d=4, .... z=26
Python recursive function to print all the possible codes for the strings.

### Checklist

- [Y] I've read the contribution guidelines.
- [Y] I've checked the issue list before deciding what to submit.
- [Y] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#1111

### CODE REVIEW

**Comment by narayan2111** [comment]
kindly review this PR @iamrajiv @Kajol-Kumari @SKAUL05 @plazzy99

**Review by iamrajiv — APPROVED** [review]

**Review by vatsalkesarwani12 — APPROVED** [review]
👍🏻

**Comment by narayan2111** [comment]
Kindly review this PR @SKAUL05

**Review by SKAUL05 — APPROVED** [review]

**Comment by narayan2111** [comment]
kindly add hacktoberfest accepted label on this PR ,this PR is counted towards hacktobefest. @iamrajiv @plazzy99

**Pull request merged**
