### PR TITLE
Unique III in Java

### PR DESCRIPTION
**Pull request by ritvij14**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?
Yes
(Write your answer here.)

### Description
Code to find the Unique number from an array which has all repeated elements, except one.
(Write your answer here.)

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
Issue #988 
(Write your answer here.)

### CODE REVIEW

**Comment by ritvij14** [comment]
@iamrajiv @plazzy99 @siddharth25pandey @Kajol-Kumari please review this.

**Comment by ritvij14** [comment]
@iamrajiv sir, I think there is again some wrong stuff in the wrong place in the Java README file on `master` branch :sweat_smile: . Should I make a separate PR for it this time?

**Review by vatsalkesarwani12 — APPROVED** [review]
LGTM 👍🏻

**Comment by iamrajiv** [comment]
@ritvij14 Yeah `Sorting` section programs are added `Competitive programming` section. Also, `Competitive programming` section is duplicated in Java README. You can make new PR on this also check other languages sections README if these type of problems exist refactor that too.

**Review by iamrajiv — APPROVED** [review]

**Review by atarax665 — APPROVED** [review]

**Pull request merged**
