### PR TITLE
Linear Probing in Hashing using Python

### PR DESCRIPTION
**Pull request by RaveenaBhasin**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Implementation of linear probing in hashing using python

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#6759

### CODE REVIEW

**Comment by RaveenaBhasin** [comment]
I have updated the readme and made PR #6769 for it

**Comment by RaveenaBhasin** [comment]
@atarax665 @HarshCasper I have updated the readme in this branch only. Please review my PR.

**Review by ankitaggarwal23 — CHANGES_REQUESTED** [review]
Few changes: 

- Add Multi-Line Comments 
- Add a beginner-friendly description at the top
- Use proper code Format 
- Remove extra lines of code and spaces
- Add sample I/O at the end of the Code
- Add Time and Space Complexity at the end of the Code   
- Add new line at the EOF
- Add input-output prompts to make the program more interactive.

**Comment by RaveenaBhasin** [comment]
@ankitaggarwal23 I have made the required changes by adding multiline comments, a clear description of linear probing in hashing also I have added i/o sample along with time & space complexities at the end of the program

**Review by HarshCasper — APPROVED** [review]

**Pull request merged**
