### PR TITLE
Depth first search using adjacency list

### PR DESCRIPTION
**Pull request by RhuthuHegde**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

This is the depth-first search problem using an adjacency list and explanation with example.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

### CODE REVIEW

**Review by srimanikantapalakollu — CHANGES_REQUESTED** [review]
Please try to take input Dynamically from the console.

**Comment by RhuthuHegde** [comment]
Sure I will do that

**Comment by atarax665** [comment]
@RhuthuHegde Closing this PR due to inactivity, comment if you are still working on this.

**Comment by RhuthuHegde** [comment]
I am working on it, I will add the changes in a day or so.

**Pull request closed without merging**
