### PR TITLE
Fast Fibonacci Last digit numbers

### PR DESCRIPTION
**Pull request by narayan2111**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

C++ Program to calculate last digit number of fibonacci series

### Checklist

- [Y] I've read the contribution guidelines.
- [Y] I've checked the issue list before deciding what to submit.
- [Y] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#1298

### CODE REVIEW

**Comment by narayan2111** [comment]
kindly review this PR @iamrajiv @plazzy99 @SKAUL05

**Review by SKAUL05 — APPROVED** [review]

**Review by iamrajiv — CHANGES_REQUESTED** [review]
@narayan2111 For the larger value of `n` this code will not work. There is another way to implement this in `O(1)` time. 

Look at the final digit in each Fibonacci number:

Fibonacci number: 0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, ...
Final digit: 0, 1, 1, 2, 3, 5, 8, 3, 1, 4, 5, 9, 4, 3, 7, 0, 7, ...
The series is just 60 numbers long and then it repeats the same sequence, again and again, all the way through the Fibonacci series forever. We say the series of final digits repeats with a cycle length of 60.

The final two digits in the Fibonacci numbers also follow the pattern. After Fibonacci(300) the last two digits repeat the same sequence again and again. The cycle length is 300 this time.

For the last three digits, the cycle length is 1500.
For the last four digits, the cycle length is 15000.
For the last five digits, the cycle length is 150000
and so on ...

So I want you to implement this logic in addition to your current program.

**Comment by narayan2111** [comment]
> @narayan2111 For the larger value of `n` this code will not work. There is another way to implement this in `O(1)` time.
> 
> Look at the final digit in each Fibonacci number:
> 
> Fibonacci number: 0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, ...
> Final digit: 0, 1, 1, 2, 3, 5, 8, 3, 1, 4, 5, 9, 4, 3, 7, 0, 7, ...
> The series is just 60 numbers long and then it repeats the same sequence, again and again, all the way through the Fibonacci series forever. We say the series of final digits repeats with a cycle length of 60.
> 
> The final two digits in the Fibonacci numbers also follow the pattern. After Fibonacci(300) the last two digits repeat the same sequence again and again. The cycle length is 300 this time.
> 
> For the last three digits, the cycle length is 1500.
> For the last four digits, the cycle length is 15000.
> For the last five digits, the cycle length is 150000
> and so on ...
> 
> So I want you to implement this logic in addition to your current program.

It will work for large values of n too, i tested it. Because I'm just taking last digit of the series not whole series @iamrajiv

**Comment by narayan2111** [comment]
Like 𝐹200= 280 571 172 992 510 140 037 611 932 413 038 677 189 525 
and it gives output within less than seconds and output is 5

And also if i give input 327305, which will be so large series and my output come within seconds.

**Comment by iamrajiv** [comment]
@narayan2111 This code will work fine only when `0 ≤ n ≤ 10 ^7` because you have used this `for(int i = 2; i <= n; i++)` so if `n > 10^7` this will give you Time Limit Exceeded (TLE). The reason for this is that generally, a machine can process `10^7` instructions per second approximately. What I have suggested is of `O(1)`  i.e. constant time so in this case, time complexity does not depend on the value of `n`. I would suggest keeping your existing code and in addition to it implement the `O(1)` approach too so that people can get to know about different ways to implement this.

**Comment by narayan2111** [comment]
> @narayan2111 This code will work fine only when `0 ≤ n ≤ 10 ^7` because you have used this `for(int i = 2; i <= n; i++)` so if `n > 10^7` this will give you Time Limit Exceeded (TLE). The reason for this is that generally, a machine can process `10^7` instructions per second approximately. What I have suggested is of `O(1)` i.e. constant time so in this case, time complexity does not depend on the value of `n`. I would suggest keeping your existing code and in addition to it implement the `O(1)` approach too so that people can get to know about different ways to implement this.

So, should i omit my code and write the code of time complexity O(1) or i should Create another issue for that sir @iamrajiv

**Comment by iamrajiv** [comment]
@narayan2111 Add `O(1)` method in this code only with a different function name.

**Comment by narayan2111** [comment]
> @narayan2111 Add `O(1)` method in this code only with a different function name.

Okay sir, i will remove my algorithm and will implement the algorithm you said , i will do it accordingly sir, thank you so much @iamrajiv

**Comment by iamrajiv** [comment]
@narayan2111 Do not remove the existing algorithm in addition to it add `O(1)` method too in the same code.

**Comment by narayan2111** [comment]
> @narayan2111 Do not remove the existing algorithm in addition to it add `O(1)` method too in the same code.

Okay sir, will add both the algorithms, thank you

**Comment by narayan2111** [comment]
> @narayan2111 Do not remove the existing algorithm in addition to it add `O(1)` method too in the same code.


> @narayan2111 Do not remove the existing algorithm in addition to it add `O(1)` method too in the same code.

Added new Algorithm and taken help from geeksforgeeks @iamrajiv

**Review by iamrajiv — APPROVED** [review]

**Review by vatsalkesarwani12 — APPROVED** [review]
👍🏻

**Pull request merged**
