### PR TITLE
Sleep sort description added

### LINKED ISSUE #7142: Sleep sort description wiki
## 📚 Documentation

In this sort, we create different threads for every element within the input array, then each thread sleeps for an amount of the duration which is proportional to the value of corresponding array element.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

### PR DESCRIPTION
**Pull request by Bhumika2409**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

yes

### Description

In this sort, we create different threads for every element within the input array, then each thread sleeps for an amount of the duration which is proportional to the value of the corresponding array element.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Fixes #7142

### CODE REVIEW

**Comment by Bhumika2409** [comment]
@HarshCasper @ankitaggarwal23 @bhav09 @gat786 @anushkrishnav can anyone please review this pr

**Comment by gat786** [comment]
Did you forget to commit the code file?

**Comment by Bhumika2409** [comment]
@gat786 no I have just added the description as a part of documentation in Resources folder

**Review by gat786 — APPROVED** [review]

**Comment by gat786** [comment]
It looks good to me.

**Pull request merged**
