### PR TITLE
Created Counting Sort in Kotlin

### PR DESCRIPTION
**Pull request by iamvs-2002**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?
Yes
(Write your answer here.)

### Description
Implementation of Counting Sort Algo in Kotlin.
(Write your answer here.)

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
#1487 
(Write your answer here.)

### CODE REVIEW

**Review by iamvs-2002 — COMMENTED** [review]
...

**Comment by iamvs-2002** [comment]
Respected maintainers, please help me resolve this issue. Never encountered such an issue ever before. Please help.

**Comment by HarshCasper** [comment]
Hello @iamvs-2002 

You did not need to close this. The DeepSource Configuration has some errors and you can safely ignore it for now.

**Comment by iamvs-2002** [comment]
> Hello @iamvs-2002
> 
> You did not need to close this. The DeepSource Configuration has some errors and you can safely ignore it for now.

Ohh okay.

**Pull request closed without merging**
