### PR TITLE
Depth-First Search in C

### PR DESCRIPTION
**Pull request by muthuannamalai12**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?
Yes
(Write your answer here.)

### Description
Added Graph traversal algorithm of Depth-First Search in C.
(Write your answer here.)

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
#1725 
(Write your answer here.)

### CODE REVIEW

**Comment by muthuannamalai12** [comment]
@srimani-programmer .Kindly review this

**Comment by srimanikantapalakollu** [comment]
@muthuannamalai12 please replace getch() function with getchar() function then only it will work after adding unistd.h library.

**Comment by muthuannamalai12** [comment]
> @muthuannamalai12 please replace getch() function with getchar() function then only it will work after adding unistd.h library.

Ok I will do it

**Comment by muthuannamalai12** [comment]
> @muthuannamalai12 please replace getch() function with getchar() function then only it will work after adding unistd.h library.

I will do the same for bfs also

**Comment by muthuannamalai12** [comment]
I have changed it. Kindly review @srimani-programmer

**Comment by muthuannamalai12** [comment]
@HarshCasper Can you please add DWOC and level label for this issue here on my PR.

**Comment by muthuannamalai12** [comment]
@HarshCasper @atarax665. Can you please add DWOC and level label for this issue here on my PR.

**Comment by muthuannamalai12** [comment]
@HarshCasper @atarax665 @anushkrishnav. Can you please add DWOC and level label for this issue here on my PR.

**Comment by muthuannamalai12** [comment]
@HarshCasper @atarax665 @anushkrishnav . Can you please add DWOC and level label for this issue here on my PR.

**Pull request merged**
