### PR TITLE
Rearrange array in alternating positive & negative item 

### PR DESCRIPTION
**Pull request by soumikbaithalu**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes 

### Description

using the single-pass approach 

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Issue is related #5847

### CODE REVIEW

**Review by atarax665 — CHANGES_REQUESTED** [review]
Can you come up with a better approach?  An approach with better space and time complexity.

**Comment by soumik2012** [comment]
> Can you come up with a better approach? An approach with better space and time complexity.

@atarax665  No sir i can't

**Comment by soumik2012** [comment]
> Can you come up with a better approach? An approach with better space and time complexity.

@aakriti1318 sir, please reply

**Review by ankitaggarwal23 — APPROVED** [review]

**Comment by soumikbaithalu** [comment]
@ankitaggarwal23 but this is level 2 question

**Comment by soumikbaithalu** [comment]
#5849 you also review this one same question @ankitaggarwal23  sir

**Pull request merged**
