### PR TITLE
Wrapping Letters 

### PR DESCRIPTION
**Pull request by ErzaTitania-2001**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

yes

(Write your answer here.)

### Checklist

- [ y] I've read the contribution guidelines.
- [y ] I've checked the issue list before deciding what to submit.
- [y ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Wrapping Letters #1804 as assigned by @shraddhavp

### CODE REVIEW

**Comment by ErzaTitania-2001** [comment]
@iamrajiv.

**Review by iamrajiv — CHANGES_REQUESTED** [review]
@ErzaTitania-2001 Format your code like this

```java
import java.util.*;
class Main {
    public static void main(String args[]) {
        Scanner sc = new Scanner(System.in);

        System.out.println("Enter the target character");
        char ch = sc.nextLine().charAt(0); //target character
        List < Character > arr = new ArrayList < > ();
        System.out.println("Enter the letters");
        String s = sc.nextLine();
        for (int i = 0; i < s.length(); i++)
            arr.add((s.charAt(i)));
        arr.add((ch));
        Collections.sort(arr);
        int ind = arr.indexOf(ch);
        System.out.print("The closest letter : ");
        if (ind == (arr.size() - 1))
            System.out.println((arr.get(0)));
        else
            System.out.println((arr.get(ind + 1)));
    }

}

/*
Sample input and output:
Enter the target character
a
Enter the letters
cdf
The closest letter : c
Enter the target character
z
Enter the letters
abc
The closest letter : a

Time Complexity: O(n)
Space Complexity: O(1)
*/
```

**Comment by ErzaTitania-2001** [comment]
Done @iamrajiv . Which code formatter did you use? 
I used https://www.tutorialspoint.com/online_java_formatter.htm

**Review by iamrajiv — APPROVED** [review]

**Comment by iamrajiv** [comment]
> Done @iamrajiv . Which code formatter did you use?
> I used https://www.tutorialspoint.com/online_java_formatter.htm

@ErzaTitania-2001 I followed [Google Java Style Guide](https://google.github.io/styleguide/javaguide.html). I have installed [Sublime​AStyle​Formatter](https://packagecontrol.io/packages/SublimeAStyleFormatter) which is a package for sublime. After installing Sublime​AStyle​Formatter than you have to set some setting in `SublimeAStyleFormatter.sublime-settings` file and set ` "style": "google"` like this

```
"options_default": {
        // Default bracket style
        // Can be one of "allman", "bsd", "break", "java", "attach", "kr", "k&r",
        // "k/r" "stroustrup", "whitesmith", "banner", "gnu", "linux", "horstmann",
        // "1tbs", "otbs ", "google", "pico", "lisp", "python", "vtk", or null
        // for default.
        "style": "google"
```

This will automatically format your code according to Google Style Guide.

**Pull request merged**
