### PR TITLE
Added Lucky number in CPP

### PR DESCRIPTION
**Pull request by nidh-ish**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Added Lucky number in CPP.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Added for documentation purposes in NeoAlgo-Docs.

### CODE REVIEW

**Review by HarshCasper — APPROVED** [review]

**Review by ankitaggarwal23 — COMMENTED** [review]
Code already present #2852

**Comment by nidh-ish** [comment]
Hey @ankitaggarwal23. The code wasn't merged until two days back. I needed it for documentation purposes in NeoAlgo-Docs. Before writing my own code and creating a PR, I went through the C++ code directory in NeoAlgo. Should I have gone through all the open issues and open PRs to find out if somebody will/has written the code for the same. @HarshCasper You only tell how is it justified?

**Comment by nidh-ish** [comment]
@ankitaggarwal23 FYI, both the codes are different, not just in terms of implementation. There are variants of lucky numbers. The variant of lucky number I used for article writing is different than this one.

**Comment by ankitaggarwal23** [comment]
> @ankitaggarwal23 FYI, both the codes are different, not just in terms of implementation. There are variants of lucky numbers. The variant of lucky number I used for article writing is different than this one.

Don't worry I'm doing audit of all PR's and scores of each participants.

**Pull request merged**
