### PR TITLE
hashtable chaining in c

### LINKED ISSUE #3898: Linear probing and chaining in hashtables in c and c++
## 🚀 Feature

Collision resolution is an  important concept in hashtables linear probing and chaining are 2 collision resolution techniques

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

## Motivation

Collision resolution is an  important concept in hashtables linear probing and chaining are 2 collision resolution techniques

## Pitch

This is an important data structure concept

### PR DESCRIPTION
**Pull request by aaadddiii**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

yes

### Description

fixes #3898 

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

issue #3898

### CODE REVIEW

**Review by HarshCasper — CHANGES_REQUESTED** [review]
Use Multi-Line Comments instead of Single-Line Comments

**Comment by aaadddiii** [comment]
necessary changes made

**Comment by aaadddiii** [comment]
@HarshCasper can you please review my pr

**Review by ankitaggarwal23 — CHANGES_REQUESTED** [review]
Code produces error kindly cross check

**Comment by aaadddiii** [comment]
@ankitaggarwal23   I have made the changes can you please reviewthe pr

**Review by HarshCasper — APPROVED** [review]

**Pull request merged**
