### PR TITLE
Added StrongNumber.py file-#2826

### PR DESCRIPTION
**Pull request by javeed3157**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Given input number is Strong number or not
EX : 1! + 4! + 5! => 1 + 24 + 120 => 145

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#2826

### CODE REVIEW

**Comment by javeed3157** [comment]
@ankitaggarwal23 please review my code

**Comment by javeed3157** [comment]
@ankitaggarwal23 I have some changes please review my code

**Review by ankitaggarwal23 — CHANGES_REQUESTED** [review]
Few changes: 

- Remove extra lines of code and spaces
- Add Time and Space Complexity at the end of the Code

**Comment by ankitaggarwal23** [comment]
@javeed3157 We don't accept PRs without any corresponding Issue.

**Comment by javeed3157** [comment]
@ankitaggarwal23  

> @javeed3157 We don't accept PRs without any corresponding Issue.
# Bhaiya this is my issue link I was assigned issue by you .
# https://github.com/TesseractCoding/NeoAlgo/issues/2826
# Sorry because I forgot to present it in PR documentation message
# Now what should I do @ankitaggarwal23 ?

**Pull request closed without merging**
