### PR TITLE
Finding_a_pair_of_element.c

### PR DESCRIPTION
**Pull request by saimanoharhm**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)
Yes 
### Description

(Write your answer here.)
I  have added code for Finding a pair of element with sum k using hash table in a Unsorted array using c
### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)
Issue #2442

### CODE REVIEW

**Comment by saimanoharhm** [comment]
@gat786 and @HarshCasper pls check my PR and let me know if further changes needed.

**Comment by saimanoharhm** [comment]
@HarshCasper Could you pls check it now.

**Review by HarshCasper — CHANGES_REQUESTED** [review]
Few changes: 

- Use Comments above the Line of Code not beside it
- Remove extra lines of code
- Add some more description at the beginning of the Code
- Format your Code using a clang formatter

**Review by HarshCasper — CHANGES_REQUESTED** [review]
You don't need to put comments on every line. Just use comments where needed

**Review by HarshCasper — APPROVED** [review]

**Pull request merged**
