### PR TITLE
IMPLEMENTED TOWER OF HANOI PROBLEM IN C 

### LINKED ISSUE #3902: TOWER OF HANOI in C (GSSOC'21)
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes !

AIM :: **TOWER OF HANOI in C**

## Motivation

As i didn't found TOWER OF HANOI in C, So i am willing to contribute it...

## Pitch

Hi I am GSSoC'21 participant,
"I am looking to work on the TOWER OF HANOI in C"

I will write the clean and optimized code , by keeping best case time and space complexity in mind and 
with  brief commenting and algorithm.
I will use C language.

### PR DESCRIPTION
**Pull request by ananddasani**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes !

### Description

I have implemented the tower of hanoi problem in C language 
so i request @HarshCasper , @bhav09 , @ankitaggarwal23 to please review my PR :)

### Checklist

- [X] I've read the contribution guidelines.
- [X] I've checked the issue list before deciding what to submit.
- [X] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

No.

Fixes #3902

### CODE REVIEW

**Comment by rohanbabbar04** [comment]
@ananddasani This problem is already present

**Comment by ananddasani** [comment]
> @ananddasani This problem is already present

@rohanbabbar04 where did you find it ?

location ?

**Comment by rohanbabbar04** [comment]
It is in the other section

**Comment by ananddasani** [comment]
> It is in the other section

okay

**Pull request closed without merging**
