### PR TITLE
Selection Sort

### PR DESCRIPTION
**Pull request by achalesh27022003**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

yes

### Description

(Write your answer here.)

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#2075

### CODE REVIEW

**Review by atarax665 — CHANGES_REQUESTED** [review]
Remove all the irrelevant files and instead of adding a new file for Selection Sort in C++ just modify the existing [program](https://github.com/TesseractCoding/NeoAlgo/blob/master/C-Plus-Plus/sort/selection_sort.cpp) with proper comments and sample input/output.

**Comment by achalesh27022003** [comment]
Everything done sir @atarax665 .

**Comment by HarshCasper** [comment]
Push all your commits into a single atomic commit. Let me know if you need any assistance for the same 👍

**Comment by achalesh27022003** [comment]
git checkout master
git merge --squash selectionsort
git commit

Sir I have taken help from stackoverflow..there i get this code
so should I use this to do the required?

**Comment by HarshCasper** [comment]
> git checkout master
> git merge --squash selectionsort
> git commit
> 
> Sir I have taken help from stackoverflow..there i get this code
> so should I use this to do the required?

Refer [this](https://stackoverflow.com/questions/5189560/how-can-i-squash-my-last-x-commits-together-using-git)

**Comment by achalesh27022003** [comment]
SIr I am not able to merge into one don't know why everything tried rebasing, squash etc. Sir pls time is less in DWoC program 
therfore couldn't do it more into it. already dived deep into it but getting more confused. so sir pls merge it due to less time also.

**Comment by HarshCasper** [comment]
> SIr I am not able to merge into one don't know why everything tried rebasing, squash etc. Sir pls time is less in DWoC program
> therfore couldn't do it more into it. already dived deep into it but getting more confused. so sir pls merge it due to less time also.

We cannot merge it as long as the issues pointed out are not addressed. Plagiarizing Code and pushing 20+ Commits for a single Issues does not make the cut.

**Comment by achalesh27022003** [comment]
Okay sir I am opening new PR and closing it. Please check that PR. Thanks.

**Comment by achalesh27022003** [comment]
#2186

**Pull request closed without merging**
