### PR TITLE
Add Doubly Linked List

### PR DESCRIPTION
**Pull request by Naman-1234**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Doubly Linked List

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#508

### CODE REVIEW

**Comment by Naman-1234** [comment]
@siddharth25pandey  Sorry to disturb,But can u tell me how can i resolve this conflict. I searched the whole internet but didn't get anything. Pls help

**Comment by Naman-1234** [comment]
@siddharth25pandey  Sir pls help or tell me any other person who can help me in this case,Because i have tried it on my level and my connections.

**Comment by siddharth25pandey** [comment]
> @siddharth25pandey Sir pls help or tell me any other person who can help me in this case,Because i have tried it on my level and my connections.

@Naman-1234 As it is showing This branch has no conflicts with the base branch. So, no worries

**Review by siddharth25pandey — CHANGES_REQUESTED** [review]
Do the following changes
* Take Dynamic input from user for better user-interface
* Create a function for counting the total number of nodes present at that time.
* Display suitable message after each of successful operations.

**Comment by Naman-1234** [comment]
> Do the following changes
> 
> * Take Dynamic input from user for better user-interface
> * Create a function for counting the total number of nodes present at that time.
> * Display suitable message after each of successful operations.

**Comment by Naman-1234** [comment]
@siddharth25pandey  Surely will do the changes sir,it Sir but can u tell me what's the reason of first error,bcoz i got the message of pr failed.that's why i asked it.

**Comment by siddharth25pandey** [comment]
@Naman-1234 ,  Don't  worry about Merge Conflicts **Labeler** like it does not check merge conflicts but add labels to the PR if the **PR has merge conflicts.**  Therefore,  if Merge Conflicts **Labeler** is failing it doesn't mean the branch has Merge Conflicts error.
Hope you Understand !

**Pull request closed without merging**
