### PR TITLE
Quotient-Remainder Sort C++

### PR DESCRIPTION
**Pull request by DEEPIKA-SUK**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Quotient-Remainder Sorting Algorithm for non-negative numbers in C++.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Issue:  #3358

### CODE REVIEW

**Review by HarshCasper — CHANGES_REQUESTED** [review]
Run your Code against a formatter and reduce the size of few comments

**Comment by DEEPIKA-SUK** [comment]
I have made the changes as you said. Kindly check now.

**Comment by DEEPIKA-SUK** [comment]
@HarshCasper I have made the changes, kindly review it.

**Comment by DEEPIKA-SUK** [comment]
@anushkrishnav @ankitaggarwal23 @Apoorve73 Kindly review my PR , I have also made the desired changes.

**Comment by anushkrishnav** [comment]
Your code has a lot of linting issues use an online linter and fix the issues. Check this [linter out]( https://cpplint.appspot.com/CppLint)

**Comment by DEEPIKA-SUK** [comment]
@HarshCasper @anushkrishnav I have formatted my code, reduced the size of comments and also cleared linting issues. Kindly review and merge my PR.

**Review by HarshCasper — APPROVED** [review]

**Comment by HarshCasper** [comment]
@all-contributors bot please add @DEEPIKA-SUK for code

**Pull request merged**
