### PR TITLE
added the palindromic string code in java.

### LINKED ISSUE #2695: (GSSOC'21)palindromic string
## 💥 Proposal

Hello, I have a code to check whether a string is a palindrome or not, in C++/JAVA. I checked the c++ and java folders and didn't found it. So I want to contribute the same, as a part of GSSOC'21.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

-YES

### PR DESCRIPTION
**Pull request by krishantraj**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?
yes

### Description

Here I have written the code in java for checking whether a string is a palindrome or not with short comments for explanation and sample outputs. (issue assigned as a part of  @GSSOC'21).

### Checklist

- [ Y] I've read the contribution guidelines.
- [Y ] I've checked the issue list before deciding what to submit.
- [Y ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(GSSOC'21)palindromic string #2695
Fixes #2695

### CODE REVIEW

**Review by HarshCasper — CHANGES_REQUESTED** [review]
Few changes: 

- Make Markdown Updates
- Shift all the code logic into some other function. Use main() only for driver code
- Add a beginner-friendly description about your Code

**Comment by krishantraj** [comment]
> Few changes:
> 
> * Make Markdown Updates
> * Shift all the code logic into some other function. Use main() only for driver code
> * Add a beginner-friendly description about your Code

okay, will try edit my code to the nearest of the changes you mentioned. sorry for the inconvenience.

**Comment by krishantraj** [comment]
> > Few changes:
> > 
> > * Make Markdown Updates
> > * Shift all the code logic into some other function. Use main() only for driver code
> > * Add a beginner-friendly description about your Code
> 
> okay, will try edit my code to the nearest of the changes you mentioned. sorry for the inconvenience.

I added the description and made a function for the logic part but didn't know what markdown update is. Can you brief a bit about it?

**Comment by HarshCasper** [comment]
> > > Few changes:
> > > 
> > > * Make Markdown Updates
> > > * Shift all the code logic into some other function. Use main() only for driver code
> > > * Add a beginner-friendly description about your Code
> > 
> > 
> > okay, will try edit my code to the nearest of the changes you mentioned. sorry for the inconvenience.
> 
> I added the description and made a function for the logic part but didn't know what markdown update is. Can you brief a bit about it?

Make the changes on the README

**Comment by krishantraj** [comment]
ok, I did a big mistake, I saw the readme file while updating it and found that there is already a code for verifying a palindromic string, with the name palindrome.java which didn't caught my eyes previously, I'm really sorry for the inconvenience. should I contribute for it in C++ : / . (I'm comfortable in c++ also).

**Comment by HarshCasper** [comment]
> ok, I did a big mistake, I saw the readme file while updating it and found that there is already a code for verifying a palindromic string, with the name palindrome.java which didn't caught my eyes previously, I'm really sorry for the inconvenience. should I contribute for it in C++ : / . (I'm comfortable in c++ also).

Sure. First check if it exists or not

**Pull request closed without merging**
