### PR TITLE
feat: Added Bucket Sort in Go

### LINKED ISSUE #2110: Bucket Sort in C++
I would like to add Bucket Sort in C++ without using Insertion Sort as a part of DWOC. @shraddhavp @anushkrishnav Could you assign me this issue?

### PR DESCRIPTION
**Pull request by m-code12**
Fixes: #2110 

Added Bucket Sort in Go

### CODE REVIEW

**Comment by m-code12** [comment]
@atarax665 @HarshCasper Please review this pr.

**Review by HarshCasper — COMMENTED** [review]
Code plagiarized from [here](https://gostudent.github.io/Letsgo/implementation-of-bucket-sort-in-GO)

**Comment by HarshCasper** [comment]
@m-code12 

Please open another PR if you plan to work on it.

**Comment by m-code12** [comment]
> @m-code12
> 
> Please open another PR if you plan to work on it.

Yeah I'll raise another PR.

**Pull request closed without merging**
