### PR TITLE
Level Orde Traversal in java

### PR DESCRIPTION
**Pull request by Vrindagupta6828**
Please read [how to contribute](CONTRIBUTING.md) first!
# Description
Submission description here

Checklist
* [ ] I've checked the issue list __BEFORE__ deciding what to submit
* [ ] I've read the contribution guidelines
* [ ] I've edited the README.md link to my code

## Don't forget to visit our [website](http://www.tesseractcoding.tech)!

Feel free to add this badge after your submission is accepted!

```
<a href=https://github.com/TesseractCoding/NeoAlgo>
   <img src=https://img.shields.io/badge/NeoAlgo-Contributor-brightgreen>
</a>
```

### CODE REVIEW

**Comment by Vrindagupta6828** [comment]
I have also updated the README please merge my request.

**Review by mar-galho — APPROVED** [review]
Great! If you could just solve the conflicts in the README.md file, that would be great!

**Comment by Vrindagupta6828** [comment]
How to resolve could you please assist me?

**Comment by mar-galho** [comment]
You should pull/rebase your fork, then edit your file before pushing it to your branch version and then merging the changes here...but perhaps it is faster if I do it here haha :D so don't worry

**Review by mar-galho — APPROVED** [review]

**Comment by Vrindagupta6828** [comment]
Thanks..

**Pull request merged**
