### PR TITLE
Swap Two Nibbles in C++

### PR DESCRIPTION
**Pull request by mahimagoyalx**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Code for Swap Two Nibbles in C++

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Issue #980

### CODE REVIEW

**Comment by mahimagoyalx** [comment]
@iamrajiv @Abhijit2505 @HarshCasper Kindly review.

**Review by iamrajiv — APPROVED** [review]

**Comment by mahimagoyalx** [comment]
@Kajol-Kumari @plazzy99 Kindly review.

**Review by atarax665 — APPROVED** [review]
LGTM.

**Review by Kajol-Kumari — APPROVED** [review]
LGTM :+1:

**Comment by mahimagoyalx** [comment]
@iamrajiv Kindly merge this PR as it has got 3 approvals.

**Pull request merged**
