### PR TITLE
Fractional knapsack using Greedy in c

### PR DESCRIPTION
**Pull request by vilsijain**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes
### Description
Fractional Knapsack using Greedy Approach in C

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
Issues- https://github.com/TesseractCoding/NeoAlgo/issues/2138

Pull Requests-https://github.com/TesseractCoding/NeoAlgo/pull/2160

### CODE REVIEW

**Comment by HarshCasper** [comment]
The entire code including the comments are copied from [here](https://www.geeksforgeeks.org/fractional-knapsack-problem/) 

@atarax665 Maybe you would like to review this once, before I close this PR

**Comment by vilsi12** [comment]
Sir i have done for c not for c++ and not copied from gfg c++ done earlier
but niw it is deleted csn i check it again if not deleted for c++

**Comment by vilsijain** [comment]
> The entire code including the comments are copied from [here](https://www.geeksforgeeks.org/fractional-knapsack-problem/)
> 
> @atarax665 Maybe you would like to review this once, before I close this PR

Sorry sir it was code of c++ which i forget to remove i have deleted that 
I will be putting my own code of C

**Comment by vilsijain** [comment]
Yes i have put that of c and uploaded the file which i have made and run

**Review by HarshCasper — CHANGES_REQUESTED** [review]
The Code seems to be plagiarized from [here](https://www.chegg.com/homework-help/questions-and-answers/knapsack-problem-file-knapsackdata1txt-knapsackdata2txt-sample-input-files-following-knaps-q36328016) 

Why are we even taking the input from text files? Please don't push such bad PRs

**Comment by vilsijain** [comment]
sorry sir first check the code i not have count in chegga you can't open answer just check your link no problem first check

**Comment by atarax665** [comment]
> sorry sir first check the code i not have count in chegga you can't open answer just check your link no problem first check

I went through your code and it seriously looks plagiarized. There are several things that one can point out to prove that this is not an original work of yours. Please take your time to understand the concept behind the algorithm and try to implement it yourself. We are in no hurry.

**Pull request closed without merging**
