### PR TITLE
Merge Sort with sequential and parallel approach in Golang   

### LINKED ISSUE #469: Implementation of Merge Sort using both ways sequential as well as parallel .
## 🚀 Feature

Sort an array of random integers with merge sort using both sequential as well as parallel implementation. 

Language Supported

C
CPP
Python
Java
C#
JavaScript
GO

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

## Motivation

(Please outline the motivation for the proposal.)

## Pitch

This will help to understand the Merge sort algorithm better in term of both time and space complexity as we have taken both ways sequential as well as parallelism.
Happy Coding :)

### PR DESCRIPTION
**Pull request by GajjarMiten**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?
Yes, I have read the Contributing Guidelines on Pull Requests.

### Description

- Added implementation of Merge Sort with the sequential approach in Golang.
- Added implementation of Merge Sort with the parallel approach in Golang.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Fixes #469  for Go language

### CODE REVIEW

**Comment by GajjarMiten** [comment]
Hey, @Kajol-Kumari @SKAUL05 @iamrajiv @siddharth25pandey 
could you please review this pr?

**Review by iamrajiv — CHANGES_REQUESTED** [review]
@GajjarMiten please fixed `sequantial` typo across all the files. Also, add time and space complexity after sample input-output. Rest LGTM! Hope, you have formatted the code using `gofmt`.

**Comment by GajjarMiten** [comment]
Hey, @iamrajiv.
I have made both changes and used `gofmt`.
kindly check it out :)

**Review by SKAUL05 — CHANGES_REQUESTED** [review]
Algorithm LGTM.
Use meaningful variable names instead of alphabets.

**Review by iamrajiv — CHANGES_REQUESTED** [review]
@GajjarMiten please fix typo for `mergeSortParaller`. Also, implement the things suggested by @SKAUL05

**Comment by GajjarMiten** [comment]
Hey, @SKAUL05 
Do I need to change names of `i,j,k` which have been used in `merge()` function?

**Comment by SKAUL05** [comment]
> Hey, @SKAUL05 
> Do I need to change names of `i,j,k` which have been used in `merge()` function?

Yes

**Comment by GajjarMiten** [comment]
@SKAUL05 @iamrajiv 
I have made changes.
could you please check it?

**Review by iamrajiv — APPROVED** [review]

**Review by SKAUL05 — APPROVED** [review]

**Comment by GajjarMiten** [comment]
hey @siddharth25pandey 
could please review this pr?

**Review by atarax665 — APPROVED** [review]
LGTM :)

**Pull request merged**
