### PR TITLE
Added Inplace rotation of matrix by 90 degrees

### PR DESCRIPTION
**Pull request by Nidhideveloper**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Added Inplace rotation of matrix by 90 degrees

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#5966

### CODE REVIEW

**Review by ankitaggarwal23 — COMMENTED** [review]
Don't think it's is inplace matrix rotation looks like a normal matrix rotation because the concept of inplace matrix rotation is different

**Comment by Nidhideveloper** [comment]
@ankitaggarwal23 Ok sir, I will see to it.

**Review by ankitaggarwal23 — CHANGES_REQUESTED** [review]
why you are adding two lines in readme
solve merge conflict as well

**Comment by Nidhideveloper** [comment]
@ankitaggarwal23 Sir, I have worked accordingly as you requested plz review it!

**Review by ankitaggarwal23 — APPROVED** [review]

**Review by ankitaggarwal23 — CHANGES_REQUESTED** [review]
Why you fixed size to 4? What I suggest it can be of any size of matrix you can rotate think once?

**Comment by Nidhideveloper** [comment]
@ankitaggarwal23 Sir could you please review the PR number #6334 because I was not able to merge the changes made according to your suggestions in this branch and more specifically the file of the code was also deleted. So, made the changes in a new branch. Sir , I request you to please check my pr #6334 which has the same code for the issue #5966, and the changes that you have suggested has also been worked on.

**Comment by Nidhideveloper** [comment]
I wasn't able to merge the changes in this pr! please accept my apology.

**Pull request closed without merging**
