### PR TITLE
Added Round Robin Scheduling Algorithm with Gantt chart

### PR DESCRIPTION
**Pull request by Tanya170620**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

I've added Round Robin Scheduling algorithm with Gantt chart. It also calculates and displays the completion time, turn around time, waiting time, response time, average waiting time and average turn around time. It also displays the ready queue.
I've added comments wherever necessary to make the reader understand the program. I've also added the output at the end in comments.

### Checklist

- [Yes] I've read the contribution guidelines.
- [Yes] I've checked the issue list before deciding what to submit.
- [Yes] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Round Robin Scheduling in C #2592

### CODE REVIEW

**Comment by Tanya170620** [comment]
@gat786 Could you please review my PR and tell me why it is failing the test cases?

**Comment by Tanya170620** [comment]
@gat786 Could you please review my PR and tell me why it is failing the test cases?

**Review by HarshCasper — CHANGES_REQUESTED** [review]
Few changes: 

- Add a new line at the EOF
- Use Multi-Line Comments instead of Single-Line Comments at places where comments run across multiple lines
- Remove the main logic from the main() function. Use main() only for driver code

**Comment by Tanya170620** [comment]
Kindly review the changes. @HarshCasper @bhav09 @gat786 @ankitaggarwal23

**Review by ankitaggarwal23 — APPROVED** [review]

**Review by gat786 — APPROVED** [review]

**Pull request merged**
