### PR TITLE
Finding greatest common divisor(GCD) of two numbers

### PR DESCRIPTION
**Pull request by ashutoshraj01**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)
Yes
### Description

(Write your answer here.)
Finding greatest common divisor(GCD) of two numbers in Javascript.
### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)
Yes

### CODE REVIEW

**Review by ankitaggarwal23 — CHANGES_REQUESTED** [review]
We don't accept PRs without any corresponding Issue. It is difficult for us to find your issue in tons of issues available. We can't review and merged incomplete PR's.  Closing this PR as of now. Open the new PR if you want this to be reviewed and add the proper details.

**Comment by ashutoshraj01** [comment]
Hey Ankit, Need your little help. Can you tell what's missing in the PR so that i can add and raise another PR.

**Comment by ankitaggarwal23** [comment]
> Hey Ankit, Need your little help. Can you tell what's missing in the PR so that i can add and raise another PR.

Capture
 
@ashutoshraj01 Instead of YES you have to write your issue no followed by `#`

**Comment by ashutoshraj01** [comment]
Okay Ankit, Thanks. will take care of it from next time.

**Pull request closed without merging**
