### PR TITLE
Added Palindrome partition

### PR DESCRIPTION
**Pull request by Meghag5**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)
yes

### Description

(Write your answer here.)
Question:- Given a string, a partitioning of the string is a palindrome partitioning if every sub-string of the partition is a palindrome.
We have to find the mnimum cuts which will convert our string into all palindromes.
Input: str = "ababbbabbababa"
Output: 3

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)
#6069

### CODE REVIEW

**Comment by Meghag5** [comment]
@HarshCasper pls review

**Review by ankitaggarwal23 — COMMENTED** [review]
Problem already done by you #4909

**Comment by Meghag5** [comment]
this one is different pls check @ankitaggarwal23

**Comment by Meghag5** [comment]
here we have to find 
We have to find the minimum cuts which will convert our string into all palindromes and it is done using dp
Input: str = "ababbbabbababa"
Output: 3

and in that ques
This problem is solved using backtracking.
It will print all possible Palindromes in the string
Input - abaaba
Output -
a , b , a , a , b , a
a , b , a , aba
a , b , aa , b , a
a , baab , a
aba , a , b , a
aba , aba
abaaba

**Pull request closed without merging**
