### PR TITLE
Rabin-Karp in Python

### LINKED ISSUE #334: Rabin Karp Algorithm
**Algorithm: [Rabin-Karp Algorithm](https://en.wikipedia.org/wiki/Rabin%E2%80%93Karp_algorithm)**

**Language Supported:**
- C++ [@YashThakare ]
- C
- Java [@parjanyaacoder]
- Python [@AdityaJ7]
- C#
- Javascript
- Golang

### PR DESCRIPTION
**Pull request by AdityaJ7**
### Description

Submission description here

Checklist:

- [x] I've checked the issue list before deciding what to submit.
- [x] I've read the contribution guidelines.
- [x] I've edited the `README.md` link to my code.

### References to other Issues or PRs
Fixes #334 -Python part

### CODE REVIEW

**Comment by atarax665** [comment]
@AdityaJ7 Perfect.

**Review by atarax665 — APPROVED** [review]

**Comment by AdityaJ7** [comment]
> @AdityaJ7 Perfect.

Thanks

**Comment by iamrajiv** [comment]
@all-contributors please add @AdityaJ7 for code

**Comment by iamrajiv** [comment]
@all-contributors please add @AdityaJ7 for code

**Pull request merged**
