### PR TITLE
max_sum_subarray_of_size_k

### PR DESCRIPTION
**Pull request by bitaashna**
### Have you read the [Contributing Guidelines on Pull Requests]
Yes,I have read it

### Description
I have implemented the code to find **maximum sum subarray of size k** with the help of sliding window in cpp .

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
#2304

### CODE REVIEW

**Review by HarshCasper — CHANGES_REQUESTED** [review]
Few changes:
- Add new line at the EOF
- Remove redundant comments
- Use multi-line comments wherever possible
- Remove explanation from the sample I/O 
- Keep only one test case 
- Use main() only for driver code. Use a separate function for your main code

**Review by bitaashna — COMMENTED** [review]
I have made the changes. Please check it!

**Review by bitaashna — COMMENTED** [review]
@HarshCasper Please review it

**Review by HarshCasper — CHANGES_REQUESTED** [review]
Format the Code properly with indentation

**Review by bitaashna — COMMENTED** [review]
I have made the changes..Please check it!!

**Review by HarshCasper — CHANGES_REQUESTED** [review]
Format the Code using a formatter

**Review by bitaashna — COMMENTED** [review]
@HarshCasper  done using formatter!

**Comment by bitaashna** [comment]
@HarshCasper Sorry for the inconvenience but I will be creating a fresh PR..as I deleted the forked and forked it again.
So to avoid any issue, I will be opening a new PR

**Pull request closed without merging**
