### PR TITLE
Added playfair cipher decryption

### LINKED ISSUE #5601: decryption for playfair cipher in java
## 🚀 Feature

(A clear and concise description of what the feature is.)
decryption for playfair cipher in java
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

(Write your answer here.)

## Motivation

(Please outline the motivation for the proposal.)

## Pitch

(Please explain why this feature should be implemented and how it would be used.)

### PR DESCRIPTION
**Pull request by nagasrihith608**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?
yes
(Write your answer here.)

### Description
Added Playfair cipher decryption
(Write your answer here.)

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
Fixed #5601  this is a follow-up issue in neo algo docs
(Write your answer here.)

### CODE REVIEW

**Comment by nagasrihith608** [comment]
@HarshCasper please review this pr.

**Review by ankitaggarwal23 — COMMENTED** [review]
#4514 problem already present

**Comment by nagasrihith608** [comment]
> #4514 problem already present

@ankitaggarwal23 this is decryption not encryption

**Comment by nagasrihith608** [comment]
As harsh asked for decryption part also in the neo Algo docs I had to do it with the same implementation, please revisit this or its not duplicate.

**Pull request closed without merging**
