### PR TITLE
Check prime with and without recursion in java

### PR DESCRIPTION
**Pull request by ErzaTitania-2001**
Solving the question Prime Number with iteration as well as recursion #1372

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Checklist

- [ y] I've read the contribution guidelines.
- [ y] I've checked the issue list before deciding what to submit.
- [ y] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Prime Number #1372

### CODE REVIEW

**Review by iamrajiv — CHANGES_REQUESTED** [review]
@ErzaTitania-2001 Add sample input-output, space and time complexity. Also, update the README file.

**Comment by ErzaTitania-2001** [comment]
Okay!
I'm working on it.
I need to add sample input and output cases as the comment lines in he
program?

**Comment by iamrajiv** [comment]
@ErzaTitania-2001 Yes. Also, you can refer to other programs for reference.

**Review by iamrajiv — CHANGES_REQUESTED** [review]
@ErzaTitania-2001 Add your program links in `Java/README.md`.

**Comment by ErzaTitania-2001** [comment]
Oh. I'm so sorry. I'll remove my commit for Contributors.md right now.

**Comment by ErzaTitania-2001** [comment]
Review the changes and if required do suggest more! @iamrajiv @atarax665

**Review by iamrajiv — APPROVED** [review]

**Comment by iamrajiv** [comment]
@all-contributors please add @ErzaTitania-2001 for code

**Pull request merged**
