### PR TITLE
Breadth First Search Algorithm (AI)

### PR DESCRIPTION
**Pull request by iamvs-2002**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)
Yes
### Description

(Write your answer here.)
Created a .md file containing the explanation of the Breadth-First Search Algo and a file containing the algorithm.
### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
#1693 
(Write your answer here.)

### CODE REVIEW

**Comment by atarax665** [comment]
@HarshCasper Take a look at this. I guess we should assign contributors to work on the wikipages now.

**Comment by iamvs-2002** [comment]
> @HarshCasper Take a look at this. I guess we should assign contributors to work on the wikipages now.

Sir that's not from a wiki page or any such resource. The explanation/concept of the algorithm has been written by me, and I have been learning AI algorithms for a while now. Didn't add the real implementation, because I haven't studied it yet.
Kindly look into it. 
And as for the algorithm, it's the general algorithm.

**Comment by atarax665** [comment]
> > @HarshCasper Take a look at this. I guess we should assign contributors to work on the wikipages now.
> 
> Sir that's not from a wiki page or any such resource. The explanation/concept of the algorithm has been written by me, and I have been learning AI algorithms for a while now. Didn't add the real implementation, because I haven't studied it yet.
> Kindly look into it.
> And as for the algorithm, it's the general algorithm.

I acknowledge that the contributed pseudo codes are your original work, I am just seeking validation from him as we were planning to have dedicated wiki page to document all the algorithms and programs contributed. Personally I don't think that its a nice idea to put the pseudo code and documentation in a folder along with codes.

**Comment by iamvs-2002** [comment]
> > > @HarshCasper Take a look at this. I guess we should assign contributors to work on the wikipages now.
> > 
> > 
> > Sir that's not from a wiki page or any such resource. The explanation/concept of the algorithm has been written by me, and I have been learning AI algorithms for a while now. Didn't add the real implementation, because I haven't studied it yet.
> > Kindly look into it.
> > And as for the algorithm, it's the general algorithm.
> 
> I acknowledge that the contributed pseudo codes are your original work, I am just seeking validation from him as we were planning to have dedicated wiki page to document all the algorithms and programs contributed. Personally I don't think that its a nice idea to put the pseudo code and documentation in a folder along with codes.

Oh. I get it. I am sorry, I misunderstood.😅
I am learning the implementation part and will be soon adding once I am confident with the theory of the algorithms.
Also, consider me in as a contributor for any kind of tech documentations needed.

**Comment by HarshCasper** [comment]
We don't need to add it now. 

I would have considered it, if it was a detailed doc, but here it just a step-wise instruction. We have a `resources` directory now. Please raise PRs over there if you would like to work on docs and developing resources. 

 I am closing it now. If you like to discuss about more of this, drop me a message on Slack/Discord.

**Comment by iamvs-2002** [comment]
Okay sir, I got it.

**Pull request closed without merging**
