### PR TITLE
Dynamic Huffman Algorithm Added

### PR DESCRIPTION
**Pull request by hgoyal254**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Added DynamicHuffman.cpp in other folder.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#2272

### CODE REVIEW

**Review by HarshCasper — CHANGES_REQUESTED** [review]
Few changes required: 

- Add proper comments for every function and module
- Add sample I/O at the end of the Code
- Add the Code Complexity at the end of the Code
- Format and indent the Code properly

**Comment by hgoyal254** [comment]
Added proper comments for every function and module
Added sample I/O at the end of the Code
Added the Code Complexity at the end of the Code
Format and indent the Code properly

**Comment by hgoyal254** [comment]
Added RSA Algorithm in cryptography C-Plus-Plus folder.
Related Issues or Pull Requests
#2339

**Comment by HarshCasper** [comment]
You should not have pushed the second code file in the same PR. Break down your PR into two separate PRs and it would be reviewed then.

**Pull request closed without merging**
