### PR TITLE
Rotation Count in Array

### PR DESCRIPTION
**Pull request by U-c0de**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(YES)

### Description

In an given sorted array we will have to find the number of count of rotation after which we have got this array. Here, we take into observation the element I which is greater than the element i+1.after we get this element we calculate the number of rotation that might have occurred .

### Checklist

- [ YES] I've read the contribution guidelines.
- [ YES] I've checked the issue list before deciding what to submit.
- [ YES] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
#6814

### CODE REVIEW

**Comment by U-c0de** [comment]
Please Check PR @ankitaggarwal23 @HarshCasper

**Comment by U-c0de** [comment]
Please Check PR @ankitaggarwal23 @HarshCasper

**Comment by U-c0de** [comment]
Please Check the PR @ankitaggarwal23 @HarshCasper

**Comment by U-c0de** [comment]
Please Check the PR @ankitaggarwal23 @HarshCasper

**Comment by U-c0de** [comment]
Please Check the PR @ankitaggarwal23 @HarshCasper

**Comment by U-c0de** [comment]
@atarax665 @ankitaggarwal23  Please Check

**Comment by U-c0de** [comment]
@atarax665 @ankitaggarwal23 Please Check

**Comment by U-c0de** [comment]
Do check @HarshCasper @atarax665 @ankitaggarwal23

**Review by ankitaggarwal23 — COMMENTED** [review]
Code plagiarized from [here](https://www.geeksforgeeks.org/find-rotation-count-rotated-sorted-array/)

**Comment by ankitaggarwal23** [comment]
Kindly Don't Spam in the PR for review.

**Pull request closed without merging**
