### PR TITLE
countingSort.c submission for DWOC

### PR DESCRIPTION
**Pull request by japneetkaurbhatia**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Implemented countingSort Program in C Language
(Submission for DWOC)

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Counting Sort #1776

### CODE REVIEW

**Review by srimanikantapalakollu — CHANGES_REQUESTED** [review]
Please format the code properly in a single format.

**Comment by japneetkaurbhatia** [comment]
Hey @srimani-programmer 
Do I need to remove everything except code ?

**Comment by shraddhavp** [comment]
@japneetbhatia  format the code and then it is good to merge

**Comment by japneetkaurbhatia** [comment]
Changes done

**Comment by shraddhavp** [comment]
@japneetbhatia  please add the time and space complexity at the end of the code with sample output

**Comment by japneetkaurbhatia** [comment]
Done @shraddhavp

**Review by vatsalkesarwani12 — APPROVED** [review]

**Pull request merged**
