### PR TITLE
Check for Subsequence in Python

### PR DESCRIPTION
**Pull request by yashaswibiyahut**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

**YES**

### Description

**Issue no: #993**
Check for subsequence in Python.
Time Complexity : O(n)

_Below is the Output of this code._

### Checklist

- [x]  I've read the contribution guidelines.
- [x]  I've checked the issue list before deciding what to submit.
- [x]  I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

### CODE REVIEW

**Comment by yashaswibiyahut** [comment]
WhatsApp Image 2020-09-15 at 4 39 25 PM
Output of this code.

**Comment by yashaswibiyahut** [comment]
kindly review this PR @Kajol-Kumari @SKAUL05 @siddharth25pandey @iamrajiv @HarshCasper

**Review by iamrajiv — CHANGES_REQUESTED** [review]
@yashaswibiyahut Format the code according to PEP 8 rules. You can refer to http://pep8online.com/. Also, a lot of changes are done in README just update the link of `sebsequence_check.py`.

**Comment by vatsalkesarwani12** [comment]
resolve merge conflict

**Pull request closed without merging**
