### PR TITLE
Total subtrees with total nodes sum equal to x in C++

### PR DESCRIPTION
**Pull request by gayatri517**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Code added in cp folder

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#6921

### CODE REVIEW

**Comment by gayatri517** [comment]
@ankitaggarwal23 @bhav09 @siddharth25pandey please review my PR

**Review by bhav09 — CHANGES_REQUESTED** [review]
The purpose of the code is good but it is not commented, please comment it. And make sure the comments are above the lines of code and not alongside.

**Comment by gayatri517** [comment]
@bhav09 I have added the comments, Kindly review it.

**Review by siddharth25pandey — CHANGES_REQUESTED** [review]
@gayatri517 Resolve the merge conflicts

**Comment by gayatri517** [comment]
@siddharth25pandey i have resolved the merge conflicts

**Review by siddharth25pandey — APPROVED** [review]
@gayatri517 LGTM 💯 Able to merge

**Pull request merged**
