### PR TITLE
Finding number of digits in an integer(TesseractCoding#406)

### PR DESCRIPTION
**Pull request by imPGupta**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

This program will helps you to count number of digits in an integer in O(1) Time Complexity.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

### CODE REVIEW

**Comment by atarax665** [comment]
@imPGupta Its always better to use underscore ('_') instead of spaces while naming a file. Although I have made required changes to the file name and README.md.

**Comment by imPGupta** [comment]
Sure, I will take care of this next time.

**Review by siddharth25pandey — APPROVED** [review]
@imPGupta Looks fine to me
Able to merge
Thanks!

**Comment by iamrajiv** [comment]
@imPGupta please resolve merge conflicts

**Comment by imPGupta** [comment]
@iamrajiv These merge conflicts are not from my side. Someone deleted the README.md file from the master branch.
Please create a new one.

**Comment by imPGupta** [comment]
@atarax665 @iamrajiv Please resolve the issue and merge by by PR.

**Comment by atarax665** [comment]
I have updated the README.md file now. This PR will get merged soon.

**Review by atarax665 — APPROVED** [review]
LGTM :+1:

**Review by iamrajiv — APPROVED** [review]

**Review by vatsalkesarwani12 — APPROVED** [review]

**Pull request merged**
