### PR TITLE
Trading Algorithm

### PR DESCRIPTION
**Pull request by niyatitotala**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes, I have gone through the document. 

### Description
You have been given an array depicting the prices of each day. 
The goal is to maximize profits. One is allowed to buy and sell multiple times.
### Checklist

- [.] I've read the contribution guidelines.
- [.] I've checked the issue list before deciding what to submit.
- [.] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
Issue #3414

### CODE REVIEW

**Review by HarshCasper — CHANGES_REQUESTED** [review]
Don't use templates in such codes.

**Comment by ankitaggarwal23** [comment]
@niyatitotala Fill the details properly before creating a PR.
Capture

**Comment by niyatitotala** [comment]
> @niyatitotala Fill the details properly before creating a PR.
> Capture

Please check now. Do I have to change code as well because of the template issue?

**Review by ankitaggarwal23 — CHANGES_REQUESTED** [review]
Few changes: 

- Add Multi-Line Comments 
- Add a beginner-friendly description at the top
- Don't use CP templates in such codes.
- Use proper code Format 
- Remove extra lines of code and spaces
- Add sample I/O at the end of the Code
- Add Time and Space Complexity at the end of the Code   
- Add new line at the EOF

**Comment by atarax665** [comment]
@niyatitotala Are you still working on these?

**Comment by niyatitotala** [comment]
> @niyatitotala Are you still working on these?

I've completed from my end according to the requests and changes suggested. It just remains to be merged.

**Review by ankitaggarwal23 — COMMENTED** [review]
> > @niyatitotala Are you still working on these?
> 
> I've completed from my end according to the requests and changes suggested. It just remains to be merged.

Where is the updated file?

**Comment by niyatitotala** [comment]
> > > @niyatitotala Are you still working on these?
> > 
> > 
> > I've completed from my end according to the requests and changes suggested. It just remains to be merged.
> 
> Where is the updated file?

I had committed it, but there seems to be some inconsistency.

**Review by ankitaggarwal23 — CHANGES_REQUESTED** [review]
Don't Use CP templates and tricks.

Few changes: 

- Add Multi-Line Comments 
- Add a beginner-friendly description at the top
- Use proper code Format 
- Remove extra lines of code and spaces
- Add sample I/O at the end of the Code
- Add Time and Space Complexity at the end of the Code   
- Add new line at the EOF

**Review by ankitaggarwal23 — COMMENTED** [review]
Closing this due to inactivity

**Pull request closed without merging**
