### PR TITLE
Added Bubble sort Program

### PR DESCRIPTION
**Pull request by Gaushikmr**
### All Submissions:

__PLEASE DO NOT CREATE EXTRA FOLDERS WITHIN THE EXISTING ONES!__

* [ ] Have you followed the guidelines in our Contributing document?
* [ ] Have you checked the issues to see if your request isn't assigned to someone else?
* [ ] Have you checked to ensure there aren't other open [Pull Requests](../../../pulls) for the same update/change?
* [ ] If your submission is to improve an existing code, have you created an issue to specify that?

### New Code Submissions:

1. [ ] Does your code work locally?
2. [ ] Have you cleaned your code for better readability? (no extra unnecessary lines, etc.)
3. [ ] Have you updated the README.md file to add the link to your code?

### CODE REVIEW

**Comment by mar-galho** [comment]
Hi! 

Have you checked the items on the list?

**Comment by mar-galho** [comment]
Closing, it corresponds to an existing algorithm.

**Comment by gaushikmr** [comment]
Can u suggest me any Algorithm.

**Comment by mar-galho** [comment]
Sure! Why don't you check our [issues page](https://github.com/TesseractCoding/NeoAlgo/issues)? There are some algos to be done there :)

Thanks for your efforts to contribute :D

**Pull request closed without merging**
