### PR TITLE
Intersection Point of Linked List in Java

### PR DESCRIPTION
**Pull request by Jassi10000-zz**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

### Description

(Write your answer here.)

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

### CODE REVIEW

**Comment by Jassi10000-zz** [comment]
Successfully added the PR

**Review by srimanikantapalakollu — CHANGES_REQUESTED** [review]
Code looks clean But please add comments that could easily understand by everyone.

**Comment by Jassi10000-zz** [comment]
Ok now should I send one more PR , or delete this and then send a new?

**Comment by atarax665** [comment]
> Ok now should I send one more PR , or delete this and then send a new?

You can make changes in this PR itself.

**Pull request closed without merging**
