### PR TITLE
added delete linkedlist function

### PR DESCRIPTION
**Pull request by shraddhavp**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

yes

### Description

Added the function to delete linked list node

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#1060

### CODE REVIEW

**Comment by shraddhavp** [comment]
@iamrajiv  @Kajol-Kumari  and @HarshCasper  please check the PR and please  let me know if any changes

**Review by iamrajiv — CHANGES_REQUESTED** [review]
@shraddhavp Add program with proper input-output and implement this function in `main()` function . Also, add time and space complexity.

**Comment by shraddhavp** [comment]
@iamrajiv  and @Kajol-Kumari  added the code as per changes told please check ASAP!!

**Review by iamrajiv — APPROVED** [review]

**Review by Kajol-Kumari — APPROVED** [review]
LGTM :+1:

**Comment by shraddhavp** [comment]
@plazzy99  please check the code sir and let me know if any changes ASAP

**Pull request merged**
