### PR TITLE
READ.me Updated

### PR DESCRIPTION
**Pull request by bagladivyang03**
Please read [how to contribute](CONTRIBUTING.md) first!
# Description
Submission description here

Checklist
* [x] I've checked the issue list __BEFORE__ deciding what to submit
* [x] I've read the contribution guidelines
* [x] I've edited the README.md link to my code

## Don't forget to visit our [website](http://www.tesseractcoding.tech)!

Feel free to add this badge after your submission is accepted!

```
<a href=https://github.com/TesseractCoding/NeoAlgo>
   <img src=https://img.shields.io/badge/NeoAlgo-Contributor-brightgreen>
</a>
```

### CODE REVIEW

**Review by mar-galho — CHANGES_REQUESTED** [review]
I think you're missing a file

**Comment by iamrajiv** [comment]
@bagladivyang03 I think there is no change in the file.

**Comment by bagladivyang03** [comment]
Problem is solved na 
U have merged na?

**Comment by iamrajiv** [comment]
@bagladivyang03 Earlier this PR was having only empty single line commit and rest things are already added so I think this has to be closed now.

**Pull request closed without merging**
