### PR TITLE
Zero one knapsack 1459

### PR DESCRIPTION
**Pull request by Bharati2612**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Added Zero One Knapsack Problem to DP Section

### Checklist

- [Y] I've read the contribution guidelines.
- [Y] I've checked the issue list before deciding what to submit.
- [Y] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Issue Number #1459

### CODE REVIEW

**Comment by Bharati2612** [comment]
@iamrajiv Here is the changes added for the Zeo_One _Knapsack kindly look in to it and merge the request.

**Comment by iamrajiv** [comment]
@Bharati2612 Do not make duplicate PR. Both PR #1554 and #1555 are same.

**Review by iamrajiv — CHANGES_REQUESTED** [review]
@Bharati2612 Update the README.

**Review by iamrajiv — APPROVED** [review]

**Comment by iamrajiv** [comment]
@all-contributors please add @Bharati2612 for code

**Pull request merged**
