### PR TITLE
linear search in java #12

### PR DESCRIPTION
**Pull request by MSufiyanAG**
code for linear search in java  #12 .
And the readme file for binary search merged in java folder has to be shifted to wiki .
Thanks

### CODE REVIEW

**Comment by mar-galho** [comment]
Hi! Thanks. 

I will work on the Wiki file today :)

**Review by mar-galho — CHANGES_REQUESTED** [review]
Your code is missing indentation, and lines 4-7 are probably from a method that wasn't added to the code.

**Comment by MSufiyanAG** [comment]
@ricardoprins  I did the necessary changes.You can merge it .
I had a doubt if i want to write explanations for algos which are already written(only code)by others for wiki where should i do that.

**Comment by mar-galho** [comment]
You can either fork the wiki and submit it, or if you want, you can just upload them into any folder and tag me as a reviewer and I'll do it

**Review by mar-galho — APPROVED** [review]
Great!

**Pull request merged**
