### PR TITLE
Prefix Sum Array in C++

### PR DESCRIPTION
**Pull request by RaiyanMahin**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

YES.

### Description

Given an array of N elements , find it's prefix sum array. In Competitive Programming, many times we need to calculate prefix sum array to solve our problem.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#3014

### CODE REVIEW

**Review by ankitaggarwal23 — CHANGES_REQUESTED** [review]
Few changes Required:
- Remove the space between line no. 24-26
- Add a new line above `int main()`
- Align your code properly in `int main()` function

**Comment by RaiyanMahin** [comment]
@ankitaggarwal23  I made all changes.
Kindly review.

**Review by ankitaggarwal23 — APPROVED** [review]

**Comment by RaiyanMahin** [comment]
@ankitaggarwal23 thanks for merged the PR. ready-to-merge label?

**Comment by RaiyanMahin** [comment]
@ankitaggarwal23 Thanks for merged the PR.
ready-to-merge label?

**Pull request merged**
