### PR TITLE
Added ZigZag Tree Traversal

### PR DESCRIPTION
**Pull request by tanyarajhans**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes.

### Description

ZigZag Tree Traversal is a famous interview question and I thought it would be a great addition to this repo, so I have added it.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

### CODE REVIEW

**Comment by tanyarajhans** [comment]
Please suggest any changes if needed. Thanks!

**Review by HarshCasper — APPROVED** [review]

**Comment by HarshCasper** [comment]
Thanks!

**Review by ankitaggarwal23 — COMMENTED** [review]
Copied the main code logic from [here](https://www.geeksforgeeks.org/zigzag-tree-traversal/).

**Comment by tanyarajhans** [comment]
> Copied the main code logic from [here](https://www.geeksforgeeks.org/zigzag-tree-traversal/).

You should be aware that I can't produce a new algorithm and study from internet resources and learn but write my own code. I don't understand why you would do this but go ahead!

**Pull request merged**
