### PR TITLE
Add Code For Interval List Intersection.cpp

### PR DESCRIPTION
**Pull request by ANUJAGRAWAL2000**
I worked on this issue as a participant of GSSOC'21

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)
Yes I have read the guideline carefully!!
### Description

(Write your answer here.)

### Checklist

- [Yes] I've read the contribution guidelines.
- [Yes] I've checked the issue list before deciding what to submit.
- [Yes ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

### CODE REVIEW

**Comment by ANUJAGRAWAL2000** [comment]
I have added the code for Interval_List_Intersection.cpp. If any changes required please notify.

**Comment by ANUJAGRAWAL2000** [comment]
I have added the Code For Binary Coded String #2932 . I have add the Code, Description about the issue, Sample Input / Output.
If any changes required please notify.

**Comment by ANUJAGRAWAL2000** [comment]
This one check "DeepSource: Java (beta) Failing after 9s — Analysis Failed: Issues detected that need attention." is getting Failed.
How to resolve this?

**Comment by ankitaggarwal23** [comment]
@ANUJAGRAWAL2000 We don't accept PRs without any corresponding Issue.

Capture

There are tons of issues available how to find your issue. Also Kindly Don't interlinked other issues no. review as your this PR looks confusing which to review. Create a new one and Mention the details correctly related to that particular issue. Closing this PR as of now.

**Pull request closed without merging**
