### PR TITLE
Sub1

### PR DESCRIPTION
**Pull request by siddharth-143**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

### Description

(Write your answer here.)

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

### CODE REVIEW

**Review by Suvraneel — CHANGES_REQUESTED** [review]
Please change only those files that require changing...
Remove the json files.

**Comment by siddharth-143** [comment]
Sir/mam
I don't know about it.
Would you like to help me please.

**Comment by Suvraneel** [comment]
How this works is:
1. Raise an issue
2. Get assigned
3. PR

Go through the Contribution Guidelines...
https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests

**Comment by siddharth25pandey** [comment]
@siddharth-143 Code plagiarized from [here](https://www.geeksforgeeks.org/stack-set-3-reverse-string-using-stack/) and Proper PR Creation guidelines was not followed.

**Pull request closed without merging**
