### PR TITLE
Completed Queue using Linked List

### PR DESCRIPTION
**Pull request by bagladivyang03**
Please read [how to contribute](CONTRIBUTING.md) first!
# Description
Submission description here

Checklist
* [x] I've checked the issue list __BEFORE__ deciding what to submit
* [x] I've read the contribution guidelines
* [x] I've edited the README.md link to my code

## Don't forget to visit our [website](http://www.tesseractcoding.tech)!

Feel free to add this badge after your submission is accepted!

```
<a href=https://github.com/TesseractCoding/NeoAlgo>
   <img src=https://img.shields.io/badge/NeoAlgo-Contributor-brightgreen>
</a>
```

### CODE REVIEW

**Review by mar-galho — CHANGES_REQUESTED** [review]
Please add the link to your code to the README.md file

**Comment by iamrajiv** [comment]
@bagladivyang03 Please solve the conflicts.

**Comment by bagladivyang03** [comment]
Yeah but i have read that it was already implemented so i think it will not be accepted  then should i solve conflict or it will not be accepted

**Comment by iamrajiv** [comment]
@bagladivyang03 Yeah, LinkedList is already implemented using struct. But this can also be added since the approach is different from the previous.

**Comment by bagladivyang03** [comment]
Ok I will solve basically I have updated the readme also and also provided link but what is the issue i m not understanding

**Comment by iamrajiv** [comment]
@bagladivyang03 You do not have to update anything. I have already formatted the code and updated the readme in my last 2 commits. The problem is that there is conflict between the branch `patch-1` and `TesseractCoding:master` because there is an update in `TesseractCoding:master` branch and your branch is not updated according to `TesseractCoding:master`.

**Comment by bagladivyang03** [comment]
Okay so i have to update my branch ? So how to do ?

**Comment by iamrajiv** [comment]
@bagladivyang03 Just copy the content of readme file from [TesseractCoding:master](https://github.com/TesseractCoding/NeoAlgo) and click on` Resolve conflicts` and paste it there. Also, add your [Queue using Linked List](ds/QueueLinkedList.cpp)  in `ds` section of C++

**Comment by iamrajiv** [comment]
@bagladivyang03 Just copy the content of readme file from [NeoAlgo/C++/README.md
](https://github.com/TesseractCoding/NeoAlgo/blob/master/C%2B%2B/README.md) and click on` Resolve conflicts` and paste it there. Also, add your [Queue using Linked List](ds/QueueLinkedList.cpp)  in `ds` section of C++

**Comment by iamrajiv** [comment]
@bagladivyang03 Just copy the content of readme file from [NeoAlgo/C++/README.md
](https://github.com/TesseractCoding/NeoAlgo/blob/master/C%2B%2B/README.md) and click on` Resolve conflicts` and paste it there. Also, add [Queue using Linked List](ds/QueueLinkedList.cpp)  to the readme.

**Comment by iamrajiv** [comment]
@bagladivyang03 Just copy the content of readme file from [NeoAlgo/C++/README.md
](https://github.com/TesseractCoding/NeoAlgo/blob/master/C%2B%2B/README.md) and click on` Resolve conflicts` and paste it there. Also, add `Queue using Linked List`  to the readme.

**Comment by bagladivyang03** [comment]
Now can u pls check is it done ?

**Review by iamrajiv — APPROVED** [review]

**Comment by iamrajiv** [comment]
@bagladivyang03 LGTM! Thanks for the PR.

**Comment by mar-galho** [comment]
Great job, guys!

**Comment by iamrajiv** [comment]
@all-contributors please add @bagladivyang03 for code

**Pull request merged**
