### PR TITLE
left rotate the array by one

### PR DESCRIPTION
**Pull request by RYzen-009**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?
Yes

### Description

Left rotate the given array by one 

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
#6017

### CODE REVIEW

**Review by ankitaggarwal23 — COMMENTED** [review]
Don't push more than one code file in a single PR.

**Comment by RYzen-009** [comment]
I did't  understood pls explain the issue briefly.

**Comment by ankitaggarwal23** [comment]
you are adding more that one code file and readme update

**Comment by RYzen-009** [comment]
okkh so I need to create a different branch for different issue

**Pull request closed without merging**
