### PR TITLE
Linked lists Intersection

### PR DESCRIPTION
**Pull request by pradeep98**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

[Python] Intersection of Y-shaped Linked Lists

### Checklist

- [X] I've read the contribution guidelines.
- [X] I've checked the issue list before deciding what to submit.
- [X] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

[Intersection Point in Y Shaped Linked Lists #495](https://github.com/TesseractCoding/NeoAlgo/issues/495)

### CODE REVIEW

**Comment by Kajol-Kumari** [comment]
Hey @pradeep98 can you please give me a bit of clarification about what this code is actually doing. Like the point of intersection means the common element after skipping the mentioned number of element or anything else? Please go with this example:

```
Elements of list1: 1,2,3,4,5                                                                                                   
Elements of list2: 6,7,8,9,0                                                                                                   
No. of elements to be skipped for l1: 1                                                                                        
No. of elements to be skipped for l1: 1
2
```
I am getting here output as `2`

**Comment by pradeep98** [comment]
> Hey @pradeep98 can you please give a bit of clarification about what this code is actually doing. Like the point of intersection means the common element after skipping the mentioned number of element or anything else? Please go with this example:
> 
> ```
> Elements of list1: 1,2,3,4,5                                                                                                   
> Elements of list2: 6,7,8,9,0                                                                                                   
> No. of elements to be skipped for l1: 1                                                                                        
> No. of elements to be skipped for l1: 1
> ```

Ma'am, for the 2 lists to intersect, we need to mention the no. of skips for both the lists. The quoted input is invalid because after 1 skip list 1 element is 2 while that of list 2 is 7. Why this skips thing? Idea is- making **equal values** of these two lists will not be enough to make it a Y-shaped. These two lists should have **same nodes** after the point of intersection. 
Input has to be given keeping in mind, if we want to make these 2 lists to intersect or not.
To make them intersect 2 lists should have some equal nodes and these equal value nodes appear after skip1 in l1 and skip2 in l2.
To make the lists not to intersect, skip1 should be equal to length of l1, skip2 = length of l2. This will make us jump to the end of list and we couldn't join them at all. 
Its just the input part of the question. There is no other way to make a Y-shaped linked list.

**Comment by pradeep98** [comment]
> Hey @pradeep98 can you please give me a bit of clarification about what this code is actually doing. Like the point of intersection means the common element after skipping the mentioned number of element or anything else? Please go with this example:
> 
> ```
> Elements of list1: 1,2,3,4,5                                                                                                   
> Elements of list2: 6,7,8,9,0                                                                                                   
> No. of elements to be skipped for l1: 1                                                                                        
> No. of elements to be skipped for l1: 1
> 2
> ```
> 
> I am getting here output as `2`

I've updated the code to prevent the user from giving wrong input. In the quoted example , i.e. l1-1,2,3,4,5 l2=6,7,8,9,0 skip1=1 skip2=1, Its like we are trying to make two lists intersect at position no. 2, however, values at position 2 in both lists are not same so they can not be intersected. Its like a fail try to intersect two lists.
This problem is tagged as an easy one. Indeed its an easy problem if we talk about finding the intersection point. However, constructing a Y-shaped linked list in itself is a good problem.

**Comment by Kajol-Kumari** [comment]
Hey @pradeep98 thanks for explanation. So can we modify your code so that :
1.don't take any skip input from user instead just show the output of both lists taking the first intersecting point of both the list as head of the list.
2. If the user enters an input having no intersecting point, just show them a message telling that there is no intersection point in it.
3. make a new list of all the intersecting points and then print it.

we can provide this in switch/case option to the users.

Please let me know if it sounds good to you, i will change the label of this PR accordingly then.

**Review by Abhijit2505 — CHANGES_REQUESTED** [review]
@pradeep98 , do the changes as requested by @Kajol-Kumari, and you are ready to go further.

**Comment by pradeep98** [comment]
> Hey @pradeep98 thanks for explanation. So can we modify your code so that :
> 1.don't take any skip input from user instead just show the output of both lists taking the first intersecting point of both the list as head of the list.
> 2. If the user enters an input having no intersecting point, just show them a message telling that there is no intersection point in it.
> 3. make a new list of all the intersecting points and then print it.
> 
> we can provide this in switch/case option to the users.
> 
> Please let me know if it sounds good to you, i will change the label of this PR accordingly then.

@Kajol-Kumari Ma'am, I've modified the most of the code. Sorry for being late, was busy with some project.
Now first 2 lines of the input are uncommon part in both lists.
3rd line can be kept empty if we do not want 2 lists to intersect. If we want them to, then just specify the common elements. 
Please change the label as well.

**Comment by Kajol-Kumari** [comment]
@pradeep98 thanks for incorporating the changes. Please do the following changes and it'll be good to go :) 
1. resolve the conflict here.
2. show a valid message like `No intersecting point found!`  instead of just showing `False` when there is no intersection point.

**Comment by pradeep98** [comment]
> @pradeep98 thanks for incorporating the changes. Please do the following changes and it'll be good to go :)
> 
> 1. resolve the conflict here.
> 2. show a valid message like `No intersecting point found!`  instead of just showing `False` when there is no intersection point.

@Kajol-Kumari  Changes made.

**Comment by pradeep98** [comment]
@Kajol-Kumari @SKAUL05 @Abhijit2505 please review

**Review by SKAUL05 — APPROVED** [review]

**Comment by pradeep98** [comment]
@Kajol-Kumari @Abhijit2505 Review it please so that I can move on.

**Review by Abhijit2505 — APPROVED** [review]

**Comment by Abhijit2505** [comment]
@HarshCasper, please merge this PR

**Review by atarax665 — APPROVED** [review]

**Pull request merged**
