### PR TITLE
Implementation of Trie in Java

### PR DESCRIPTION
**Pull request by Himanshu70565**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes
### Description

Implementation of Trie Data Strucuture in java .

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#849

### CODE REVIEW

**Comment by Himanshu70565** [comment]
@siddharth25pandey  Can you please review the pr?

**Comment by Himanshu70565** [comment]
@siddharth25pandey I have removed the merge conflicts . Can you review the pr now ?

**Review by iamrajiv — CHANGES_REQUESTED** [review]
@Himanshu70565 Add sample input-output and format the code using code formatted. Also, add a description of Trie Data Structure.

**Comment by atarax665** [comment]
Closing due to inactivity from the contributor's end.

**Pull request closed without merging**
