### PR TITLE
Added 3 way quick sort in cpp

### PR DESCRIPTION
**Pull request by satcasm**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

I have added 3 way quick sort in cpp

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#5417

### CODE REVIEW

**Comment by satcasm** [comment]
@ankitaggarwal23 @HarshCasper please review my PR.

**Review by ankitaggarwal23 — COMMENTED** [review]
Problem is already present

**Comment by satcasm** [comment]
Hey @ankitaggarwal23 I can't seem to find this in the readme section of cpp, so I don't think it exists already , have a look again.
There is only one 3 way algo ,i.e., ```three_way_merge_sort```.
Thanks!

**Comment by ankitaggarwal23** [comment]
> Hey @ankitaggarwal23 I can't seem to find this in the readme section of cpp, so I don't think it exists already , have a look again.
> There is only one 3 way algo ,i.e., `three_way_merge_sort`.
> Thanks!

Yes because other contributors didn't name it properly while creating issue and PR. we are working on it.

**Pull request closed without merging**
