### PR TITLE
Create Minimum Sum Partition.py

### PR DESCRIPTION
**Pull request by Ajay0511**
In this problem given set is partitioned into two subsets such that the difference between the sum of elements of 1st set and the sum of elements of 2nd set is minimized.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Minimum Sum Partition

### Description

In this problem given set is partitioned into two subsets such that the difference between the sum of elements  of 1st set and the sum of elements of 2nd set is minimized.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

### CODE REVIEW

**Review by Kajol-Kumari — CHANGES_REQUESTED** [review]
Please update the readme file.

**Comment by Ajay0511** [comment]
> Please update the readme file.

Done @Kajol-Kumari

**Review by siddharth25pandey — APPROVED** [review]
@Ajay0511 Perfect code
Able to merge
Thanks!

**Review by iamrajiv — CHANGES_REQUESTED** [review]
@Ajay0511 Update the README. Rename the program name to `Minimum_Sum_Partition.py`. Format your code according to PEP 8 rules. You can refer to this http://pep8online.com/.

**Comment by Kajol-Kumari** [comment]
> > Please update the readme file.
> 
> Done @Kajol-Kumari

@Ajay0511 I can't see the changes here. please verify it on your end once.

**Pull request merged**
