### PR TITLE
Added Number of Digits Program

### LINKED ISSUE #5067: Wanted to add program to find the total no. of digit in a number in c
## 💥 Proposal
As I saw that there is no program related to find the total no. of digits in a number in c language so can i add this program
Ex. Input: 43645
     Output: The total no. of digits in `43645` are 5 
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes I have read the contributing guidelines

### PR DESCRIPTION
**Pull request by UG-SEP**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes,I have Read the contributing.md 
## Description
Program to check total number of digit or count of digits in a number 

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Resolve: #5067

### CODE REVIEW

**Comment by UG-SEP** [comment]
@siddharth25pandey  Please review it

**Comment by UG-SEP** [comment]
@ankitaggarwal23 and @HarshCasper  please review it

**Comment by UG-SEP** [comment]
please review it @ankitaggarwal23

**Comment by siddharth25pandey** [comment]
@UG-SEP Not a valid Algorithm

**Comment by UG-SEP** [comment]
@siddharth25pandey can you please let me to know that why this is invalid algorithm so that i can understand that how to create a valid algorithm and also learn for it

**Pull request closed without merging**
