### PR TITLE
Added Linear Regression using PyTorch

### PR DESCRIPTION
**Pull request by farazkhanfk7**
Please read [how to contribute](CONTRIBUTING.md) first!
# Description
Submission description here

Checklist
* [x] I've checked the issue list __BEFORE__ deciding what to submit
* [x] I've read the contribution guidelines
* [x] I've edited the README.md link to my code

## Don't forget to visit our [website](http://www.tesseractcoding.tech)!

Feel free to add this badge after your submission is accepted!

```
<a href=https://github.com/TesseractCoding/NeoAlgo>
   <img src=https://img.shields.io/badge/NeoAlgo-Contributor-brightgreen>
</a>
```

### CODE REVIEW

**Comment by anushkrishnav** [comment]
Awesome .Looks good Thank you

**Comment by farazkhanfk7** [comment]
@anushkrishnav  @HarshCasper  Can you add me to the list of contributors ?

**Comment by anushkrishnav** [comment]
@farazkhanfk7 You have been added .  Its automated :) . Have a nice day

**Comment by farazkhanfk7** [comment]
@anushkrishnav  I thought it was using allcontributors bot ?

**Comment by anushkrishnav** [comment]
Yes it is. I meant we will automaticaly add it DW abt it . Have  a great day .

**Comment by anushkrishnav** [comment]
@all-contributors please add @farazkhanfk7 for code

**Pull request merged**
