### PR TITLE
Added a Prime Checker Program in java

### PR DESCRIPTION
**Pull request by amit14mitra**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

### Description

(Write your answer here.)

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

### CODE REVIEW

**Comment by atarax665** [comment]
Please do fill the PR form and create an issue if this program hasn't been proposed yet.

**Comment by amit14mitra** [comment]
> Please do fill the PR form and create an issue if this program hasn't been proposed yet.

>I have proposed an issue..but I didn't get your pr form fill up part?

**Comment by amit14mitra** [comment]
Hi,

I have done that.you can check now if further anything needed to be done

Thanks,
Amit

**Comment by atarax665** [comment]
Get the issue assigned to you before pulling a request.

**Pull request closed without merging**
