### PR TITLE
Shell Sort in C

### PR DESCRIPTION
**Pull request by yashaswibiyahut**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

**YES**

### Description

Issue No: #387
_Implementation of Shell Sort_
It is a generalized version of **insertion sort.**
In shell sort, elements at a specific interval are sorted.
**Complexity:**
Worst case time complexity = O(n2)
Best case complexity = O(nlog(n)).
Space complexity = O(1).

_Below is the output of this code._

### Checklist

- [x]  I've read the contribution guidelines. 
- [x] I've checked the issue list before deciding what to submit.
- [x]  I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

### CODE REVIEW

**Comment by yashaswibiyahut** [comment]
C__Users_yashaswi Biyahut_Desktop_Github Projects_ShellSort exe 9_4_2020 3_09_24 PM (2)
Output of above code.

**Comment by yashaswibiyahut** [comment]
kindly review this PR @Kajol-Kumari @SKAUL05 @siddharth25pandey @iamrajiv @HarshCasper

**Review by atarax665 — APPROVED** [review]
LGTM :+1:

**Review by Kajol-Kumari — APPROVED** [review]
LGTM :+1:

**Comment by yashaswibiyahut** [comment]
kindly review this PR @iamrajiv

**Review by iamrajiv — APPROVED** [review]

**Pull request merged**
