### PR TITLE
Stack

### PR DESCRIPTION
**Pull request by parjanyaacoder**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Implemented Stack in Java using Linked List

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#399

### CODE REVIEW

**Comment by parjanyaacoder** [comment]
@siddharth25pandey Please review.

**Review by siddharth25pandey — CHANGES_REQUESTED** [review]
@parjanyaacoder Please do following modifications
* Peek operation is missing, Implement it.
* Make the Program interface more user friendly by doing following things
   * Print the Success message after each operation
   * If user don't enter the choice value ranging in between it. Then it must show "Enter Valid Input"
   * One Choice for Exit operation
   * Heading of the topic should be present on the top of the Program while Execution

**Review by parjanyaacoder — COMMENTED** [review]
@siddharth25pandey Please review. Done some changes.

**Review by siddharth25pandey — CHANGES_REQUESTED** [review]
@parjanyaacoder Success message doesn't mean you have to write the word **Success** everywhere. It means according to your operation, it show some message like 
The element is inserted/deleted Successfully.
* Also Count of element is missing
* Display of all the elements present in the Stack is missing.

**Review by parjanyaacoder — COMMENTED** [review]
@siddharth25pandey @iamrajiv @plazzy99 Please review.

**Review by vatsalkesarwani12 — APPROVED** [review]
The code works well for me.

**Review by iamrajiv — APPROVED** [review]

**Review by siddharth25pandey — APPROVED** [review]
@parjanyaacoder Looks fine to me
Able to merge
Thanks!

**Pull request merged**
