### PR TITLE
Added happy number code in C

### PR DESCRIPTION
**Pull request by arnab031**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes.

### Description

Write a program in C to check a number is Happy Number or not. 

### Checklist

- [Y] I've read the contribution guidelines.
- [Y] I've checked the issue list before deciding what to submit.
- [Y] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#1308

### CODE REVIEW

**Review by atarax665 — CHANGES_REQUESTED** [review]
Format your code as:
```
#include<stdio.h>
#include<math.h>

void main(){
    int n, sum, digit;
    printf("Enter a number: ");
    scanf("%d", &n);
    int temp = n;
    while(sum != 1 && sum != 4){
            sum = 0;
        while(temp != 0){
            digit = temp % 10;
            sum += digit * digit;
            temp = temp / 10;
        }
        temp = sum;

    }
    if(sum == 1)
        printf("%d is a happy number.",n);
    else
        printf("%d is not a happy number.",n);
}

/*
    Sample input/output:
    Example 1:
    Input : Enter a number: 32
    Output : 32 is a happy number
    Example 2:
    Input : Enter a number: 14
    Output : 14 is not a happy number
*/
```

**Comment by arnab031** [comment]
What will I change in my file? I cannot understand.

**Comment by arnab031** [comment]
I have changed my code. Please check it. @atarax665

**Review by atarax665 — APPROVED** [review]
Looks good to me.👍

**Review by vatsalkesarwani12 — APPROVED** [review]
👍🏻

**Comment by iamrajiv** [comment]
@all-contributors please add @arnab031 for code

**Pull request merged**
