### PR TITLE
Vignere Cipher Algorithm - C

### PR DESCRIPTION
**Pull request by SangeetaMishra**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

(Write your answer here.)

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#974

### CODE REVIEW

**Review by iamrajiv — CHANGES_REQUESTED** [review]
@SangeetaMishra Make separate functions for encryption and decryption. Key and Message should be given by user. Make something like this
```
Input:
Enter Message To Encode:
Enter Key:

Output:
Generated Key:
Encrypted Message:
Decrypted Message:
```

**Comment by SangeetaMishra** [comment]
@iamrajiv I have made the changes

**Review by Kajol-Kumari — APPROVED** [review]
LGTM :+1:

**Review by iamrajiv — APPROVED** [review]

**Review by vatsalkesarwani12 — APPROVED** [review]
👍🏻

**Pull request merged**
