### PR TITLE
Format all Python programs according to PEP 8 rules

### PR DESCRIPTION
**Pull request by SangeetaMishra**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

(Write your answer here.)

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#985

### CODE REVIEW

**Review by iamrajiv — APPROVED** [review]
@SangeetaMishra Nice Work. Hope you have checked that all the programs are running fine after formatting.

**Review by vatsalkesarwani12 — APPROVED** [review]
Nice Work

**Review by Kajol-Kumari — COMMENTED** [review]
@SangeetaMishra Changes looks good to me but I tried running few of the programs like [this](https://github.com/TesseractCoding/NeoAlgo/pull/1024/files#diff-41611d0eb1a32d02bb971f52cda3a512) one as it's throwing indentation error.

\cc: @plazzy99 @iamrajiv

**Review by iamrajiv — CHANGES_REQUESTED** [review]
@SangeetaMishra Your most of program are not formatted according to PEP 8 rules please update like `Fibonacci.py`, `Russian_Peasant_Algorithm.py` etc.

**Comment by iamrajiv** [comment]
@Kajol-Kumari Thank You for mentioning this issue. Also, @SangeetaMishra you can refer http://pep8online.com/ to format the code.

**Comment by vatsalkesarwani12** [comment]
Thanks @Kajol-Kumari 
the code I ran showed no error so I approved it.
Checking again

**Comment by SangeetaMishra** [comment]
@iamrajiv I changed all the files according to PEP8 by the given link. All codes are working.

**Review by iamrajiv — APPROVED** [review]

**Comment by SangeetaMishra** [comment]
@Kajol-Kumari @plazzy99 Can you please review the PR

**Review by Kajol-Kumari — APPROVED** [review]
@SangeetaMishra Thanks for making required changes, Now everything seems to work fine :+1:

**Pull request merged**
