### PR TITLE
XOR Cipher in Python 

### PR DESCRIPTION
**Pull request by thuy-ttn**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

This in an implementation of XOR cipher in Python 3.8.
It can encrypt message with a given key and decrypt the message with top 5 possible plaintext.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

https://github.com/TesseractCoding/NeoAlgo/issues/1374#issue-727903659

### CODE REVIEW

**Review by iamrajiv — CHANGES_REQUESTED** [review]
@thuy-ttn Format your code according to PEP 8 rules. You can refer to this http://pep8online.com/.

**Comment by thuy-ttn** [comment]
> @thuy-ttn Format your code according to PEP 8 rules. You can refer to this http://pep8online.com/.

@iamrajiv  Done :))) Some last lines are about sample I/O so I can't change them.

**Review by iamrajiv — APPROVED** [review]

**Review by atarax665 — APPROVED** [review]
Good work :+1:

**Comment by iamrajiv** [comment]
@all-contributors please add @thuy-ttn for code

**Pull request merged**
