### PR TITLE
Decimal Equivalent of Gray code and its inverse in Kotlin

### PR DESCRIPTION
**Pull request by anuragmukherjee2001**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?
Yes, I have read the contributing guidelines.

### Description

The reflected binary code or Gray code is an ordering of the binary numeral system such that two successive values differ in only one bit (binary digit).
### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

I created an issue. The link of the issue is:
#5891

### CODE REVIEW

**Comment by anuragmukherjee2001** [comment]
Please review this PR.

**Review by ankitaggarwal23 — CHANGES_REQUESTED** [review]
Invalid problem written as binary and code is for decimal
Read the instructions mentioned on Gssoc discord yesterday. Do the changes as per that.
Readme file is buggy

**Comment by anuragmukherjee2001** [comment]
Sir I mistakenly wrote a wrong thing in the previous PR, which I corrected in this PR. I wrote the correct description in this PR, and also changed the README file.

**Review by ankitaggarwal23 — CHANGES_REQUESTED** [review]
Readme file has bug fix it

**Comment by anuragmukherjee2001** [comment]
> Readme file has bug fix it

I fixed the bug. Please check the PR.

**Review by ankitaggarwal23 — APPROVED** [review]

**Pull request merged**
