### PR TITLE
Added the code for flattening binary tree into linkedlist in-place in c++

### PR DESCRIPTION
**Pull request by ainy-123**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes.

### Description

Code for the mentioned problem.

The motivation behind doing these changes is that, to solve this question , clear and concise knowledge of both linkedlist and tree is required .Along with this ,I tried to cover many concepts like inorder and level order traversal ,queue ,struct etc and provided the complete solution along with sample input and output to understand the solution quickly.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

flattening binary tree to linkedlist in-place using c++ #3291

### CODE REVIEW

**Comment by ainy-123** [comment]
kindly check this ,I am not able to resolve conflicts. Suggest plz ,what to be done.

**Review by HarshCasper — CHANGES_REQUESTED** [review]
Few changes:
- Make the description shorter and more intuitive. Keep the diagrams below the code
- Format the Code and indent it properly
- Add code complexity

**Comment by ainy-123** [comment]
> Few changes:
> 
> * Make the description shorter and more intuitive. Keep the diagrams below the code
> * Format the Code and indent it properly
> * Add code complexity

Okay sir.

**Comment by ainy-123** [comment]
> Few changes:
> 
> * Make the description shorter and more intuitive. Keep the diagrams below the code
> * Format the Code and indent it properly
> * Add code complexity

Sir ,I have added, committed and pushed all the changes that you have mentioned. Kindly review it.

**Review by HarshCasper — APPROVED** [review]

**Pull request merged**
