### PR TITLE
Added the code for Kadane's Algorithm in Cpp

### PR DESCRIPTION
**Pull request by Jassi10000-zz**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)
Yes

### Description

(Write your answer here.)
Successfully added the code for Kadane's Algorithm in Cpp which is used to find max subarray sum in an array 
### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)
#3886

### CODE REVIEW

**Comment by ankitaggarwal23** [comment]
@Jassi10000 Already someone did this problem in C++. Kindly don't open such issue always check before opening a new issue.

**Review by ankitaggarwal23 — COMMENTED** [review]
@Jassi10000 Already someone did this problem in C++. Kindly don't open such issue always check before opening a new issue.

**Comment by Jassi10000-zz** [comment]
Can you show where the same issue has been opened ?
@ankitaggarwal23

**Comment by ankitaggarwal23** [comment]
@Jassi10000 #3791 #3436 #3886 #4042

**Comment by Jassi10000-zz** [comment]
> @Jassi10000 Already someone did this problem in C++. Kindly don't open such issue always check before opening a new issue.

@ankitaggarwal23  Kindly look closely , you will see that I didn't opened that , #3886 was opened by someone else and it was not assigned so I just assigned myself 
Anyways , I will take care in future  for further issues

**Pull request closed without merging**
