### PR TITLE
Median of array in java

### LINKED ISSUE #4822: Median of 2 sorted arrays
## 💥 Proposal
I am a GSOC participant and want to work on Median of Two Sorted Arrays using java

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?
Yes

### PR DESCRIPTION
**Pull request by Amit366**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Given two sorted arrays nums1 and nums2 of size m and n respectively, return the median of the two sorted arrays.

## Related Issues or Pull Requests

Fixes: #4822

### CODE REVIEW

**Comment by siddharth25pandey** [comment]
@Amit366 Excessive number of commits

**Comment by Amit366** [comment]
@siddharth25pandey once check the code at least. The commits will not affect the code.

**Comment by Amit366** [comment]
@siddharth25pandey and also no where it is mentioned that a fixed no of commits is allowed

**Comment by siddharth25pandey** [comment]
@Amit366 It's your duty to adhere the instruction given to you. It's better to keep silent if you don't know the effect of extra commits which were unnecessary made.
It's better for you to create a new PR with maximum **2 commits** until unless the reviewers ask to do the changes.

**Pull request closed without merging**
