### PR TITLE
Rotten Oranges Problem in C++

### PR DESCRIPTION
**Pull request by prithwirajmitra2001**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes I have

### Description

In response to #2564 
Added the code for the problem of the "_time taken to rot all oranges_" in C++.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

I have implemented this code in C++

### CODE REVIEW

**Review by atarax665 — CHANGES_REQUESTED** [review]
We recommend one PR, one issue. Please do not add multiple file changes in one PR.
Remove ```Reverse_Queue_content_using_Stack.cpp``` and make changes in README as well.

**Comment by prithwirajmitra2001** [comment]
Sorry Sir for the mistake.
Made the requested changes.
Please review.

**Comment by prithwirajmitra2001** [comment]
Please review again @atarax665

**Comment by prithwirajmitra2001** [comment]
@HarshCasper  @Apoorve73 
Please check this

**Review by HarshCasper — APPROVED** [review]

**Pull request merged**
