### PR TITLE
Areas of 2D and 3D figures

### PR DESCRIPTION
**Pull request by fomalhauting**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Areas of 2D and 3D figures in Golang

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Issue Number: #1473

### CODE REVIEW

**Comment by fomalhauting** [comment]
@shraddhavp Can you review it and let me know if I should make any changes?

**Comment by shraddhavp** [comment]
> @shraddhavp Can you review it and let me know if I should make any changes?

Everything looks good to me ,one addition can e adding time and space complexity at the end

**Comment by fomalhauting** [comment]
All done.

**Review by iamrajiv — CHANGES_REQUESTED** [review]
@itsIapetus Make a separate function for each figure and call that function in `func main()`. Also, you cannot use `package main` again and again in the same `.go` file. Format your code according to gofmt.

**Comment by fomalhauting** [comment]
Hello, I formatted it according to gofmt. Kindly take a look.

**Review by iamrajiv — APPROVED** [review]

**Comment by iamrajiv** [comment]
@all-contributors please add @itsIapetus for code

**Pull request merged**
