### PR TITLE
add armstrong number and update README

### PR DESCRIPTION
**Pull request by soumik-dhar**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Added Golang code for Armstrong Number in Math sextion 
(and a corresponding README update pointing to the `armstrong_number.go` file)

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
#1217

### CODE REVIEW

**Comment by soumik-dhar** [comment]
@iamrajiv  Kindly review my PR and let me know if any changes are needed.

**Review by atarax665 — APPROVED** [review]
Looks good to me :)

**Review by iamrajiv — APPROVED** [review]

**Comment by anushkrishnav** [comment]
Looks Good to me . Congrats on Merging your First PR

**Comment by soumik-dhar** [comment]
> Looks Good to me . Congrats on Merging your First PR

Cheers ✌

**Pull request merged**
