### PR TITLE
Tower of Hanoi algorithm in Golang

### PR DESCRIPTION
**Pull request by ahampriyanshu**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Implemented Tower of Hanoi algorithm in golang.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#793

### CODE REVIEW

**Review by siddharth25pandey — APPROVED** [review]
@ahampriyanshu Perfect Code
Able to merge
Thanks!

**Review by SKAUL05 — APPROVED** [review]

**Review by Kajol-Kumari — APPROVED** [review]
LGTM :+1:

**Comment by ahampriyanshu** [comment]
Sorry @SKAUL05 ,I requested the review by mistake.

**Review by iamrajiv — APPROVED** [review]

**Comment by iamrajiv** [comment]
@all-contributors please add @ahampriyanshu for code

**Pull request merged**
