### PR TITLE
causing error in fork

### PR DESCRIPTION
**Pull request by Gaurav6982**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

### Description

(Write your answer here.)

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

### CODE REVIEW

**Comment by Gaurav6982** [comment]
@atarax665 @plazzy99 @HarshCasper please check 
when I am forking this repository getting this 2 shell sort file 
these files are colliding and  preventing cloning of the repository 
please look to this issue 
my friends too faced this issue.
please look to this issue 

Thanks!

**Comment by atarax665** [comment]
> @atarax665 @plazzy99 @HarshCasper please check
> when I am forking this repository getting this 2 shell sort file
> these files are colliding and preventing cloning of the repository
> please look to this issue
> my friends too faced this issue.
> please look to this issue
> 
> Thanks!

How are you forking the repo? Using git?
And please share the image of the error that you are getting.

**Comment by Gaurav6982** [comment]
Capture
Here is the screenshot of the error I am getting while cloning and I have forked through the browser.
@atarax665

**Comment by atarax665** [comment]
I have removed the duplicate Shell Sort file, you can update your forked repo and try again.

**Pull request closed without merging**
