### PR TITLE
Hackerrank solution by Barnadip

### PR DESCRIPTION
**Pull request by barnamensch056**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?
Yes
(Write your answer here.)

### Description
Hackerrank solutions of some problems
(Write your answer here.)

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

### CODE REVIEW

**Comment by barnamensch056** [comment]
Mentors, can anyone say me how to resolve the conflict?

**Comment by barnamensch056** [comment]
@shraddhavp @iamrajiv @atarax665,please review my code?

**Comment by HarshCasper** [comment]
Hi @barnamensch056 

Can you please break down this PR into multiple other PRs? It is difficult to review multiple code pushed into a single PR and merging the same. 

Do let me know if that works. Thanks!

**Comment by barnamensch056** [comment]
Sure I'll give a try.

**Pull request closed without merging**
