### PR TITLE
linear probing, Quadratic Probing and Double Hashing in C++.

### PR DESCRIPTION
**Pull request by bhavya092**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes, I have.

### Description

Implementation of Three Hashing techniques (linear probing, Quadratic Probing and Double Hashing) in C++.  

### Checklist

- [yes] I've read the contribution guidelines.
- [yes] I've checked the issue list before deciding what to submit.
- [yes] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Hashing Techniques in C++ #3252

### CODE REVIEW

**Comment by bhavya092** [comment]
@HarshCasper Why is the  "DeepSource: Java (beta)" check failing? Can you please help me out here??

**Review by iamrajiv — CHANGES_REQUESTED** [review]
@bhavya092 Format your code using some code formatted there are a lot of unnecessary line break. Also, add sample input-output, space and time complexity. I would also suggest adding a little bit of description about each hashing technique in code comments.

**Comment by iamrajiv** [comment]
@bhavya092 Do not worry about `DeepSource: Java (beta)` there is a bug in it.

**Comment by bhavya092** [comment]
@iamrajiv I have added the necessary changes. Can you review them again please?

**Review by iamrajiv — APPROVED** [review]

**Comment by iamrajiv** [comment]
@all-contributors please add @bhavya092 for his code

**Pull request merged**
