### PR TITLE
Binary Tree

### PR DESCRIPTION
**Pull request by shobhu98**
Please read [how to contribute](CONTRIBUTING.md) first!
# Description
Submission description here

Checklist
* [x] I've checked the issue list __BEFORE__ deciding what to submit
* [x] I've read the contribution guidelines
* [x] I've edited the README.md link to my code

## Don't forget to visit our [website](http://www.tesseractcoding.tech)!

Feel free to add this badge after your submission is accepted!

```
<a href=https://github.com/TesseractCoding/NeoAlgo>
   <img src=https://img.shields.io/badge/NeoAlgo-Contributor-brightgreen>
</a>
```

### CODE REVIEW

**Review by mar-galho — CHANGES_REQUESTED** [review]
Please add the link to your code to the README.md file

**Comment by shobhu98** [comment]
Done.Can you please merge now?

**Comment by mar-galho** [comment]
I'd gladly request that you read the submission instructions. The link is still not there.

**Comment by shobhu98** [comment]
Yes I read all the contribution guidelines and updated the Readme.Md  with the link

**Comment by mar-galho** [comment]
The thing is - you've edited the wrong README.md file. If you could please remove these two edits you've made and just add the link to the README.md file at the Java main folder, we'd appreciate it!

Also, in the future, consider adding a more descriptive title to your PRs - for example, if I read this, I have no idea of knowing whether your code is to a Java binary tree or to a Julia binary tree code.

This helps reviewers who work in a particular language to choose to review your code instead of a code in a language they're not proficient in.

Thanks for your contribution!

**Comment by shobhu98** [comment]
I am sorry but still I am not able to understand, Can you please elaborate which Readme.md file I have to edit and add the link of my code?

**Comment by shobhu98** [comment]
I went through the contribution guidelines as well

**Comment by mar-galho** [comment]
/Java/README.md

**Comment by shobhu98** [comment]
cllosing

**Comment by mar-galho** [comment]
@all-contributors please add @shobhu98 for code.

Hey, since you forgot to add your code to the other PR, I've manually copied your code here and submitted to the repo myself. Make sure to pull/rebase the fork, and thank you very much for your contribution!

**Comment by mar-galho** [comment]
@all-contributors please add @shobhu98 for code

**Pull request closed without merging**
