### PR TITLE
Decision Tree from scratch

### PR DESCRIPTION
**Pull request by Pythonista7**
A commented implementation of a simple decision tree.

### CODE REVIEW

**Comment by mar-galho** [comment]
Hi! Could you also add the correspondent link to the python README.md file? Thanks for your contribution! :)

**Review by mar-galho — CHANGES_REQUESTED** [review]
Add corresponding link to README.md file

**Comment by mar-galho** [comment]
@Pythonista7

**Comment by Pythonista7** [comment]
@ricardoprins I've added the required in the README.MD . Thank you.

**Review by mar-galho — APPROVED** [review]
Thanks a lot!

**Comment by mar-galho** [comment]
@all-contributors please add @Pythonista7 for code

**Pull request merged**
