### PR TITLE
Dijsktra Algorithm

### LINKED ISSUE #5340: Dijsktra Algorithm
Dijsktra Algorithm is a greedy algorithm which is the shortest path algorithm.I would like to add it in the JAVA section.
Please assign it to me.

### PR DESCRIPTION
**Pull request by Khushi-agarwal**
Fixes #5340 

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?
Yes

### Description
I have added a greedy algorithm in the JAVA section and the algorithm is Dijsktra Algorithm which is used to find the shortest path in a graph from the source vertex.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

This Pr solves the issue #5340

### CODE REVIEW

**Comment by Khushi-agarwal** [comment]
@HarshCasper @bhav09 Can you please look into it.

**Comment by Khushi-agarwal** [comment]
@ankitaggarwal23 please review it.

**Review by ankitaggarwal23 — COMMENTED** [review]
Don't push more than one code file in a single PR.

**Comment by Khushi-agarwal** [comment]
@ankitaggarwal23 it's just one code file i.e dijskta.java

**Comment by bhav09** [comment]
You were to add only 2 files. One is the updated readme and the other is the code file.

**Comment by Khushi-agarwal** [comment]
Okay @bhav09 .I will create a new pr for the same and will make the changes there.Thank you.

**Pull request closed without merging**
