### PR TITLE
Issue2585

### PR DESCRIPTION
**Pull request by taruni-always**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes
### Description
(Issue #2585)
I wanted to contribute under GSSoC '21. This is an easy and an important application of stack data structure.
(Please ignore the first commit with message "created infixToPrefix.c and edited README.md".  ( I'm a beginner ) I accidently made changes related to a different issue (of the same project) in this branch, and i immediately rectified it. I apologise for this)

### Checklist

- [ Yes] I've read the contribution guidelines.
- [ Yes] I've checked the issue list before deciding what to submit.
- [Yes ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

None

### CODE REVIEW

**Review by siddharth25pandey — CHANGES_REQUESTED** [review]
@taruni-always Do the suggested changes below
* Add Sample Input and Output at the end of Program
* Insert suitable comment in-between some functions and variables.
Rest is fine :)

**Comment by siddharth25pandey** [comment]
@taruni-always Also add issue number in the PR Template and resolve the merge conflict errors.

**Comment by taruni-always** [comment]
@siddharth25pandey In python I wrote the sample input/output as a multiline comment, but it fails a check saying unassigned string statement. what should I do about this? (All the other changes are done from my side.

**Comment by siddharth25pandey** [comment]
> @siddharth25pandey In python I wrote the sample input/output as a multiline comment, but it fails a check saying unassigned string statement. what should I do about this? (All the other changes are done from my side.

@taruni-always Try writing in single line comment and resolve the below changes as well
* Resolve the merge conflicts
* Add Time and Space Complexity of the Algorithm

**Comment by taruni-always** [comment]
I made suggested changes (adding time and space complexity), but now, all the other files (that i haven't even edited because they're not mine) are giving me errors. I did not make any changes in all these Go, java or Python files but the DeepSource is going through the whole codebase. I don't know why this is happening. Please help me.
op
op2

**Comment by siddharth25pandey** [comment]
@taruni-always Merge Conflict error generally occurs when GIT not able to fetch in which branch you want to add the commits you did earlier. Better to create a new PR or try to resolve the merge conflict errors.
PS: Don't worry about the automated checks system.

**Comment by taruni-always** [comment]
@siddharth25pandey I will make a new PR and close this. Thank you :-)

**Pull request closed without merging**
