### PR TITLE
Added implementation of Caesar Cipher Algorithm in C 

### LINKED ISSUE #422: Caesar Cipher Algorithm - Cryptography
## 🚀 Feature

(A clear and concise description of what the feature is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Carsar Cipher is one of most basic techniques to encode and decode a message

## Motivation

As a part of the other amazing Algorithms in core programming languages, would like to add Cryptography to this.

## Pitch

Cryptography is a rising need and a bit of insight through this platform will help people modify and implement in various security settings. 

## Assignees 

- Java: @parjanyaacoder
- Python: @SayaniG371 
- C++: @Jyotika999
- C: @ankitaggarwal23
- GO:

### PR DESCRIPTION
**Pull request by ankitaggarwal23**
Have you read the Contributing Guidelines on Pull Requests?
Yes, I have read the Contributing Guidelines on Pull Requests.

Description
• Added implementation of Caesar Cipher Algorithm in C.

Checklist
☑︎ I've read the contribution guidelines.
☑︎ I've checked the issue list before deciding what to submit.
☑︎ I've edited the README.md and link to my code.

Related Issues or Pull Requests
Fixes #422 for C language

### CODE REVIEW

**Comment by iamrajiv** [comment]
@ankitaggarwal23 LGTM!

**Review by iamrajiv — APPROVED** [review]

**Comment by iamrajiv** [comment]
@ankitaggarwal23 remove `prime_factors.cs` file

**Review by iamrajiv — CHANGES_REQUESTED** [review]
@ankitaggarwal23 remove prime_factors.cs file

**Review by iamrajiv — APPROVED** [review]

**Review by atarax665 — APPROVED** [review]
LGTM :)

**Review by iamrajiv — APPROVED** [review]

**Review by Kajol-Kumari — APPROVED** [review]
LGTM :)

**Comment by iamrajiv** [comment]
@all-contributors please add @ankitaggarwal23 for code

**Pull request merged**
