### PR TITLE
Floyd–Warshall Algorithm in JavaScript

### LINKED ISSUE #6409: Floyd–Warshall Algorithm in JavaScript
## 💥 Proposal

Adding Floyd–Warshall Algorithm in JavaScript

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

### PR DESCRIPTION
**Pull request by anniesaxena**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Added Floyd Warshall Algorithm in JavaScript

### Checklist

- [X] I've read the contribution guidelines.
- [X] I've checked the issue list before deciding what to submit.
- [X] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Fixes: #6409

### CODE REVIEW

**Comment by anniesaxena** [comment]
@ankitaggarwal23 can you please review this

**Review by ankitaggarwal23 — COMMENTED** [review]
We don't accept PRs without any corresponding Issue. It is difficult for us to find your issue in tons of issues available. We can't review and merged incomplete PR's.

**Comment by anniesaxena** [comment]
@ankitaggarwal23 I'm sorry but you just edited my PR and removed the issue from there.

**Comment by ankitaggarwal23** [comment]
> @ankitaggarwal23 I'm sorry but you just edited my PR and removed the issue from there.

I have fixed the typo in your description. Why should I removed the issue no. ?

**Comment by anniesaxena** [comment]
Actually my issue no. was already there...that's why I had confusion

**Comment by anniesaxena** [comment]
@ankitaggarwal23 thanks!!

**Review by ankitaggarwal23 — CHANGES_REQUESTED** [review]
Few changes: 

- Add Multi-Line Comments 
- Add a beginner-friendly description at the top
- Use proper code Format 
- Remove extra lines of code and spaces
- Add sample I/O at the end of the Code
- Add Time and Space Complexity at the end of the Code   
- Add new line at the EOF
- Use proper display message how you are reading and writing outputs
- Add input-output prompts to make the program more interactive.

**Review by ankitaggarwal23 — COMMENTED** [review]
Closing this due to inactivity. Thank you for your valuable time.😊

**Pull request closed without merging**
