### PR TITLE
[Java] Implementation of Optimized Bubble Sort.

### PR DESCRIPTION
**Pull request by Lakhan-Nad**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

yes

### Description

Optimized Version of Bubble Sort in JAVA Language.

### Checklist

- [X] I've read the contribution guidelines.
- [X] I've checked the issue list before deciding what to submit.
- [X] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Issue #436

### CODE REVIEW

**Review by siddharth25pandey — APPROVED** [review]
@Lakhan-Nad Already reviewed your previous closed PR.
Good to go.
Thanks!

**Comment by Lakhan-Nad** [comment]
@siddharth25pandey Thankyou!

**Review by Kajol-Kumari — APPROVED** [review]
Well formatted and clean code! LGTM :+1:

**Review by atarax665 — APPROVED** [review]
LGTM :)

**Pull request merged**
