### PR TITLE
Pair star

### PR DESCRIPTION
**Pull request by anshika272**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

yes

### Description

Given a string S, compute recursively a new string where identical chars that are adjacent in the original string are separated from each other by a "*".
### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
issue #4735

### CODE REVIEW

**Comment by anushkrishnav** [comment]
Please run your code on CPPLinters before you push the code for review, there are around 20 + linting issues kindly fix it.
You can use this [Linter](https://cpplint.appspot.com/) if you wish.

**Comment by anshika272** [comment]
@anushkrishnav please review

**Review by iamrajiv — CHANGES_REQUESTED** [review]
@anshika272 Format your code like this

```c++
/*
"Copyright [2021] <Anshika Dubey>"
Given a string S, compute recursively a new string where identical chars that are adjacent in the original string are separated from each other by a "*".
*/

#include <bits/stdc++.h>

void pairStar(char input[]) {
	int size = 0, i;
	while (input[size] != '\0')
		size++;
	if (input[0] == '\0' || size == 0)
		return;
	if (input[0] == input[1]) {
		input[size + 1] = '\0';
		for (int i = size - 1; i >= 1; i--) {
			input[i + 1] = input[i];
		}
		input[1] = '*';
		pairStar(input + 1);
	} else {
		pairStar(input + 1);
	}
}

int main() {
	char input[100];
	std::cin.getline(input, 100);
	pairStar(input);
	std::cout << input << std::endl;
}

/*
sample input:
hello
sample output:
hel*lo

Time complexity: O(n)
*/
```

**Comment by anshika272** [comment]
@iamrajiv  please review the changes

**Review by iamrajiv — APPROVED** [review]

**Comment by anshika272** [comment]
Hey @iamrajiv @anushkrishnav the changes were approved. but the pull request is still not merged. please look into it.

**Comment by anshika272** [comment]
@anushkrishnav @iamrajiv @siddharth25pandey please review and merge my pull request.

**Comment by anushkrishnav** [comment]
Looks good to me

**Comment by anshika272** [comment]
@anushkrishnav and @iamrajiv, my score of this pull request is not visible. please kindly look into it. and level of code is also not assigned to this pull request.

**Comment by anushkrishnav** [comment]
@anshika272 done Thank you

**Pull request merged**
