### PR TITLE
Added Nearest Greater To Right Element in java.

### PR DESCRIPTION
**Pull request by AasthaGoyalgit**
### Description

I have  read all well defined guidelines , Contibuting guidelines , desciptions, Readme file .

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

I can add some more interesting java questions which can improve your project in much better way.

And also if you feel to make changes in my work . Please let me know i'll do as soon as possible.

### CODE REVIEW

**Comment by AasthaGoyalgit** [comment]
Added  commits .

**Comment by AasthaGoyalgit** [comment]
I have done pull request on #2116 .
Please review my pull request and let me know if you'll need some corrections . I'll work on them as soon as possible.

**Review by AasthaGoyalgit — COMMENTED** [review]
Added new line in EOF

**Review by HarshCasper — CHANGES_REQUESTED** [review]
Spam PR. Plenty of mistakes: 

- A Java Code is marked with `txt` extension. 
- No Markdown Updates. 
- Bad Code

**Pull request closed without merging**
