### PR TITLE
Connected Components in a graph

### PR DESCRIPTION
**Pull request by Sidhant-Gupta**
### Have you read the [Contributing Guidelines on Pull Requests]
Yes, I've read.

### Description
Added the code for the connected components in the graphs section in cpp.
Discussed the time and space complexity.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

### CODE REVIEW

**Review by atarax665 — CHANGES_REQUESTED** [review]
Format your code according to [C++ style guide](https://google.github.io/styleguide/cppguide.html).

**Comment by Sidhant-Gupta** [comment]
@atarax665  Code is already formatted. Please check it.

**Review by atarax665 — CHANGES_REQUESTED** [review]
Use proper space between operator and operands. Use proper variable names instead of alphabets like ```n, m```.

**Comment by HarshCasper** [comment]
Are you working on it @Sidhant-Gupta ?

**Comment by atarax665** [comment]
Closing the PR due to inactivity from contributor's end.

**Pull request closed without merging**
