### PR TITLE
Find GCD(Greatest Common Divisor) using Javascript

### PR DESCRIPTION
**Pull request by ashutoshraj01**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)
Yes
### Description
Finding greatest common divisor(GCD) of two numbers in Javascript.
(Write your answer here.)

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)
#5035

### CODE REVIEW

**Review by HarshCasper — CHANGES_REQUESTED** [review]
Make Markdown changes

**Comment by ashutoshraj01** [comment]
Hey Harsh, Need your little help. How to do markdown changes?

**Comment by HarshCasper** [comment]
> Hey Harsh, Need your little help. How to do markdown changes?

Just go to the Language README.md and add a hyperlink for your code

**Review by ankitaggarwal23 — COMMENTED** [review]
Are you still working on it.

**Comment by ashutoshraj01** [comment]
Yes Ankit

**Review by ankitaggarwal23 — COMMENTED** [review]
Found same Pr opened by you. Closing this PR.

**Pull request closed without merging**
