### PR TITLE
Singly Linked List Implementation in C

### PR DESCRIPTION
**Pull request by Sohailsaifi**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Added Implementation of Singly Linked List in C.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#400

### CODE REVIEW

**Review by siddharth25pandey — APPROVED** [review]
@Sohailsaifi Looks fine to me, only some addition is required.
* Add the topic in README file

**Review by Kajol-Kumari — COMMENTED** [review]
@Sohailsaifi Well formated :) 
please add one sample input/outpiut below code section in commented form and incorporate the changes suggested by @siddharth25pandey . It will be good to go then :)

**Comment by Sohailsaifi** [comment]
> @Sohailsaifi Looks fine to me, only some addition is required.
> *Add the topic in README file

Done. Updated the README file

**Comment by Sohailsaifi** [comment]
> @Sohailsaifi Well formated :)
> please add one sample input/outpiut below code section in commented form and incorporate the changes suggested by @siddharth25pandey . It will be good to go then :)

Thanks :) 
Changes Done.

**Review by Kajol-Kumari — APPROVED** [review]
LGTM :)

**Review by siddharth25pandey — APPROVED** [review]
@Sohailsaifi Looks fine to me
Able to merge.
Thanks!

**Comment by atarax665** [comment]
Resolve merge conflict ASAP so that I can merge this PR.

**Review by atarax665 — APPROVED** [review]

**Comment by Sohailsaifi** [comment]
> Resolve merge conflict ASAP so that I can merge this PR.

Done.

**Pull request merged**
