### PR TITLE
Added code for finding maximum number formed from the given array of 2-digit numbers

### LINKED ISSUE #5000: Maximum number formed from the combinations of two digit numbers given as input by the user
## 💥 Proposal

Maximum number formed from the combinations of two digit numbers given as input by the user in C++
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

### PR DESCRIPTION
**Pull request by SAY-droid427**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Added code for finding maximum number formed from the given array of 2-digit numbers in C++

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Fixes https://github.com/TesseractCoding/NeoAlgo/issues/5000

### CODE REVIEW

**Review by gat786 — APPROVED** [review]

**Comment by gat786** [comment]
Thanks for contributing :-)

**Comment by HarshCasper** [comment]
Please make an issue here and raise a PR, for an article as part of our Docs repository: https://github.com/TesseractCoding/NeoAlgo-Docs

It would be much appreciated. Thanks!

**Comment by SAY-droid427** [comment]
@HarshCasper I didn't understand what you meant . I have to create an issue here and raise a PR ? What should the issue be about?

**Comment by HarshCasper** [comment]
> @HarshCasper I didn't understand what you meant . I have to create an issue here and raise a PR ? What should the issue be about?

Adding the documentation for the Code.

**Pull request merged**
