### PR TITLE
Dijkstras Algorithm in Python

### PR DESCRIPTION
**Pull request by mursalfk**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Dijkstra's Algorithm is a graph search algorithm that solves the single-source shortest path problem for a graph with non-negative edge path costs, producing a shortest-path tree. This is an algorithm for finding the shortest paths between nodes in a graph, which may represent, for example, road networks...
- First of all, I have imported the matplotlib library's pyplot as plt along with networkx as nx
- Then I have introduced Nodes and Edges to create a network along with printing them resp[ectively for a better understanding at runtime
- There are two graphs in the code, one being a normal one, while the latter has Dijkstra's algorithm implemented
- And at the end, the code shows the shortest path to reach the destination from the starting point using dijkstra_path

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

### CODE REVIEW

**Comment by mursalfk** [comment]
@gat786

**Review by mursalfk — COMMENTED** [review]
corrected

**Comment by gat786** [comment]
Can you give a description of what you have implemented here in the top message where you started this PR.

**Comment by mursalfk** [comment]
> Can you give a description of what you have implemented here in the top message where you started this PR.

@gat786 updated ^^^

**Comment by gat786** [comment]
It still doesn't say what you have implemented in this pr. It simply says definition of djikstras algorithm

**Review by mursalfk — COMMENTED** [review]
Corrected the code

**Comment by mursalfk** [comment]
> It still doesn't say what you have implemented in this pr. It simply says the definition of djikstras algorithm

Done @gat786

**Review by gat786 — APPROVED** [review]
This looks great Mursal. 👍

**Pull request merged**
