### PR TITLE
Sieve eratosthenes in Go

### PR DESCRIPTION
**Pull request by BeAgarwal**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes, I have read the guidelines.

### Description

Completed sieve of eratosthenes 

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#2471

### CODE REVIEW

**Review by siddharth25pandey — CHANGES_REQUESTED** [review]
@BeAgarwal Add comments between the codes

**Comment by BeAgarwal** [comment]
> @BeAgarwal Add comments between the codes

Done

**Review by siddharth25pandey — APPROVED** [review]
@BeAgarwal LGTM, able to merge

**Comment by siddharth25pandey** [comment]
@all-contributors please add @BeAgarwal for his code

**Pull request merged**
