### PR TITLE
Added a program for Fast exponentiation of a number using Bit Masking

### PR DESCRIPTION
**Pull request by anushkasethi1710**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

### CODE REVIEW

**Review by HarshCasper — CHANGES_REQUESTED** [review]
Few changes: 
- Add a beginner-friendly description about your Code at the top
- Add description of functions 
- Add a new line at the EOF 
- Add sample I/O at the end of the Code
- Add complexity at the end of the code
- Use a Code formatter to format the Code

**Comment by anushkasethi1710** [comment]
Hi @HarshCasper :) I'll gladly make the required changes, it would be great if you could guide me on how to do so on visual studio code? I don't really know what a code formatter is. Thanks

**Comment by HarshCasper** [comment]
> Hi @HarshCasper :) I'll gladly make the required changes, it would be great if you could guide me on how to do so on visual studio code? I don't really know what a code formatter is. Thanks

Follow [this](https://code.visualstudio.com/docs/cpp/config-clang-mac)

**Comment by anushkasethi1710** [comment]
> > Hi @HarshCasper :) I'll gladly make the required changes, it would be great if you could guide me on how to do so on visual studio code? I don't really know what a code formatter is. Thanks
> 
> Follow [this](https://code.visualstudio.com/docs/cpp/config-clang-mac)

Hey! This doesn't mention anything about a code formatted for windows

**Comment by HarshCasper** [comment]
> > > Hi @HarshCasper :) I'll gladly make the required changes, it would be great if you could guide me on how to do so on visual studio code? I don't really know what a code formatter is. Thanks
> > 
> > 
> > Follow [this](https://code.visualstudio.com/docs/cpp/config-clang-mac)
> 
> Hey! This doesn't mention anything about a code formatted for windows

You can follow the next links to see how to do the same on Microsoft/GNU-Linux or whatever OS you use.

**Pull request closed without merging**
