### PR TITLE
Updated README.md

### PR DESCRIPTION
**Pull request by Yash-Thakare22**
Updated Reverse a LINKED LIST in README file in C language

### CODE REVIEW

**Review by anushkrishnav — CHANGES_REQUESTED** [review]
File not found . Check it once again

**Comment by Yash-Thakare22** [comment]
@iamrajiv  have told me to update README for the above file ie Reversing a Linked List in C

**Comment by iamrajiv** [comment]
@YashThakare do not make a new PR for every commit you can commit the changes in the same PR i.e. #375

**Comment by Yash-Thakare22** [comment]
I will not to so . But add my file Reverse_linked_list in C language please @iamrajiv

**Comment by iamrajiv** [comment]
@YashThakare do not make a new PR to update the readme you can commit the changes in the same PR i.e. #375

**Pull request closed without merging**
