### PR TITLE
Recursive buuble sort code

### PR DESCRIPTION
**Pull request by ghost**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

yes

### Description

Its a code for recursive bubble sort

### Checklist

- [X] I've read the contribution guidelines.
- [X] I've checked the issue list before deciding what to submit.
- [X] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

### CODE REVIEW

**Comment by ghost** [comment]
@HarshCasper @Kajol-Kumari @iamrajiv 
have a look at that I have contributed for hakin codes please tell if theirs an issue

**Comment by ghost** [comment]
@atarax665 @HarshCasper 
why this Abhinav Anand name is coming in this as a participant even I have done this code please can u tell me

**Comment by atarax665** [comment]
> @atarax665 @HarshCasper
> why this Abhinav Anand name is coming in this as a participant even I have done this code please can u tell me

Your last merged PR (#384 ) was from the same branch (master) and I (Abhinav Anand) refactored your code before merging, that is why it has my name as a participant. This shows that your forked repo is not even with the source. I will advice you to create a new branch whenever working on a new issue and keep your repo updated.

**Comment by atarax665** [comment]
I am closing this PR as it violated Rule 7 of #398 . @HarshAgarwal-DEV Please create a new branch to raise this PR. It will only be reviewed then.

**Comment by HarshAgarwal-DEV** [comment]
@atarax665 
last time @iamrajiv  said that there is a problem with the bot it's not merging my branch  so what I can do now

**Comment by HarshAgarwal-DEV** [comment]
@atarax665 
its not my fault man now if my branch is not merged just because of the bot now what I have to do

**Pull request closed without merging**
