### PR TITLE
BASIC DS IN PYTHON

### PR DESCRIPTION
**Pull request by sujal111**
Please read [how to contribute](CONTRIBUTING.md) first!
# Description
Submission description here

Checklist
* [x] I've checked the issue list __BEFORE__ deciding what to submit
* [x] I've read the contribution guidelines
* [x] I've edited the README.md link to my code

## Don't forget to visit our [website](http://www.tesseractcoding.tech)!

Feel free to add this badge after your submission is accepted!

```
<a href=https://github.com/TesseractCoding/NeoAlgo>
   <img src=https://img.shields.io/badge/NeoAlgo-Contributor-brightgreen>
</a>
```

### CODE REVIEW

**Review by mar-galho — CHANGES_REQUESTED** [review]
Hi! Thanks a lot for the great contribution!

Could you check the file structure and read the instructions to fix your PR, placing the files under the right folders and updating the necessary links? Thanks a lot!

**Comment by sujal111** [comment]
I have updated
It would be a great help if you plzzzzzzzzz check.

**Comment by mar-galho** [comment]
The changes didn't fix the issues. Could you please fix this so we can merge it?

**Comment by mar-galho** [comment]
PR Closed. Once the conflicts are resolved, please submit a new PR - make sure to pull/rebase first!

**Pull request closed without merging**
