### PR TITLE
Add bfs

### PR DESCRIPTION
**Pull request by muthuannamalai12**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?
Yes
(Write your answer here.)

### Description
Added Graph traversal algorithm of Breadth-First Search in C.

(Write your answer here.)

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
#1725 

(Write your answer here.)

### CODE REVIEW

**Comment by muthuannamalai12** [comment]
@iamrajiv. Please Review

**Review by srimanikantapalakollu — CHANGES_REQUESTED** [review]
I found the same issue as discussed in the DFS code. please verify and submit the PR again.

**Comment by muthuannamalai12** [comment]
@srimani-programmer.Can I open a new pull request by closing this

**Comment by muthuannamalai12** [comment]
Thank you @srimani-programmer sir for your review
I am making a new Pr by closing this Pr
Pr no: #1908. Kindly review it

**Pull request closed without merging**
