### PR TITLE
shaker sort in c

### PR DESCRIPTION
**Pull request by riyalamba07**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?
yes

### Description

Implementing shaker sort in C . 
The user needs to give size of the array , elements of the array and order in which the array needs to be sorted .
The algorithms will then sort the array using bubble sort in forward as well as backward direction.
 It will display the sorted array as well as the computation time in output console.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
issue #4073

### CODE REVIEW

**Comment by anushkrishnav** [comment]
Edit the relevant readme file and add the link to your file.

**Comment by riyalamba07** [comment]
Can you tell me the steps to do it? How to add a readme file only for
my code?

**Review by ankitaggarwal23 — COMMENTED** [review]
Read the instructions mentioned on Gssoc discord yesterday. Do the changes as per that.

**Review by ankitaggarwal23 — COMMENTED** [review]
Closing this due to inactivity. Thank you for your valuable time.😊

**Pull request closed without merging**
