### PR TITLE
Binary Search Algorithm in C

### PR DESCRIPTION
**Pull request by kulsoomzahra**
Binary Search Algorithm in C

### CODE REVIEW

**Review by ashwanisng — CHANGES_REQUESTED** [review]
please add the link of the program in the readme 👍

**Comment by mar-galho** [comment]
We really appreciate your contributions!

I'd just suggest that the next time you contribute to our repo, please make sure to add a better description of your contribution in the title of your pull request, this will help us to keep things organized! Thanks!

**Review by mar-galho — CHANGES_REQUESTED** [review]
Add link to README.md file and fix filename

**Comment by mar-galho** [comment]
@kulsoomzahra

**Comment by kulsoomzahra** [comment]
> Add link to README.md file and fix file
Sorry for late response . Is it fine now?

**Comment by mar-galho** [comment]
No problem! Since we've changed the structure, let me add the README.md link myself! Thanks for your submission :)

@all-contributors please add @kulsoomzahra for code

**Review by mar-galho — APPROVED** [review]

**Comment by mar-galho** [comment]
@all-contributors please add @kulsoomzahra for code

**Pull request merged**
