### PR TITLE
Decimal to binary conversion

### LINKED ISSUE #6605: Positive decimal to binary in Python
## 💥 Proposal

To add a program for conversion of a positive decimal number into its binary equivalent.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

### PR DESCRIPTION
**Pull request by tanvi355**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description
Added a program to convert decimal number into its binary equivalent

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Fixes #6605

### CODE REVIEW

**Review by ankitaggarwal23 — COMMENTED** [review]
We don't accept such code. It falls neither as a Data Structure not as an algorithm.

**Comment by tanvi355** [comment]
@atarax665 please merge this PR so that I can update the credits on NeoAlgo-Docs for this [article](https://github.com/TesseractCoding/NeoAlgo-Docs/pull/459)

**Review by atarax665 — APPROVED** [review]
Resolve Merge conflict

**Comment by tanvi355** [comment]
> Resolve Merge conflict

done! @atarax665

**Comment by tanvi355** [comment]
labels ? @atarax665

**Pull request merged**
