### PR TITLE
C program for recursion

### PR DESCRIPTION
**Pull request by AakritiKinra**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

yes

### Description

C program to determine the recursion count of substring

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#1086

### CODE REVIEW

**Comment by AakritiKinra** [comment]
I tried to edit the readme but failed to do so. can you guide me as to how it is supposed to be done

**Review by Kajol-Kumari — CHANGES_REQUESTED** [review]
@AakritiKinra please add this file path in `readme.md`

**Comment by AakritiKinra** [comment]
how can I edit it? can you please guide me about the same?

**Comment by iamrajiv** [comment]
@AakritiKinra Go to this link https://github.com/AakritiKinra/NeoAlgo/blob/patch-3/C/README.md and edit the README file by adding the link of the program. Also, update the name of the program it should be `recursion_string.c`.

**Comment by AakritiKinra** [comment]
I have made the requested changes. Thank you for the help.

**Review by siddharth25pandey — APPROVED** [review]
@AakritiKinra Good to go
Able to merge
Thanks!

**Review by iamrajiv — CHANGES_REQUESTED** [review]
@AakritiKinra Your code `recursion_string.c ` is not in the proper location it should be in `c/other` directory.

**Comment by AakritiKinra** [comment]
I've changed it

**Review by iamrajiv — APPROVED** [review]

**Pull request merged**
