### PR TITLE
Cocktail Sort in Java

### PR DESCRIPTION
**Pull request by ritvij14**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?
Yes
(Write your answer here.)

### Description
This is code for Cocktail Sort in Java, which is an optimized form of the Bubble Sort Algorithm. In this case, we traverse the array in both directions in one iteration of the loop.
(Write your answer here.)

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
Issue #925 
(Write your answer here.)

### CODE REVIEW

**Comment by ritvij14** [comment]
@iamrajiv @plazzy99 @siddharth25pandey @Kajol-Kumari please review this.

**Comment by ritvij14** [comment]
Also, there is a problem, in Java `README` file, all `Sorting` algorithms have gone under a repeated `Competitive programming` heading.
Should I create a new issue for it?

**Review by iamrajiv — APPROVED** [review]

**Comment by iamrajiv** [comment]
@ritvij14 Yeah, refactor Java README file in this PR only.

**Comment by ritvij14** [comment]
@iamrajiv I have done the refactoring, please have a look just to check that all is fine.

**Review by iamrajiv — CHANGES_REQUESTED** [review]
@ritvij14 I have formatted the README a little bit. Update like this
```md
<p align="center">
    <img src="../img/neo_algo.png"><br>
    <img src="https://img.shields.io/github/license/tesseractcoding/neoalgo?style=flat">
    <a href="http://makeapullrequest.com" target="_blank"><img src="https://img.shields.io/badge/PRs-welcome-brightgreen.svg?style=flat" alt="PRs Welcome"></a>
    <img alt="GitHub pull requests" src="https://img.shields.io/github/issues-pr/tesseractcoding/neoalgo">
    <img alt="GitHub issues" src="https://img.shields.io/github/issues/tesseractcoding/neoalgo">
    <img alt="Github All Contributors" src="https://img.shields.io/github/all-contributors/tesseractcoding/neoalgo">
</p>

# Codes in the Java language

## Algorithms

- [Kadane's Algorithm](Algorithms/kadanes_Java.java)

## Greedy Algorithms

- [Activity Selection](Greedy_Algorithms/Active_Selection.java)

## Blockchain

_add list here_

## Competitive programming

- [Aggressive Cows](cp/AggressiveCows.java)
- [Count The Reversals](cp/Count_The_Reversals.java)
- [Merge Overlaping Subintervals](cp/MergeOverlappingArray.java)
- [Rabin Karp Algorithm](cp/Rabin_Karp.java)
- [Remove Duplicate Element from an array using extra space](cp/RemoveDuplicateElement.java)
- [Remove Duplicate Element Without using Extra Space](cp/RemoveDuplicateElementWithoutExtraSpace.java)
- [Spiral Matrix](cp/Spiral_Matrix.java)
- [Target Sum Triplets](cp/target_sum_triplets.java)

## Cryptography

- [Caesar Cipher](cryptography/ceaserCipher.java)

## Dynamic Programming

- [Coin Change Problem Using DP](dp/CoinChangeUsingDp.java)
- [Kandane Algorithm](dp/Kadane_Algorithm.java)

## Data Structures

- [Binary Tree](ds/Binary_Tree.java)
- [Detect Loop in Linked List](DetectLoopLL.java)
- [Matrix Sorting](ds/MatrixSorting.java) master
- [Queue Basic Functionalities](ds/queue.java)
- [Implementation of Queue using stack & vice-versa](ds/QueueandStack.java)
- [Queue](ds/Queuell.java)
- [Segment Tree](ds/SegmentTree.java)
- [Sparse Matrix](ds/SparseMatrix.java)
- [Stack ~ Linked List Implementation](ds/Stack.java)
- [Stack](ds/Stackll.java) Implementation-of-queue-using-stack
- [Linked List](ds/linkedList.java)
- [Linked List ~ Reverse](ds/linkedListReverse.java)
- [Tree Traversal(postorder traversal)](ds/postorder_Traversal.java)

## Graphs

- [Breadth First Search](graphs/BFS.java)
- [Depth First Search](graphs/DFS.java)
- [Dijkstra's Algorithm](graphs/Dijkstra.java)
- [Kruskal's Algorithm](graphs/Kruskal_Algorithm.java)
- [Level Order Traversal of a Binary Tree Using Priority Queue](graphs/LevelOrderTraversalInQueue.java)
- [Prim's Algorithm](graphs/Prim_Algorithm.java)

## Mathematics

- [Count Number Of Digits](math/countDigits)
  - [Iterative](countDigits/iterative.java)
  - [Recursive](countDigits/recursive.java)
  - [String Method](countDigits/stringmethod.java)
- [Binary Exponentiation](math/Binary_Exponentiation.java)
- [Complex numbers](math/Complex.java)
- [Extended Euclid Algorithm](math/ExtendedEuclidAlgo.java)
- [Segmented_Sieve](math/Segmented_Sieve.java)
- [Sieve of Atkin](math/sieveOfAtkin.java)
- [Sieve of Eratosthenes](math/SieveOfEratosthenes.java)
- [Double Factorial](math/DoubleFactorial.java)

## Searching

- [Binary Search](search/Binary_search.java)
- [Interpolation Search](search/Interpolation_search.java)
- [Linear Search](search/Linear_search.java)
- [Manacher's Algorithm](search/ManacherAlgorithm.java)
- [Stack Search](search/Stack_Search.java)
- [Jump Search](search/jumpSearch.java)

## Sorting

- [BeadSort](sort/BeadSort.java)
- [Bubble Sort](sort/BubbleSort.java)
- [Bucket Sort](sort/BucketSort.java)
- [Cocktail Sort](sort/CocktailSort.java)
- [Heap Sort](sort/HeapSort.java)
- [Insertion Sort](sort/InsertionSort.java)
- [Merge Sort](sort/Merge_sort.java)
- [Minimum number of swaps to sort an array of N unordered consecutive integers](sort/MinimumSwapsForNIntegers.java)
- [Optimized Bubble Sort](sort/OptimizedBubbleSort.java)
- [PancakeSort](sort/PancakeSort.java)
- [Quick Sort](sort/QuickSort.java)
- [Selection Sort](sort/SelectionSort.java)

## Machine Learning

_add list here_

## Other

- [Find first missing positive number](other/FirstMissingPositiveNumber.java)
- [First non-repeating character in a string](other/FirstNonRepeatingChar.java)
- [Merge 2 Sorted arrays in O(1) extra space](other/MergeSortedArrays.java)
- [Tower of Hanoi problem](other/TowerOfHanoi.java)

```

**Comment by ritvij14** [comment]
@iamrajiv sir done.

**Review by iamrajiv — APPROVED** [review]

**Comment by ritvij14** [comment]
Just a small fix, I saw that in Heap sort, the class name was mistakenly kept as Bucket Sort, so I changed it.
It was from one of my previous PRs, so I am sorry about that :sweat_smile:

**Review by vatsalkesarwani12 — APPROVED** [review]

**Comment by vatsalkesarwani12** [comment]
> Just a small fix, I saw that in Heap sort, the class name was mistakenly kept as Bucket Sort, so I changed it.
> It was from one of my previous PRs, so I am sorry about that 😅

but from next time don't merge another issue in one pr.
always open a new pull request

**Review by atarax665 — APPROVED** [review]
Nice work. LGTM :)

**Pull request merged**
