### PR TITLE
Armstrong number

### PR DESCRIPTION
**Pull request by sukritidawar**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

#1217 

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

### CODE REVIEW

**Comment by sukritidawar** [comment]
@iamrajiv @Kajol-Kumari @siddharth25pandey please review.

**Review by iamrajiv — CHANGES_REQUESTED** [review]
@sukritidawar Format your code according to PEP 8 rules. You can refer to this http://pep8online.com/.

**Review by siddharth25pandey — APPROVED** [review]
@sukritidawar Clean code
Able to merge
Thanks!

**Review by Kajol-Kumari — APPROVED** [review]
Codewise Looks good to me!

**Pull request merged**
