### PR TITLE
Smallest and longest Substring of given length in java

### LINKED ISSUE #6089: smallest and longest Substring of given length
## 💥 Proposal

(A clear and concise description of what the proposal is to find smallest and largest Substring of given length with java.  The smallest substring should start from initial alphabetic character and largest substring should start from last character of alphabet in given string.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

### PR DESCRIPTION
**Pull request by RuchiGitHu**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

finding two substring. One will be shortest substring as the substring will start from smallest(initial character of alphabets) character from string, similarly for largest substring, the substring will start from largest(end most character of alphabets) character from string.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

fixes #6089

### CODE REVIEW

**Comment by RuchiGitHu** [comment]
> ### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?
> Yes
> 
> ### Description
> finding two substring. One will be shortest substring as the substring will start from smallest(initial character of alphabets) character from string, similarly for largest substring, the substring will start from largest(end most character of alphabets) character from string.
> 
> ### Checklist
> * [x]  I've read the contribution guidelines.
> * [x]  I've checked the issue list before deciding what to submit.
> * [x]  I've edited the `README.md` and link to my code.
> 
> ## Related Issues or Pull Requests
> fixes #6089

Please review my PR @HarshCasper @ankitaggarwal23 @siddharth25pandey @atarax665 @bhav09

**Review by ankitaggarwal23 — CHANGES_REQUESTED** [review]
This is not a cp problem. Add this in appropriate section also Read the instructions mentioned on Gssoc discord yesterday. Do the changes as per that. 

Is this largest or longest substring kindly make it same

**Comment by RuchiGitHu** [comment]
> This is not a cp problem. Add this is appropriate section also Read the instructions mentioned on Gssoc discord yesterday. Do the changes as per that.
> 
> Is this largest or longest substring kindly make it same

Please review @ankitaggarwal23, I have updated as requested by you...

**Comment by RuchiGitHu** [comment]
Please review my PR, I have done the changes and waited for atleast more then 24 hours for next review, kindly look into it. @bhav09 @atarax665 @ankitaggarwal23

**Review by HarshCasper — APPROVED** [review]

**Pull request merged**
