### PR TITLE
Golang Algorithms

### PR DESCRIPTION
**Pull request by fomalhauting**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Golang Algorithms

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Issue Number - #1579

### CODE REVIEW

**Comment by fomalhauting** [comment]
@shraddhavp, Hey can you take a look?

**Comment by fomalhauting** [comment]
@shraddhavp Can you take a look?

**Comment by HarshCasper** [comment]
Hi @itsIapetus 

Can you please break down this PR into multiple other PRs? It is difficult to review multiple code pushed into a single PR and merging the same. 

Do let me know if that works. Thanks!

**Comment by atarax665** [comment]
@itsIapetus You can make individual PRs.

**Pull request closed without merging**
