### PR TITLE
Added Arctan Algorithm

### PR DESCRIPTION
**Pull request by XZANATOL**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

- [x] Yes

### Description

Added Arctan Algorithm.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

This pull request resolves issue: #3437

### CODE REVIEW

**Review by iamrajiv — CHANGES_REQUESTED** [review]
@XZANATOL Format your code according to PEP 8 rules, check your code here http://pep8online.com/.

**Comment by XZANATOL** [comment]
@iamrajiv Done most of the requested, but I think it's better to leave the comments in the last without splitting them into multiple lines so to be easily read, or is it better to split them? tell me what you think.

**Comment by XZANATOL** [comment]
I'm although interested about other types of code formats (if exist)

Is PEP 8 the format that the whole repository use?

What other formats that exist?

**Review by HarshCasper — APPROVED** [review]

**Comment by iamrajiv** [comment]
@all-contributors please add @XZANATOL for his code

**Pull request merged**
