### PR TITLE
Added adjacent element product problem solution

### PR DESCRIPTION
**Pull request by tanvi355**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)
Yes
### Description

(Write your answer here.)
Added the solution for adjacent elements product problem in Java. 
### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)
#2250

### CODE REVIEW

**Comment by tanvi355** [comment]
@siddharth25pandey @atarax665 please review the PR .

**Review by HarshCasper — CHANGES_REQUESTED** [review]
Make Markdown updates. Good to merge then

**Comment by tanvi355** [comment]
Made the updates

**Review by HarshCasper — APPROVED** [review]

**Comment by HarshCasper** [comment]
@all-contributors bot please add @tanvi355 for code

**Pull request merged**
