### PR TITLE
queue using array in cpp

### PR DESCRIPTION
**Pull request by pragyajaiswa05l**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

yes

### Description

Created a generic queue with all its basic functionality in cpp.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#419

### CODE REVIEW

**Comment by pragyajaiswa05l** [comment]
@Kajol-Kumari @SKAUL05 @Abhijit2505 @plazzy99 @siddharth25pandey 
please review my PR .

**Review by siddharth25pandey — CHANGES_REQUESTED** [review]
@pragyajaiswa05l  Please make following modifications
* The Program interface should be user-friendly
* Take input from user side by printing proper message regarding operation
* Choice for exit option in the Program
* Heading same as the topic is required in top of the Program while Executing.
* No need of giving Sample Input & output

**Review by siddharth25pandey — CHANGES_REQUESTED** [review]
@pragyajaiswa05l  You have not got my point. Please make the required modification as listed in the previous comment.
Also you can take help from [this](https://github.com/TesseractCoding/NeoAlgo/pull/416/files#diff-2191868b7ea37fb10060ed3bd3898b8b)

**Comment by pragyajaiswa05l** [comment]
@siddharth25pandey  kindly review it .
.

**Review by siddharth25pandey — CHANGES_REQUESTED** [review]
@pragyajaiswa05l Looks better than previous, but still need some modifications
* User interface should be more friendly, if user don't know what is dequeue & enqueue in line number 88. So, instead of these, please simply write the message as Insertion/deletion/ display, etc.
* Also, if user enter any operation, then it must shows some message like "Insertion is Successful"
Do the same for all operation.
* Also remove extra blank lines as it consumes more space. example line number 2,5,13,etc

**Comment by pragyajaiswa05l** [comment]
@siddharth25pandey  please review the changes.

**Review by siddharth25pandey — CHANGES_REQUESTED** [review]
@pragyajaiswa05l  Some more modifications required
* Avoid spelling mistake in line number 82
* In enqueue, please show message after insertion same as what you have done in dequeue
* Also for exit operation you are saying user to enter 6 as choice & doing execution for choice number -1

**Comment by pragyajaiswa05l** [comment]
@siddharth25pandey  Execution  message should be before or after ? As in enqueue it was after inserting the element and in dequeue it was before deleting the element.
please clarify it.

**Comment by siddharth25pandey** [comment]
> @siddharth25pandey Execution message should be before or after ? As in enqueue it was after inserting the element and in dequeue it was before deleting the element.
> please clarify it.

@pragyajaiswa05l 
For Enqueue, insert the success message after line number 87

**Comment by pragyajaiswa05l** [comment]
@siddharth25pandey  please review it . Made the following changes as directed by you.

**Review by siddharth25pandey — APPROVED** [review]
@pragyajaiswa05l Looks fine to me.
Able to merge.
Thanks!

**Review by SKAUL05 — APPROVED** [review]

**Comment by pragyajaiswa05l** [comment]
@plazzy99 please review it.

**Review by Kajol-Kumari — APPROVED** [review]
LGTM :)

**Comment by iamrajiv** [comment]
@all-contributors please add @pragyajaiswa05l for code

**Pull request merged**
