### PR TITLE
Added count triplets in python

### PR DESCRIPTION
**Pull request by Aanchi-glitch2744**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes
### Description

Added program to count all the triplets in a list such that sum of two elements equals the third element.
### Checklist

- [X] I've read the contribution guidelines.
- [X] I've checked the issue list before deciding what to submit.
- [X] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Issue: #815

### CODE REVIEW

**Review by atarax665 — APPROVED** [review]
LGTM :)

**Review by iamrajiv — APPROVED** [review]

**Review by siddharth25pandey — APPROVED** [review]
@Aanchi-glitch2744 Good to go
Able to merge
Thanks!

**Comment by siddharth25pandey** [comment]
@all-contributors please add @Aanchi-glitch2744 for his/her code

**Comment by iamrajiv** [comment]
@all-contributors please add @Aanchi-glitch2744 for code

**Pull request merged**
