### PR TITLE
Sorting algorithms written in golang

### PR DESCRIPTION
**Pull request by PaulSayantan**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?
Yes

### Description

__Sorting Algorithm__ implementation in Golang
* Bubble Sort
* Counting Sort
* Insertion Sort
* Merge Sort
* Quick Sort
* Selection Sort

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

### CODE REVIEW

**Comment by PaulSayantan** [comment]
@atarax665 @SKAUL05 @HarshCasper please review this PR at your convenience !!
also mention if this needs any improvement

**Comment by PaulSayantan** [comment]
@HarshCasper @iamrajiv @atarax665 this contribution is still not getting reviewed, please suggest any changes if required !!

**Review by iamrajiv — APPROVED** [review]
@belikesayantan LGTM! Hope the code follows `gofmt` format if not you can refer this https://play.golang.org/.

**Review by atarax665 — CHANGES_REQUESTED** [review]
Add sample Input/output, space and time complexity in the end of every program in commented form.

**Review by PaulSayantan — COMMENTED** [review]
changes added

**Review by atarax665 — APPROVED** [review]
LGTM :)

**Review by vatsalkesarwani12 — APPROVED** [review]

**Comment by iamrajiv** [comment]
@all-contributors please add @belikesayantan for code

**Pull request merged**
