### PR TITLE
Longest Increasing Subsequence problem using DP in JavaScript

### PR DESCRIPTION
**Pull request by noob-26**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes
### Description
Solution to the Longest Increasing Subsequnce problem using Dynamic  Programming in JavaScript
Time Complexity : O(N^2)
Space Complexity : O(N)

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Issue related to this PR is #2204

### CODE REVIEW

**Review by HarshCasper — CHANGES_REQUESTED** [review]
Few changes: 

- Use Dynamic Input instead of Static Input
- Add a pitch on your Code about the Algorithm 
- Add sample I/O

**Comment by noob-26** [comment]
I updated the code to include the changes you mentioned.

**Comment by FireQueen-3010** [comment]
I would like to contribute Longest Increasing Subsequence Problem in Java. Please assign this to me!

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

**Review by HarshCasper — CHANGES_REQUESTED** [review]
Few changes: 
- Modularize the beginner pitch. Its tough to read. Use short and justified lines for better readability.
- Shift Time and Space Complexity at the end of the Code. 
- Create short comments. We don't need comments for which we have to scroll much.
- Add a new line at the EOF

**Comment by noob-26** [comment]
@HarshCasper I updated the code. Please review the changes I made.

**Review by HarshCasper — APPROVED** [review]

**Pull request merged**
