### PR TITLE
Added C programs.

### PR DESCRIPTION
**Pull request by proghead00**
People who are visiting this repository have a common purpose - to get most of the popular and well-used data structures and algorithms. The programs I am adding are very popular and are common interview and competitive questions. They will get a tonne of benefits from this.
 
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)
Yes, I have.
### Description

(Write your answer here.)
I have included several C programs that fall under mathematical problems, and data structures too. I have placed the files in respect to their correct folders.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)
I'll be opening more PRs with different branches, where I'll submit programs in other languages as well.

### CODE REVIEW

**Comment by proghead00** [comment]
@HarshCasper kindly look at it :)

**Comment by HarshCasper** [comment]
Hello @proghead00 

I appreciate the PR and your Contribution. Can you please break down this PR into multiple separate PRs because that makes it easy for us to review them and subsequently score them. 

Thanks!

**Comment by proghead00** [comment]
@HarshCasper so, you want me to create each branch for a PR? Because I already opened it, and as I said earlier, I would open separate PRs for separate programming languages.

**Comment by HarshCasper** [comment]
> @HarshCasper so, you want me to create each branch for a PR? Because I already opened it, and as I said earlier, I would open separate PRs for separate programming languages.

No, I did not mean to say that. I mentioned to create separate PR for every Code you push. As you see, every commit should correspond to something logical and PRs are meant to keep these logical changes compact and easy to review. 

Now in your case, multiple files have been changed, which makes the review process harder. Also it would be detrimental for you, as you will not be given extra scores for every code you push, since you are doing that via a single large PR.

Take a look at how other PRs have been merged and you will be better able to understand. Also you don't have a corresponding Issue. Please keep in mind that the lack of an Issue would simply mean that any of us can close the PR with no warning.

**Pull request closed without merging**
