### PR TITLE
Added link to the Merging two Linked List using c

### PR DESCRIPTION
**Pull request by saimanoharhm**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)
yes
### Description

(Write your answer here.)
I have added link to Merging two Linked List using c in  readme.md file
### Checklist

- [yes ] I've read the contribution guidelines.
- [ yes] I've checked the issue list before deciding what to submit.
- [ yes] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)
#2171

### CODE REVIEW

**Comment by saimanoharhm** [comment]
@gat786 Could you pls review my PR

**Comment by HarshCasper** [comment]
Thanks for making your Pull Request!

PRs would be reviewed after the start of the Coding Period. Thanks!

**Review by atarax665 — CHANGES_REQUESTED** [review]
Update README in PR #2197 itself.

**Comment by saimanoharhm** [comment]
> Update README in PR #2197 itself.

@atarax665 Could you pls guide me how to do that. How to update readme file #2197 itself

**Comment by HarshCasper** [comment]
@saimanoharhm 

I would ask you to go through Git & Github tutorials first. Its no hard feat to go over to your branch, update the README profile and make a commit. 

I will close this PR and would request you to continue your work on your original PR.

**Pull request closed without merging**
