### PR TITLE
Himanshi2997

### PR DESCRIPTION
**Pull request by Himanshi2997**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Program in C++ to multiply two matrices

### Checklist

- [] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

### CODE REVIEW

**Review by ankitaggarwal23 — COMMENTED** [review]
Problem already present

**Comment by Himanshi2997** [comment]
Sorry for the inconvenience sir I was trying to make a pull request to
issue #5870 but it has been made separately as #5997.

This is my first pull request, I tried following the steps in the
contributing file but it looks like I made some mistake. I have already
made a commit to the forked repo for #5870 .

Kindly reopen issue "product of matrices" #5870, so that I can send another
pull request to it or should I make a new issue for the same?
Please advise. Thank you

**Comment by ankitaggarwal23** [comment]
No someone already did the problem you can choose another issue

**Comment by Himanshi2997** [comment]
Ok, thank you.

**Pull request closed without merging**
