### PR TITLE
Minimun no swaps required

### PR DESCRIPTION
**Pull request by agamgupta2015**
#4517 issue resolved

### CODE REVIEW

**Comment by agamgupta2015** [comment]
Thanks for Assigning the issue

**Review by iamrajiv — CHANGES_REQUESTED** [review]
@agamgupta2015 Please add an extension to the program. Also, update the readme file.

**Comment by agamgupta2015** [comment]
I have Updated readme and added extension

**Review by ankitaggarwal23 — CHANGES_REQUESTED** [review]
@agamgupta2015 Kindly save your file in `.cpp extension` not in .txt also Readme.md file update  missing. We are not reviewing incomplete PR kindly do the changes in a new PR. Closing this as of now.

**Pull request closed without merging**
