### PR TITLE
Implementation of Interpolation Search in C Language

### PR DESCRIPTION
**Pull request by yashaswibiyahut**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

**Yes**

### Description
_Issue Number =#451._
The Interpolation Search is an improvement over Binary Search.
Implemented this algorithm in C language with Iterative approach.
**Time Complexity :** If the elements are uniformly distributed then O(log log n)
and in worst case it can take upto O(n).
**Auxiliary Space :** O(1).

_Below is the output of this algorithm._

### Checklist

- [x]  I've read the contribution guidelines.
- [x]  I've checked the issue list before deciding what to submit.
 - [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)
#451

### CODE REVIEW

**Comment by yashaswibiyahut** [comment]
90504593-f1f15a80-e16e-11ea-9427-4b197f74f42c
Output of this algorithm.

**Comment by yashaswibiyahut** [comment]
Please review my PR @SKAUL05 @Kajol-Kumari @Abhijit2505 @plazzy99 @siddharth25pandey

**Comment by vatsalkesarwani12** [comment]
mention issue no.
edit readme file

**Comment by yashaswibiyahut** [comment]
Issue Number =#451.
Update Readme file.
@plazzy99

**Review by siddharth25pandey — APPROVED** [review]
@yashaswibiyahut Looks fine to me as I already checked the same in the previous PR.
Able to merge.
Thanks!

**Review by iamrajiv — APPROVED** [review]

**Review by Kajol-Kumari — APPROVED** [review]
Well formatted! @yashaswibiyahut 

Please add a sample input-output below the code section in commented form. Rest looks perfect to me :)

**Comment by yashaswibiyahut** [comment]
Added sample Input Output in the code @Kajol-Kumari

**Comment by atarax665** [comment]
@yashaswibiyahut Update README.md so that I can merge this PR.

**Comment by yashaswibiyahut** [comment]
I have to edit  readme in yashaswi/neoalgo or tesseract/neoalgo ? @atarax665

**Comment by yashaswibiyahut** [comment]
Updated @atarax665

**Comment by yashaswibiyahut** [comment]
Updated Readme @atarax665

**Comment by yashaswibiyahut** [comment]
kindly merge this pr @atarax665

**Comment by yashaswibiyahut** [comment]
Thanks ☺️

**Comment by iamrajiv** [comment]
@all-contributors please add @yashaswibiyahut for code

**Pull request merged**
