### PR TITLE
Implemented Sprague-Grundy Theorem in C++

### PR DESCRIPTION
**Pull request by KartikeySharma**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Sprague-Grundy Theorem says that in a composite game in which 2 players A and B play, if both A and B play optimally (i.e., they don’t make any mistakes), then the player starting first is guaranteed to win if the XOR of the grundy numbers of position in each sub-games at the beginning of the game is non-zero. Otherwise, if the XOR evaluates to zero, then player A will lose definitely, no matter what.

### Checklist

- [Tick] I've read the contribution guidelines.
- [Tick] I've checked the issue list before deciding what to submit.
- [Tick] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Issue #1701

### CODE REVIEW

**Comment by KartikeySharma** [comment]
Why is the DeepSource bot giving an error? @shraddhavp 
Pls have a look once.

**Comment by KartikeySharma** [comment]
@shraddhavp Pls add the DWOC tag before merging if possible :)

**Comment by atarax665** [comment]
> Why is the DeepSource bot giving an error? @shraddhavp
> Pls have a look once.

The error has been resolved :+1:

**Review by atarax665 — COMMENTED** [review]
The contributed code is copied from [here](https://www.geeksforgeeks.org/combinatorial-game-theory-set-4-sprague-grundy-theorem/). Though you can refer to the articles and youtube videos but we expect you to implement the algorithm yourself. We take plagiarism seriously and this may lead to ban from contributing to this repository.

**Comment by KartikeySharma** [comment]
@atarax665 I will update my code and implement the theorem myself.
Can I make changes and continue in this PR?
Or should I create another pull request?

**Comment by KartikeySharma** [comment]
Could any maintainer pls reply? @atarax665

**Comment by KartikeySharma** [comment]
I am closing this PR and I will create another PR with the implemented code.
@atarax665

**Pull request closed without merging**
