### PR TITLE
transposing a matrix in-situ

### PR DESCRIPTION
**Pull request by prerna2712**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

### Description

(Write your answer here.)

### Checklist

- [ ] I've read the contribution guidelines.
- [ ] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

### CODE REVIEW

**Comment by prerna2712** [comment]
Can someone please review my PR?
Thank you.

**Comment by ankitaggarwal23** [comment]
We don't accept PRs without any corresponding Issue. It is difficult for us to find your issue in tons of issues available. We can't review and merged incomplete PR's.  

Capture

**Review by ankitaggarwal23 — COMMENTED** [review]
We don't accept PRs without any corresponding Issue. It is difficult for us to find your issue in tons of issues available. We can't review and merged incomplete PR's.  

Capture

**Comment by prerna2712** [comment]
I needed to add description to the PR, was that the issue?

**Pull request closed without merging**
