### PR TITLE
added_Iterative_Binary_Search

### PR DESCRIPTION
**Pull request by sumitgsh**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)
Yes
### Description

(Write your answer here.)
Added the iterative Binary Search 
### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)
#2227

### CODE REVIEW

**Comment by HarshCasper** [comment]
The PR would be reviewed after the Coding Period of GSSoC starts. Thanks!

**Comment by sumitgsh** [comment]
@ritvij14 @HarshCasper Please review my PR!!

**Comment by ritvij14** [comment]
> @ritvij14 @HarshCasper Please review my PR!!

@sumitgsh why are you tagging me??? I am not admin/moderator...

**Review by HarshCasper — CHANGES_REQUESTED** [review]
Few changes: 

- Add a beginner friendly pitch at the top of the Code.
- Shift Time and Space Complexity at the end of the Code
- Add sample I/O at the end of the Code
- Prefer Multi-Line Comments when you are extending beyond a single line
- Fornat your Code using a Clang Formatter 

Also is the Code plagiarized from GFG? Why are you following their driver code pattern?

**Comment by sumitgsh** [comment]
> * Also is the Code plagiarized from GFG? Why are you following their driver code pattern?
No I haven't used any part of the code from GFG and regarding the driver code pattern just wanna say..I tried to keep abstraction between the actual implementation and the main function..

**Comment by sumitgsh** [comment]
@HarshCasper can u please review and merge

**Review by HarshCasper — APPROVED** [review]

**Comment by sumitgsh** [comment]
@HarshCasper    please add a label from this so that it gets counted in the leaderboard. Currently no points are added
GsSoC21

**Pull request merged**
