### PR TITLE
Completed inorder traversal assigned to me for hakincodes

### PR DESCRIPTION
**Pull request by bagladivyang03**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

### Description

(Write your answer here.)

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [ ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

### CODE REVIEW

**Comment by bagladivyang03** [comment]
Completed #415 issue assigned to me 
Divyang Bagla

**Review by iamrajiv — CHANGES_REQUESTED** [review]
@bagladivyang03 update readme

**Comment by bagladivyang03** [comment]
As a part of hakin codes they were telling not to update readme so should i update or ?

**Comment by iamrajiv** [comment]
@bagladivyang03 Ok than leave it. I was not aware of that.

**Comment by bagladivyang03** [comment]
Yeah ok

**Review by vatsalkesarwani12 — CHANGES_REQUESTED** [review]
The code should work at all test cases 
```
               3
           /         \
       2              4
      /                   \
   1                        5
```

Unable to take this as input

**Comment by bagladivyang03** [comment]
It is working na See

Enter the data for root node                                                                                       
3                                                                                                                  
Enter the postion l / r where u want to insert the element                                                         
l                                                                                                                  
2                                                                                                                  
Do u want to enter more data ?                                                                                     
y                                                                                                                  
Enter the postion l / r where u want to insert the element                                                         
l                                                                                                                  
Enter the postion l / r where u want to insert the element                                                         
l                                                                                                                  
1                                                                                                                  
Do u want to enter more data ?                                                                                     
y                                                                                                                  
Enter the postion l / r where u want to insert the element                                                         
r                                                                                                                  
4                                                                                                                  
Do u want to enter more data ?                                                                                     
y                                                                                                                  
Enter the postion l / r where u want to insert the element                                                         
r                                                                                                                  
Enter the postion l / r where u want to insert the element                                                         
r                                                                                                                  
5
Do u want to enter more data ?                                                                                     
n                                                                                                                  
1 2 3 4 5                                                                                                          
1 2 3 4 5 


using recursive and non recursive the ans is correct na ?
Then whats the prob ??

**Comment by bagladivyang03** [comment]
Could u pls tell what is the change i have to do ?

**Comment by Kajol-Kumari** [comment]
> Could u pls tell what is the change i have to do ?

Hey @bagladivyang03 the code is working fine for me.

\cc: @plazzy99

**Review by Kajol-Kumari — COMMENTED** [review]
Code looks good to me, please add one example test case below the code section in commented form. Also please update the readme as well so that it would be easy for the user to find this :)

Good work!

**Comment by bagladivyang03** [comment]
Yeh sure i will do that :)

**Comment by bagladivyang03** [comment]
Hi there is some conflict between C++/readme @iamrajiv could u pls help in previous pr i was also getting the same type of conflicting issue.

**Comment by iamrajiv** [comment]
@bagladivyang03 Your branch is 119 commits behind TesseractCoding:master. Please make it even. Also, add inorder.cpp file inside the C-Plus-Plus directory. I would also suggest whenever you do changes make a separate branch for that, do not commit to master branch.

**Comment by bagladivyang03** [comment]
Okay i will do that inorder.cpp in c++ directory but how to make it even @iamrajiv

**Comment by iamrajiv** [comment]
@bagladivyang03 move inorder.cpp to C-Plus-Plus/graphs and for syncing issues go through this https://www.atlassian.com/git/tutorials/syncing

**Review by vatsalkesarwani12 — APPROVED** [review]

**Review by iamrajiv — APPROVED** [review]

**Review by iamrajiv — APPROVED** [review]

**Comment by bagladivyang03** [comment]
Can anyone pls help as i try to create a new pr it is always coming with previous commits as @siddharth25pandey u mentioned to create new pr Could u pls help

**Comment by siddharth25pandey** [comment]
> Can anyone pls help as i try to create a new pr it is always coming with previous commits as @siddharth25pandey u mentioned to create new pr Could u pls help

@bagladivyang03 You can create separate PR by Committing the required files only i.e one by one .

**Review by Kajol-Kumari — APPROVED** [review]
LGTM :)

**Comment by Kajol-Kumari** [comment]
> Can anyone pls help as i try to create a new pr it is always coming with previous commits as @siddharth25pandey u mentioned to create new pr Could u pls help

1. Commit all the changes if current branch. 
2. Move to master branch
3. Create n new branch and make the changes, commit it and push it and then create a PR with this. 

Always remember to navigate to your master branch while creating a new branch, otherwise all previous commit of previous branch will get to the new one. 


Feel free to ask if you need any further clarification.

**Comment by bagladivyang03** [comment]
@Kajol-Kumari  could u pls merge these as my repo is showing x commits ahead , y commits behind so if u merge ig these issue will solved and also the new PR issue which I m facing

**Pull request merged**
