### PR TITLE
doubly circular linkedlist added

### PR DESCRIPTION
**Pull request by neha030**
issue #2954 
 I have provided the code for doubly circular linkedlist in C++ language.
please review my code.

### CODE REVIEW

**Review by HarshCasper — CHANGES_REQUESTED** [review]
Why are some parts of the code look taken from [here](https://www.bogotobogo.com/cplusplus/linkedlist.php) ?

**Comment by neha030** [comment]
> Why are some parts of the code look taken from [here](https://www.bogotobogo.com/cplusplus/linkedlist.php) ?

the codes are different even i have seen this site for the first time.
can u please tell me which part of the code is same so that i can see.
do i need to make changes or it is still under review?

**Comment by neha030** [comment]
#2930 
Please review my code.
I am facing some issue the pull request of different issue which is assigned to me...commits to this particular pull request issue.
so, i please request to review my codes.

**Review by ankitaggarwal23 — COMMENTED** [review]
.

**Comment by ankitaggarwal23** [comment]
@neha030 Kindly don't commit all files in a same PR. It becomes difficult for us to review and don't spam in PR to review other PR. As our team is giving our best to review it may delay but we will review. Give us some time. As of now I'm closing all the PR. create a separate new one for each issue.

**Pull request closed without merging**
