### PR TITLE
added modified bubble sort using c

### PR DESCRIPTION
**Pull request by prashant7139**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)
yes
### Description

(Write your answer here.)
In the existing bubble sort ,if the array is already sorted then also the time complexity will be O(n^2) but in modified bubble sort if the array is already sorted then time complexity will be O(n) .
### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)
issue #5088

### CODE REVIEW

**Comment by prashant7139** [comment]
@ankitaggarwal23 please merge this PR .

**Review by ankitaggarwal23 — COMMENTED** [review]
Bubble sort problem already present.

**Comment by prashant7139** [comment]
@ankitaggarwal23 existing bubble sort which  is written in c is not the efficient one  . In the existing bubble sort ,if the array is already sorted then also the time complexity will be O(n^2) but in modified bubble sort if the array is already sorted then time complexity will be O(n) .

**Comment by ankitaggarwal23** [comment]
@prashant7139 You can modify the existing code

**Comment by ankitaggarwal23** [comment]
Open a new issue and mention the issue no which you want to modify

**Comment by prashant7139** [comment]
Ok .
Thank you.

**Pull request closed without merging**
