### PR TITLE
Gaurav6982

### PR DESCRIPTION
**Pull request by Gaurav6982**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

yes

### Description

Added the Dynamic Programming solution to a Problem Rectangle Cutting in both methods Tabulation and Memorization.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

### CODE REVIEW

**Comment by Gaurav6982** [comment]
Please Check@plazzy99

**Review by iamrajiv — CHANGES_REQUESTED** [review]
@Gaurav6982 Add space and time complexity.

**Comment by Gaurav6982** [comment]
> @Gaurav6982 Add space and time complexity.

Ok

**Review by vatsalkesarwani12 — APPROVED** [review]
👍🏻

**Review by iamrajiv — APPROVED** [review]

**Comment by iamrajiv** [comment]
@all-contributors please add @Gaurav6982 for code

**Pull request merged**
