### PR TITLE
The Boyer–Moore majority vote algorithm java

### LINKED ISSUE #1852: Optimizing Boyer–Moore majority vote algorithm
In code present in java folder https://github.com/TesseractCoding/NeoAlgo/blob/master/Java/Algorithms/Moore_Algorithm.java complexity of this algorithm is Quadratic.
but according to Boyer–Moore majority vote algorithm the time complexity should be linear.
I would like to fix this .

### PR DESCRIPTION
**Pull request by rutujadhanawade**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

I have updated the The Boyer–Moore majority vote algorithm in java folder

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Fixes #1852

### CODE REVIEW

**Comment by rutujadhanawade** [comment]
@iamrajiv @atarax665 Please review this.

**Comment by rutujadhanawade** [comment]
@iamrajiv Please review this.

**Review by atarax665 — APPROVED** [review]
LGTM👍

**Review by iamrajiv — APPROVED** [review]

**Review by ankitaggarwal23 — COMMENTED** [review]
Code already present #1433

**Comment by rutujadhanawade** [comment]
@ankitaggarwal23 please refer this issue. #1852

**Pull request merged**
