### PR TITLE
Flight of stairs using Javascript

### PR DESCRIPTION
**Pull request by FireQueen-3010**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

The flight of stairs problem using dp in Javascript

Given two positive integers : n and k. We are currently at stair 0, and want to climb to stair n. We can either climb 1, 2 or 3 stairs at a time, but we can climb 3 stairs only k times. Return the number of ways to climb to the nth stair.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#4223 (javascript)

### CODE REVIEW

**Comment by FireQueen-3010** [comment]
Please review my pr :) @siddharth25pandey  @HarshCasper

**Comment by ankitaggarwal23** [comment]
@FireQueen-3010 Don't push more than one code file in a single PR.

**Comment by FireQueen-3010** [comment]
So do I make another pr for this ? @ankitaggarwal23

**Comment by ankitaggarwal23** [comment]
Yes

**Comment by FireQueen-3010** [comment]
Ok, created the pr here #4330 please review @ankitaggarwal23

**Pull request closed without merging**
