### PR TITLE
Min swap to sort array.

### PR DESCRIPTION
**Pull request by mansi-9**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

minimum no. of swaps needed to sort the array in ascending order having integer in range 1 to N.
/*
input:
6
1 5 3 4 2 6
output:
1
*/

### Checklist
- [yes] I've read the contribution guidelines.
- [ yes] I've checked the issue list before deciding what to submit.
- [ yes] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#2894 .Added MinSwapToSortArray.cpp in cp folder of C-Plus-Plus folder.

### CODE REVIEW

**Comment by mansi-9** [comment]
@ankitaggarwal23 please review.

**Review by ankitaggarwal23 — CHANGES_REQUESTED** [review]
Use proper code Format (Code is not properly aligned.)

**Comment by mansi-9** [comment]
@ankitaggarwal23 Did the changes. Thanks!!!

**Review by ankitaggarwal23 — CHANGES_REQUESTED** [review]
Few changes: 

- Add a beginner-friendly description at the top
- Use proper code Format 
- Align your code properly
- Add Time and Space Complexity at the end of the Code   
- Shift the logic to another function and use main for driver code

**Comment by mansi-9** [comment]
@ankitaggarwal23 updated the same.

**Review by ankitaggarwal23 — APPROVED** [review]

**Pull request merged**
