### PR TITLE
Time Conversion C++

### PR DESCRIPTION
**Pull request by U-c0de**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?
(YES)

### Description
(Time Conversion : Converting 12 hour time in 24 hour time  )   |   C++

### Checklist
- [ YES] I've read the contribution guidelines.
- [ YES] I've checked the issue list before deciding what to submit.
- [ YES] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(#6695 )

### CODE REVIEW

**Comment by U-c0de** [comment]
@HarshCasper @gat786 @siddharth25pandey  Do Check the PR

**Comment by U-c0de** [comment]
@gat786  check it

**Comment by U-c0de** [comment]
@HarshCasper @gat786 @siddharth25pandey Do Check the PR

**Comment by U-c0de** [comment]
@HarshCasper @gat786 @siddharth25pandey Do Check the PR

**Comment by U-c0de** [comment]
@HarshCasper @gat786 @siddharth25pandey Do Check the PR

**Comment by U-c0de** [comment]
@ankitaggarwal23  please check the PR

**Review by ankitaggarwal23 — COMMENTED** [review]
We don't accept such code. It falls neither as a Data Structure not as an algorithm.

**Pull request closed without merging**
