### PR TITLE
Minimum swaps to sort array of N consecutive unordered integers

### PR DESCRIPTION
**Pull request by ritvij14**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?
Yes
(Write your answer here.)

### Description
Java code that finds the minimum number of swaps needed to sort an array of N consecutive integers [1, 2, 3, 4, ..., N].
(Write your answer here.)

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
Issue #461 
(Write your answer here.)

### CODE REVIEW

**Comment by ritvij14** [comment]
@siddharth25pandey @iamrajiv @Kajol-Kumari @plazzy99 @atarax665 Please review this PR.

**Comment by ritvij14** [comment]
@iamrajiv could you please tell me why you closed the PR? Did I do some mistakes?

**Review by iamrajiv — CHANGES_REQUESTED** [review]
@ritvij14 please add time and space complexity. Also, I think this has to be put in `Java/sort` directory, not in `Java/graphs`

**Comment by ritvij14** [comment]
> @ritvij14 please add time and space complexity. Also, I think this has to be put in `Java/sort` directory, not in `Java/graphs`

@iamrajiv the issue was a Graph problem so I thought it should come in the graphs folder. Should I move it in sort folder or let it stay in graphs since the issue mentioned so? 

Also, where should I mention the time and space complexity? In the PR message or in comments in code after sample input/output part?

**Comment by iamrajiv** [comment]
@ritvij14 move this to `Java/sort` because this is used to solve graphs related problems but no graph implementation is used. Also, add time and space complexity in code comments after sample input-output.

**Review by siddharth25pandey — APPROVED** [review]
@ritvij14 Looks fine to me. Do the modifications as suggested by @iamrajiv 
Able to merge.
Thanks !

**Comment by ritvij14** [comment]
@iamrajiv I have made the required changes, please review.

**Comment by iamrajiv** [comment]
@ritvij14 LGTM!

**Review by iamrajiv — APPROVED** [review]

**Review by Kajol-Kumari — APPROVED** [review]
LGTM :)

**Comment by iamrajiv** [comment]
@all-contributors please add @ritvij14 for code

**Pull request merged**
