### PR TITLE
Finding the numbers in Java

### PR DESCRIPTION
**Pull request by ritvij14**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?
Yes
(Write your answer here.)

### Description
Java code for finding the 2 unique numbers out of the 2N+2 numbers where N numbers are repeated twice.
(Write your answer here.)

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
Issue #922 
(Write your answer here.)

### CODE REVIEW

**Comment by ritvij14** [comment]
@iamrajiv @siddharth25pandey @plazzy99 @atarax665 please review this.

**Comment by ritvij14** [comment]
@iamrajiv @atarax665 @plazzy99 please review this, I have resolved the conflicts

**Review by iamrajiv — APPROVED** [review]

**Comment by ritvij14** [comment]
@atarax665 @plazzy99 this is my last PR for CH20, please check it and merge it.

**Review by vatsalkesarwani12 — APPROVED** [review]
👍🏻

**Review by atarax665 — APPROVED** [review]
LGTM :+1:

**Pull request merged**
