### PR TITLE
Added the Kosaraju's Algo (Graphs) Python #670

### PR DESCRIPTION
**Pull request by kritikaparmar-programmer**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Issue
#670 

### Description

Added Kosaraju's Algo (Python)

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

### Screenshot
This is the ss of the output (CMD)
algo

### CODE REVIEW

**Comment by kritikaparmar-programmer** [comment]
Hey @devanshiv123  @SKAUL05 @siddharth25pandey  @iamrajiv @atarax665 @Abhijit2505 please review this PR. Its been 5 days...

**Review by iamrajiv — CHANGES_REQUESTED** [review]
@kritikaparmar-programmer your code is same as this https://www.programiz.com/dsa/strongly-connected-components

**Comment by kritikaparmar-programmer** [comment]
Hey @iamrajiv I didn't copied from anywhere , the topic I learnt from somewhere and they taught me the way I wrote that way..
If you still have any problem then please tell me how can I improve

**Comment by iamrajiv** [comment]
@kritikaparmar-programmer Your code and https://www.programiz.com/dsa/strongly-connected-components is same only some variable names are changed. You can take reference of #768 and https://cp-algorithms.com/graph/strongly-connected-components.html and update the code.

**Pull request closed without merging**
