### PR TITLE
Added Data Encryption Standard Algorithm

### PR DESCRIPTION
**Pull request by PuravUdayDesai**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Checklist

- [X] I've read the contribution guidelines.
- [X] I've checked the issue list before deciding what to submit.
- [X] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Issue Number: #1553

### CODE REVIEW

**Comment by PuravUdayDesai** [comment]
@iamrajiv please review this request
Issue Number: #1553 
Pull Request Number: #1893

**Comment by PuravUdayDesai** [comment]
@iamrajiv please review this request.

**Comment by HarshCasper** [comment]
That's a LOT of Commits and files changed! 

Also, we do not need to have images for the Code. Would it be possible for you to break this PR down into multiple separate PRs?

**Comment by PuravUdayDesai** [comment]
@HarshCasper I will try to do the respective.

It would be great if you could tell the things needed in each PR request.

Can you please elaborate on
> we do not need to have images for the Code

Thank you so much for your time and sorry for the inconvenience.

**Comment by HarshCasper** [comment]
> @HarshCasper I will try to do the respective.
> 
> It would be great if you could tell the things needed in each PR request.
> 
> Can you please elaborate on
> 
> > we do not need to have images for the Code
> 
> Thank you so much for your time and sorry for the inconvenience.

As you see, every commit should correspond to something logical and PRs are meant to keep these logical changes compact and easy to review. Now in your case, multiple files have been changed, which makes the review process harder. Also it would be detrimental for you, as you will not be given extra scores for every code you push, since you are doing that via a single large PR.

Take a look at how other PRs have been merged and you will be better able to understand.

**Comment by PuravUdayDesai** [comment]
Sorry for late reply,
Ok @HarshCasper I'll do the respective, sorry for the inconvenience, I'll make three PR request, 1 for the code, 1 for the documentation and another one for images, will that work?

**Comment by HarshCasper** [comment]
> Sorry for late reply,
> Ok @HarshCasper I'll do the respective, sorry for the inconvenience, I'll make three PR request, 1 for the code, 1 for the documentation and another one for images, will that work?

We don't need Images at all. The Code and the corresponding documentation change should be part of the same PR.

**Comment by PuravUdayDesai** [comment]
> > Sorry for late reply,
> > Ok @HarshCasper I'll do the respective, sorry for the inconvenience, I'll make three PR request, 1 for the code, 1 for the documentation and another one for images, will that work?
> 
> We don't need Images at all. The Code and the corresponding documentation change should be part of the same PR.

@HarshCasper,I'll make a single PR request for the same though I request you to please once visit repository in my account, and once view the documentation, if you don't like it, then I'll just upload the code with written documentation NO images/visual material.

Link: [DES README](https://github.com/PuravUdayDesai/NeoAlgo/blob/1553-PuravUdayDesai/Java/cryptography/des/README.md)

Thank you for your time and efforts.
And sorry for any inconvenience faced by you due to me.

**Comment by atarax665** [comment]
> > > Sorry for late reply,
> > > Ok @HarshCasper I'll do the respective, sorry for the inconvenience, I'll make three PR request, 1 for the code, 1 for the documentation and another one for images, will that work?
> > 
> > 
> > We don't need Images at all. The Code and the corresponding documentation change should be part of the same PR.
> 
> @HarshCasper,I'll make a single PR request for the same though I request you to please once visit repository in my account, and once view the documentation, if you don't like it, then I'll just upload the code with written documentation NO images/visual material.
> 
> Link: [DES README](https://github.com/PuravUdayDesai/NeoAlgo/blob/1553-PuravUdayDesai/Java/cryptography/des/README.md)
> 
> Thank you for your time and efforts.
> And sorry for any inconvenience faced by you due to me.

The document looks great and I genuinely appreciate your effort but currently we aren't planning to add any documentation to sub-folders for now, I am closing this PR, please make a new PR with just code and updated main README.

**Comment by PuravUdayDesai** [comment]
@HarshCasper, @atarax665, @shraddhavp and @iamrajiv I have created a new pull request as told above, my only concern for adding README under subfolder was to explain to the user/viewer as if anyone comes across and wants to use the respective or only view the working that person should understand the whole thing and not wander around looking at it, comments are there, I thought it would be an added advantage and would save time.

I respect your concern and grateful that you like it and devoted your time and energy on it.

The last request, if it could be possible is to add a link to the README.md in my branch only for the documentation to the main README.md, the classes in my branch would have a link to the classes in TesseractCoding/NeoAlgo, if not possible no problem better luck next time 😊.

Thank you for your time and wellbeing.

Issue Number: #1553 
Pull Request Number: #1990

**Pull request closed without merging**
