### PR TITLE
Roti Prata in c++

### PR DESCRIPTION
**Pull request by gokulkannan7**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

C++ code for the problem statement mentioned inside the file added to cp folder of c-plus-plus section

### Checklist

- [YES] I've read the contribution guidelines.
- [YES] I've checked the issue list before deciding what to submit.
- [YES] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#6042

### CODE REVIEW

**Review by ankitaggarwal23 — CHANGES_REQUESTED** [review]
Don't use cp templates and remove test case part we don't have online judge to test

Few changes: 

- Add Multi-Line Comments 
- Add a beginner-friendly description at the top
- Use proper code Format 
- Remove extra lines of code and spaces
- Add sample I/O at the end of the Code
- Add Time and Space Complexity at the end of the Code   
- Add new line at the EOF

Use proper display message how you are reading and writing outputs

Add input-output prompts to make the program more interactive.

Shift the logic to another function and use main for driver code

You need to add comments to your code. Make sure the comments you add are above the line of code and not alongside it.

**Review by gokulkannan7 — COMMENTED** [review]
@ankitaggarwal23, I have updated the file but  I didn't understand what u meant by input-output prompts. Can you please explain? and also are there any other changes?

**Review by ankitaggarwal23 — COMMENTED** [review]
Read the instructions mentioned on Gssoc discord yesterday. Do the changes as per that.

**Comment by ankitaggarwal23** [comment]
Closing this due to inactivity. Thank you for your valuable time.😊

**Review by ankitaggarwal23 — COMMENTED** [review]
Closing this due to inactivity. Thank you for your valuable time.😊

**Pull request closed without merging**
