### PR TITLE
Shortest Distance between two nodes of BST

### PR DESCRIPTION
**Pull request by Nikitha2309**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Given a Binary Search Tree, Find the shortest distance between the given two nodes of BST in  CPP.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#4493

### CODE REVIEW

**Comment by Nikitha2309** [comment]
@ankitaggarwal23 @HarshCasper 
Pls review this PR
Thank you

**Review by ankitaggarwal23 — COMMENTED** [review]
Code plagiarized from [here](https://www.geeksforgeeks.org/shortest-distance-between-two-nodes-in-bst/).

**Comment by Nikitha2309** [comment]
> Code plagiarized from [here](https://www.geeksforgeeks.org/shortest-distance-between-two-nodes-in-bst/).

In my code, I first found LCA of given two nodes, 
then Found distance between LCA and two nodes 
And then added the sum of distances.

But I don't think they have done the same there.
Finding the distance between ancestor and node will be the same, however🙂.

@ankitaggarwal23 @HarshCasper 
I request you to check it once again, 
Thank you🙂

**Review by siddharth25pandey — APPROVED** [review]
@Nikitha2309 LGTM, able to merge 💯

**Comment by siddharth25pandey** [comment]
@all-contributors please add @Nikitha2309 for her code

**Comment by HarshCasper** [comment]
Please make an issue here and raise a PR, for an article as part of our Docs repository: https://github.com/TesseractCoding/NeoAlgo-Docs

It would be much appreciated. Thanks!

**Pull request merged**
