### PR TITLE
Lowest Common Ancestor

### PR DESCRIPTION
**Pull request by Shreyash41**
### Description

The lowest Common Ancestor is implemented in Binary Tree. In LCA, For two nodes, a and b, the lowest common ancestor c is the lowest node in the binary tree that has a and b as its descendants. This is the Efficient Approach to find Lowest Common Ancestors.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
 #3530

### CODE REVIEW

**Comment by Shreyash41** [comment]
@HarshCasper @bhav09 Sir, can you please review my PR?

**Comment by bhav09** [comment]
@Shreyash41, why is one segment of the code commented and the other's is not?

**Comment by Shreyash41** [comment]
@bhav09 @HarshCasper  Thanks Sir, For your Time. Sir, are you talking about the Node* LCA function segment? 

If yes, then this is simply understood that if both are less than root, then LCA lies in the left subtree as soon as we encounter the root having one of the values greater and other lesser than root. either both n1 and n2 lie on the left/right side of the root or n1 and n2 lies on either side of the root and that is our answer. that's why I not commented.

**Review by ankitaggarwal23 — COMMENTED** [review]
Code Plagiarized from [here](https://www.geeksforgeeks.org/print-left-view-binary-tree/).

**Comment by Shreyash41** [comment]
Respected @ankitaggarwal23 sir, can you please tell me from where this Code is Plagiarized because the [link](https://www.geeksforgeeks.org/print-left-view-binary-tree/) that you have attached is of **Left View of Binary Tree** and I solve this Issue on **Lowest Common Ancestor**. According to my knowledge, Both concepts are different from each other.

***Lowest Common Ancestor*** :- For two nodes, a and b, c is the **lowest node in the binary tree** that has a and b as its descendants.

***Left View of Binary Tree*** :- It is a set of nodes visible when the **Tree is visited from the left side** and only prints the left side of elements.

I think please give an appropriate reason to show that my code is invalid or plagiarized.

I request to @bhav09  and @HarshCasper Sir, to review this **Closed PR** and tell me where I am wrong??

**Comment by ankitaggarwal23** [comment]
@Shreyash41 Your 85-90% of your code exactly matches. Also the LCA function just above int main() matched with other platform.

**Pull request closed without merging**
