### PR TITLE
Added Possible Building Construction in C++ and C 

### PR DESCRIPTION
**Pull request by Nidhideveloper**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Added Possible Building Construction in C++ and C 

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#7058

### CODE REVIEW

**Comment by Nidhideveloper** [comment]
@ankitaggarwal23  Sir plz review this PR and let me knw if any changes are required.

**Comment by Nidhideveloper** [comment]
I have added the code in both the languages C and Cpp

**Comment by Nidhideveloper** [comment]
If only one language is allowed then let me know I will remove the other one. Thank you sir!

**Review by ankitaggarwal23 — COMMENTED** [review]
Code plagiarized from [here](https://www.geeksforgeeks.org/count-possible-ways-to-construct-buildings/)

**Pull request closed without merging**
