### PR TITLE
feat: Greets the new user

### PR DESCRIPTION
**Pull request by Karthik-Nayak98**
* It adds two labels GSSOC'21 and proposal.
    * Adds the comment when the user creates a new issue or a PR

    * Fix the issue #2364

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

### Description

#2364

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

### CODE REVIEW

**Comment by Karthik-Nayak98** [comment]
Why I am getting this error? @HarshCasper @anushkrishnav

**Comment by anushkrishnav** [comment]
@Karthik-Nayak98 Dont mind the error

**Comment by anushkrishnav** [comment]
Awesome Work !! Thanks for your contribution !!

**Comment by Karthik-Nayak98** [comment]
Thank you for the opportunity.

**Comment by Karthik-Nayak98** [comment]
I think we can build one more GitHub action which will close the issue and the PR once it gets merged to the master branch. @anushkrishnav

**Comment by anushkrishnav** [comment]
@Karthik-Nayak98 sounds perfect open a new issue for it, lemme know if you need some help also I have a list of actions I am working on so if possible get this pr im by tomm we can more on more such PR.
Have you joined our Slack ?

**Comment by Karthik-Nayak98** [comment]
I haven't joined the slack
I will open an issue now.

**Comment by Karthik-Nayak98** [comment]
I will ask if I need any kind of help

**Comment by Karthik-Nayak98** [comment]
How can I join your slack channel? @anushkrishnav

**Pull request merged**
