### PR TITLE
Reverse Queue using Stack in C++

### PR DESCRIPTION
**Pull request by prithwirajmitra2001**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes I have

### Description

In response to #2421 
Added the code for reversing queue content using stack in C++.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

I have implemented this code in C++

### CODE REVIEW

**Comment by prithwirajmitra2001** [comment]
Will you please look at this PR @HarshCasper

**Review by HarshCasper — CHANGES_REQUESTED** [review]
Few changes: 
- Add a beginner-friendly description about your Code at the top
- Add description of functions 
- Add sample I/O at the end of the Code
- Add complexity at the end of the code
- Use a Code formatter to format the Code

**Comment by prithwirajmitra2001** [comment]
Sorry Sir for the mistake.
Made the requested changes.
Please review.

**Comment by prithwirajmitra2001** [comment]
Please review again @HarshCasper

**Review by HarshCasper — APPROVED** [review]

**Pull request merged**
