### PR TITLE
Span of array in Java

### LINKED ISSUE #6002: span of an array in Java
## 💥 Proposal

(A clear and concise description of what the proposal is.)
 Given a number n, representing the size of array, and n numbers of array are given. we have to find the span of array.
span of array is the difference of maximum value and minimum value in the array.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

yes

### PR DESCRIPTION
**Pull request by gnikita432**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

yes

### Description

Added a program to find the span of an array in Java language
Span of an array is the difference between the maximum value and minimum value of the array

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
Fixes #6002

### CODE REVIEW

**Review by ankitaggarwal23 — CHANGES_REQUESTED** [review]
Few changes: 

- Add Multi-Line Comments 
- Add a beginner-friendly description at the top
- Use proper code Format 
- Remove extra lines of code and spaces
- Add sample I/O at the end of the Code
- Add Time and Space Complexity at the end of the Code   
- Add new line at the EOF

Use proper display message how you are reading and writing outputs

Add input-output prompts to make the program more interactive.

Shift the logic to another function and use main for driver code

**Review by ankitaggarwal23 — COMMENTED** [review]
Last Reminder, Read the instructions mentioned on Gssoc discord yesterday. Do the changes as per that.

**Comment by gnikita432** [comment]
I am getting error while pushing to the branch.

**Review by ankitaggarwal23 — CHANGES_REQUESTED** [review]
Read the instructions mentioned on Gssoc discord yesterday. Do the changes as per that.

**Review by ankitaggarwal23 — CHANGES_REQUESTED** [review]
Read the instructions mentioned on Gssoc discord yesterday. Do the changes as per that.

**Review by ankitaggarwal23 — CHANGES_REQUESTED** [review]
Read the instructions mentioned on Gssoc discord. Do the changes as per that.

**Comment by ankitaggarwal23** [comment]
Closing this due to inactivity. Thank you for your valuable time.😊

**Review by ankitaggarwal23 — COMMENTED** [review]
Closing this due to inactivity. Thank you for your valuable time.😊

**Pull request closed without merging**
