### PR TITLE
These are some WoC contributions which aren't merged yet

### PR DESCRIPTION
**Pull request by fomalhauting**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)

### Description

(Write your answer here.)

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

### CODE REVIEW

**Comment by fomalhauting** [comment]
You could also close this PR, so I can start GSSoC contributions fresh

**Comment by fomalhauting** [comment]
You could also close this PR, so I can start GSSoC contributions fresh

**Comment by gat786** [comment]
Was it necessary to create a new pr for all this?

**Comment by fomalhauting** [comment]
I was unable to contribute for GSSoC without it, extremely sorry.

**Pull request closed without merging**
