### PR TITLE
StairCase Search

### LINKED ISSUE #2257: StairCase Search
## 🚀 Feature

StairCase search is also commonly known as Search in a Row and Column sorted array.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes 

## Motivation

Want to add this as it is not covered in repo. 

## Pitch

Want to implement Staircase search in python and want to aware people about this type of search.

### PR DESCRIPTION
**Pull request by Akash20x**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Add the implementation of Staircase search problem 

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Fixes #2257

### CODE REVIEW

**Review by HarshCasper — CHANGES_REQUESTED** [review]
Few changes: 

- Make the Markdown updates. 
- Use dynamic input
- Add function docstrings
- Use multi-line strings for comments

**Comment by kiruba-r11** [comment]
@HarshCasper It is an important note that the lines from 3 to 10 (i.e. the comments to explain the algorithm of this problem) is been plagiarised from one of my PR's in another repository. The picture below shows my work. 

Screenshot 2021-03-13 at 5 39 09 PM

You may [Click here](https://github.com/ankitapuri/DSA-guide/pull/263/files) to view my PR.

**Comment by Akash20x** [comment]
> @HarshCasper It is an important note that the lines from 3 to 10 (i.e. the comments to explain the algorithm of this problem) is been plagiarised from one of my PR's in another repository. The picture below shows my work.
> 
> Screenshot 2021-03-13 at 5 39 09 PM
> 
> You may [Click here](https://github.com/ankitapuri/DSA-guide/pull/263/files) to view my PR.

If you have problem I used your comments, then I will change it in my words.

**Comment by Akash20x** [comment]
> @HarshCasper It is an important note that the lines from 3 to 10 (i.e. the comments to explain the algorithm of this problem) is been plagiarised from one of my PR's in another repository. The picture below shows my work.
> 
> Screenshot 2021-03-13 at 5 39 09 PM
> 
> You may [Click here](https://github.com/ankitapuri/DSA-guide/pull/263/files) to view my PR.

Hey I close pull request and change the comments lines in my own words and then send new pull request with updated comments. 

But I think, these small things can be ignored, but I will change

**Pull request closed without merging**
