### PR TITLE
Implement Merge Sort Algorithm 

### PR DESCRIPTION
**Pull request by MSufiyanAG**
Merge sort using java .
with a README file explaining the algorithm. #18

### CODE REVIEW

**Comment by MSufiyanAG** [comment]
@HarshCasper  please help i dont know where i went wrong

**Comment by omkarlanghe** [comment]
@HarshCasper Ensure your folder name and file name are up to the contribution guidelines. refer #61

**Comment by ashwanisng** [comment]
Please make sure to check the guidelines before submitting your PR :)

**Comment by HarshCasper** [comment]
Please resolve the Conflicts @MSufiyanAG

**Comment by MSufiyanAG** [comment]
@HarshCasper  please merge

**Comment by mar-galho** [comment]
Hi! 

I will merge your contributions now - however, I'm moving your descriptive file to our Wiki section, as an article!

Thanks a lot!

**Comment by mar-galho** [comment]
@all-contributors please add @MSufiyanAG for code and documentation

**Pull request merged**
