### PR TITLE
Implemented factorial in Go

### LINKED ISSUE #4544: Implementing Factorial in Go
## 💥 Proposal

Implementing factorial in Go.

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

### PR DESCRIPTION
**Pull request by nidh-ish**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Implemented factorial in Go.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Fixes #4544

### CODE REVIEW

**Review by iamrajiv — CHANGES_REQUESTED** [review]
@nidh-ish Add space and time complexity.

**Comment by nidh-ish** [comment]
@iamrajiv Added TC and SC.

**Review by iamrajiv — APPROVED** [review]

**Comment by nidh-ish** [comment]
@iamrajiv Could you please add the appropriate level tag?

**Comment by HarshCasper** [comment]
Please make an issue here and raise a PR, for an article as part of our Docs repository: https://github.com/TesseractCoding/NeoAlgo-Docs

It would be much appreciated. Thanks!

**Pull request merged**
