### PR TITLE
Added algorithms: Maximum in Array, Reverse words in string, find permutations in string.

### PR DESCRIPTION
**Pull request by omkarlanghe**
Please read [how to contribute](CONTRIBUTING.md) first!
# Description
## Maximum in Array:
Given an array of type positive integers, having ith element as feet and ith + 1 element as inches.
Eg: considering arr = [1,2] where 1 equals to feet and 2 equals to inches.
Find the maximum height, where height is calculated sum of feet and inches after converting feet into inches.

## Reverse words in string:
Given a String of length S, reverse the whole string without reversing the individual words in it. Words are separated by dots.

## Find permutations in string (Dynamic programming):
Given a string S. The task is to print all permutations of a given string.

## Don't forget to visit our [website](http://www.tesseractcoding.tech)!

Feel free to add this badge after your submission is accepted!

```
<a href=https://github.com/TesseractCoding/NeoAlgo>
   <img src=https://user-images.githubusercontent.com/22795064/86514270-f831ae80-be2e-11ea-8e61-347ec81c2b50.jpg>
</a>
```

### CODE REVIEW

**Review by anushkrishnav — CHANGES_REQUESTED** [review]
Please remove Merge PR #2 and  #3 . Refer [this](https://medium.com/@anush.venkatakrishna/how-to-remove-undo-a-commit-from-your-pr-65e2e4e195af?sk=08b796b9b3dc5fbd94ef606618371214) If you don't know how to drop commit

**Comment by mar-galho** [comment]
The whole idea of this repo is to encourage people to write down their own code...I have personal folders with codes for most of the DS/Algs for several languages.

I don't think it is to our best interest to have code which is directly taken from other places...

**Comment by omkarlanghe** [comment]
> Please remove Merge PR #2 and #3 . Refer [this](https://medium.com/@anush.venkatakrishna/how-to-remove-undo-a-commit-from-your-pr-65e2e4e195af?sk=08b796b9b3dc5fbd94ef606618371214) If you don't know how to drop commit

Can I know the reason behind this ? I think the purpose of this repo is to encourage people to write code. They can refer to some online problem statements and code it into their thought process and not to copy paste ready made codes from other sources.

**Comment by mar-galho** [comment]
This is the idea. If you have just copied the code, this is bad. Using other places as a source of information, but writing the code yourself, it is fine. 

If that is the case, I see no problem with accepting your code. I just wanted a clarification.

**Comment by mar-galho** [comment]
I am going to review this, but two things: 

- The "contributors" session will be edited/added by a bot - so, if you could just remove your update from the README.md file regarding that, I'd appreciate it;

- If you could just edit the README.md link to put the link in alphabetical order, it would also be good - this is a standard we're trying to follow.

Also, if you haven't simply copied/pasted the code from GfG, I see no reason to cite them as a source. However, if it is verified that it is an integral copy, the code shouldn't be submitted.

**Comment by anushkrishnav** [comment]
Hey . Good work . Can you drop your previous commit .
The older ones . Have a great day .
Also @ricardoprins  has to review on it too .

**Review by mar-galho — CHANGES_REQUESTED** [review]
Don't worry about squashing your commits, I can do that from here.

If you could just update the link to the README.md file within the C++ folder, it would be great.

Thanks a lot for your contribution!

**Comment by omkarlanghe** [comment]
@ricardoprins Please review PR #238 . Changes made as per your suggestions.

**Comment by mar-galho** [comment]
Perfect. Thanks!

@all-contributors please add @omkarlanghe for code.

**Pull request merged**
