### PR TITLE
Vishruta patil

### PR DESCRIPTION
**Pull request by Vishruta-Patil**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?
yes
(Write your answer here.)

### Description
Heapify is the faster method to create heap. In this process, all elements are not processed. 
i.e. Leaf elements are not processed. This makes the process faster.
(Write your answer here.)

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

### CODE REVIEW

**Comment by Vishruta-Patil** [comment]
@ankitaggarwal23 can you pls help me as I am getting 1 failing check. I have added my code

**Comment by ankitaggarwal23** [comment]
> @ankitaggarwal23 can you pls help me as I am getting 1 failing check. I have added my code

Don't worry our team is working on it. Don't worry We will review.

**Comment by Vishruta-Patil** [comment]
> > @ankitaggarwal23 can you pls help me as I am getting 1 failing check. I have added my code
> 
> Don't worry our team is working on it. Don't worry We will review.

Any updates?

**Comment by Vishruta-Patil** [comment]
> > @ankitaggarwal23 can you pls help me as I am getting 1 failing check. I have added my code
> 
> Don't worry our team is working on it. Don't worry We will review.

@ankitaggarwal23  any updates?

**Comment by ankitaggarwal23** [comment]
> > > @ankitaggarwal23 can you pls help me as I am getting 1 failing check. I have added my code
> > 
> > 
> > Don't worry our team is working on it. Don't worry We will review.
> 
> @ankitaggarwal23 any updates?

You can ignore it, there is some glitch at deepsource's end.

**Comment by ankitaggarwal23** [comment]
@Vishruta-Patil We don't accept PRs without any corresponding Issue. It is difficult for us to find your issue in tons of issues available. We can't review and merged incomplete PR's.       

Capture

**Pull request closed without merging**
