### PR TITLE
algorithms in Rust

### PR DESCRIPTION
**Pull request by abhikjain360**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes, ofcourse!

### Description

Created a setup to start writing algorithms in Rust. Currently no algorithms are actually written out, but the guidelines and code layout are set so that contributors can easily write them.

### Checklist

- [X] I've read the contribution guidelines.
- [X] I've checked the issue list before deciding what to submit.
- [X] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

This PR is for the issue #2193

### CODE REVIEW

**Comment by abhikjain360** [comment]
@gat786 please review!

**Comment by HarshCasper** [comment]
That's a lot of code but glad to see you taking up the initiative :) 

If you are participating in GSSoC '20, this would be a good start to your proposal on Rust. Since I don't really have expertise in Rust (just moved ahead of Hello World), I will tag @routrohan who has worked extensively in Rust. 

I will still review the PR on behalf of stylistic changes and more. The Coding Period for GSSoC would start after 8th March so please expect it to be reviewed and merged after the date.

**Comment by gat786** [comment]
Yes, that's the very same reason I didn't comment on this. I figured some rustacean should look and comment on it. rather than me giving my advice which is collected from writing messy TypeScript all day long ;-;

**Comment by abhikjain360** [comment]
@routrohan  @HarshCasper please do review! This PR is needed to be review and merged as others then can easily contribute in Rust. People are starting to show interest, and having this merged will makes thing easy for them.

**Comment by gat786** [comment]
I will message rohan and ask him to review this code whenever he is available

**Pull request closed without merging**
