### PR TITLE
Added code for deleting consecutive same words in a sequence

### LINKED ISSUE #5241: Delete consecutive same words in a sequence in using stacks in C++
## 💥 Proposal

I want to add the code to delete consecutive same words in a sequence in using stacks in C++. [GSSOC '21]

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

### PR DESCRIPTION
**Pull request by SAY-droid427**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

I added code for deleting consecutive same words in a sequence using stacks in C++

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Fixes https://github.com/TesseractCoding/NeoAlgo/issues/5241

### CODE REVIEW

**Comment by SAY-droid427** [comment]
@HarshCasper @ankitaggarwal23 Please review this PR.

**Review by ankitaggarwal23 — COMMENTED** [review]
Code plagiarized from here.
https://www.geeksforgeeks.org/delete-consecutive-words-sequence/#:~:text=Method%202%3A(Using%20Stack,the%20whole%20sequence%20is%20traversed.

**Comment by SAY-droid427** [comment]
@ankitaggarwal23 The source you have stated displays the number of words left after deleting, while my code prints the words after deletion.

**Comment by ankitaggarwal23** [comment]
> @ankitaggarwal23 The source you have stated displays the number of words left after deleting, while my code prints the words after deletion.


Capture

**Pull request closed without merging**
