### PR TITLE
A Sample PR

### PR DESCRIPTION
**Pull request by HarshCasper**
Please read [how to contribute](CONTRIBUTING.md) first!
# Description
Submission description here

Checklist
* [ ] I've checked the issue list __BEFORE__ deciding what to submit
* [ ] I've read the contribution guidelines
* [ ] I've edited the README.md link to my code

## Don't forget to visit our [website](http://www.tesseractcoding.tech)!

Feel free to add this badge after your submission is accepted!

```
<a href=https://github.com/TesseractCoding/NeoAlgo>
   <img src=https://img.shields.io/badge/NeoAlgo-Contributor-brightgreen>
</a>
```

### CODE REVIEW

**Comment by HarshCasper** [comment]
@all-contributors please add @bagladivyang03 for code

**Comment by HarshCasper** [comment]
@all-contributors please add @ritvij14 for code

**Comment by HarshCasper** [comment]
@all-contributors please add @yashaswibiyahut for code

**Comment by HarshCasper** [comment]
@all-contributors please add @subhayu99 for code

**Comment by HarshCasper** [comment]
@all-contributors please add @anubhvshrma18 for code

**Comment by HarshCasper** [comment]
@all-contributors please add @sharur7 for code

**Comment by HarshCasper** [comment]
@all-contributors please add @nutanaarohi123 for code

**Comment by HarshCasper** [comment]
@all-contributors please add @pradeep98 for code

**Comment by HarshCasper** [comment]
@all-contributors please add @bagladivyang03 for code

**Comment by mar-galho** [comment]
@all-contributors please add @ricardoprins for docs

**Comment by HarshCasper** [comment]
@all-contributors please add @siddharth25pandey for ideas

**Comment by HarshCasper** [comment]
@all-contributors please add @siddharth25pandey for content

**Pull request merged**
