### PR TITLE
Remove outermost parenthesis in Javascript

### PR DESCRIPTION
**Pull request by ritvij14**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?
Yes
(Write your answer here.)

### Description
This is code for removing the outermost parenthesis using Javascript.
(Write your answer here.)

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
Issue #955 
(Write your answer here.)

### CODE REVIEW

**Comment by ritvij14** [comment]
@plazzy99 @atarax665 @siddharth25pandey @iamrajiv please review this PR.

**Review by vatsalkesarwani12 — APPROVED** [review]
LGTM 👍🏻

**Review by atarax665 — APPROVED** [review]
Looks good to me. :+1:

**Review by Kajol-Kumari — APPROVED** [review]
LGTM :+1:

**Pull request merged**
