### PR TITLE
Added Mo's Algorithm

### PR DESCRIPTION
**Pull request by Jassi10000-zz**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Write your answer here.)
Yes

### Description

(Write your answer here.)
It is a basic idea that is implemented to improve the speed of query-based algorithms. It is mostly used in Competitive Programming

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)
Yes

### CODE REVIEW

**Comment by Jassi10000-zz** [comment]
Successfully added the PR
Please refer to the PR made on 17th January as its the updated one commit, and ignore the PR on 12th January

**Comment by shraddhavp** [comment]
@Jassi10000  make the code to take input dynamically from the user and add space and time complexity

**Comment by Jassi10000-zz** [comment]
@shraddhavp Ok mam no issues
I will do it

**Comment by Jassi10000-zz** [comment]
Should I close this PR?
and make a new one next time?

**Comment by HarshCasper** [comment]
> Should I close this PR?
> and make a new one next time?

Preferred to work on this PR. Making multiple PRs for a single Issue and closing them to rectify the change requested would simply flood the Project. 

Every piece of Code goes through continuous reviews before it is merged. So please work on this PR itself to address the issues that we raise 👍

**Comment by Jassi10000-zz** [comment]
@shraddhavp  Mam I have updated the commits in the PR , according to what you said
1. Added the time and space complexities
2. Updated the code to take input from the user

**Comment by HarshCasper** [comment]
@Jassi10000 Make README changes as well. Let me know once you are done with the same and I will take a look over the Code 👍

**Comment by Jassi10000-zz** [comment]
> @Jassi10000 Make README changes as well. Let me know once you are done with the same and I will take a look over the Code 👍

You mean I need to make changes in that Contributors.md file mentioned in Readme?   @HarshCasper

**Comment by HarshCasper** [comment]
> > @Jassi10000 Make README changes as well. Let me know once you are done with the same and I will take a look over the Code 👍
> 
> You mean I need to make changes in that Contributors.md file mentioned in Readme? @HarshCasper

Nope. Every Langauge Directory has a README as well. Please make changes to it. 

Please resolve the Merge Conflicts as well.

**Comment by HarshCasper** [comment]
Closing the PR because no no updates.

**Comment by Jassi10000-zz** [comment]
@HarshCasper , bro what means no updates , am having my exams besides , so not getting much time , it was a coincidence that I got to see this one right now only 
Besides that , am not a pro in open source , just a beginner , so its difficult for me to figure out things what to do and how to do , I hope you would have also gone through this

With that , you also closed the PR , you would have asked last time about updates  coz you told me 2 things to do  ,   
1. to add my name in  contributors list
2. to solve the conflicts 

The first one  is already been done on the same day itself  , so atleast I expect you can ask last time about updates of second one 

Btw I have already put my name in contributors list  , you can check as well 
and regarding the merge conflicts , I don't know how to solve them , and not getting time to see a video or so , so that's why it got late 

If you understood my situation a little too , then just give me one more day , and I will finish it

**Pull request closed without merging**
