### PR TITLE
Remove Duplicate Element from an array using extra space

### PR DESCRIPTION
**Pull request by ashwanisng**
Remove Duplicate Element from an array using extra space

### CODE REVIEW

**Comment by mar-galho** [comment]
Thanks for the contribution!

Could you refer to the contribution guidelines and make the necessary adjustments to your submission?

**Review by mar-galho — CHANGES_REQUESTED** [review]
Remove the additional folders and consider maintaining this algorithm in the _other_ section instead of creating a new section in the structure.

**Comment by ashwanisng** [comment]
@ricardoprins  okay where I have to create a folder for competitive  programing

**Comment by mar-galho** [comment]
Just leave the code in the main folder for now, and add the link to the "Other" section. We will add further organization to the folders once we have more code in them. Thanks again for your contribution!

**Comment by ashwanisng** [comment]
@ricardoprins done with the changes. Thanks for the review 👍

**Review by mar-galho — CHANGES_REQUESTED** [review]
Perfect! Now just a tiny request: you have submitted the IntelliJ files along with your code :D

Could you remove them from the PR?

**Comment by ashwanisng** [comment]
> Perfect! Now just a tiny request: you have submitted the IntelliJ files along with your code :D
> 
> Could you remove them from the PR?

I have written the code in intelliJ

**Comment by mar-galho** [comment]
Yeah, I know, I also use it as well. You don't need to upload the .idea files though - you can just submit the README.md and your code file to this PR.

**Review by mar-galho — APPROVED** [review]
Great, thanks!

**Pull request merged**
