### PR TITLE
Added 2-D_Matrix Sorting

### PR DESCRIPTION
**Pull request by GrayFlash**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Implementation of Matrix Sorting
### Checklist

- [Yes ] I've read the contribution guidelines.
- [Yes ] I've checked the issue list before deciding what to submit.
- [Yes ] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

 Issue Number #825

### CODE REVIEW

**Comment by nutanaarohi123** [comment]
@GrayFlash  edit your C++ code ..atleast remove geeksforgeeks.

**Review by vatsalkesarwani12 — CHANGES_REQUESTED** [review]
You have pushed the gfg code

**Comment by GrayFlash** [comment]
> You have pushed the gfg code

Sorry for the gfg code, but I saw in one of the code in CPP directory that used gfg code with it's link given in explanation. So I am sorry for that. I have removed and changed the code.

**Review by siddharth25pandey — APPROVED** [review]
@GrayFlash Good to go
Able to merge.
Thanks!

**Review by vatsalkesarwani12 — APPROVED** [review]

**Review by iamrajiv — APPROVED** [review]

**Comment by iamrajiv** [comment]
@all-contributors please add @GrayFlash for code

**Pull request merged**
