### PR TITLE
Number of Good Pairs in an Array

### PR DESCRIPTION
**Pull request by Shivangi-ch**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?
Yes

### Description

Added the file `Number_of_good_pairs.cpp` to fix issue #5910

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(#5910)

### CODE REVIEW

**Review by bhav09 — COMMENTED** [review]
Comments should be above the respective line of code and not alongside.
Also need to mention the complexity of the code.

**Comment by Shivangi-ch** [comment]
I have made the changes!

**Review by ankitaggarwal23 — CHANGES_REQUESTED** [review]
Use proper code format


Few changes: 

- Add Multi-Line Comments 
- Add a beginner-friendly description at the top
- Use proper code Format 
- Remove extra lines of code and spaces
- Add sample I/O at the end of the Code
- Add Time and Space Complexity at the end of the Code   
- Add new line at the EOF

Use proper display message how you are reading and writing outputs

Add input-output prompts to make the program more interactive.

**Comment by Shivangi-ch** [comment]
Please Review! I have made the requested changes @ankitaggarwal23

**Review by ankitaggarwal23 — CHANGES_REQUESTED** [review]
Use proper display message how you are reading and writing outputs

Add input-output prompts to make the program more interactive.

Shift the logic to another function and use main for driver code

**Comment by Shivangi-ch** [comment]
Please review! I have made the changes @ankitaggarwal23

**Review by ankitaggarwal23 — APPROVED** [review]

**Pull request merged**
