### PR TITLE
job scheduling with given deadlines in cpp

### PR DESCRIPTION
**Pull request by captainra1**
this pull request is related to issue: job scheduling with deadlines.
all the description related to the problem is inside the .cpp file.
issue no.: #2933

### CODE REVIEW

**Review by HarshCasper — CHANGES_REQUESTED** [review]
Make README changes as well and use dynamic input.

**Comment by captainra1** [comment]
I have modified the requested changes, please review them.

**Comment by captainra1** [comment]
since, I have forked this repo some days ago, now I am facing conflicting issue when I am updating the readme file, because your read me file is some commit ahead of mine. I have tried several method from google but, problem not resolved so please help.
@HarshCasper

**Comment by atarax665** [comment]
> since, I have forked this repo some days ago, now I am facing conflicting issue when I am updating the readme file, because your read me file is some commit ahead of mine. I have tried several method from google but, problem not resolved so please help.
> @HarshCasper

You can try [this](https://gist.github.com/CristinaSolana/1885435).

**Review by ankitaggarwal23 — CHANGES_REQUESTED** [review]
Kindly do the changes mentioned

**Comment by captainra1** [comment]
all requested changes has been made.
1. added dynamic inputting.
2. updated readme file.

**Review by HarshCasper — APPROVED** [review]

**Pull request merged**
