### PR TITLE
Readme update qsharp

### PR DESCRIPTION
**Pull request by NEEHITGOYAL**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

yes

### Description

updated readme files of qsharp

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#1132

### CODE REVIEW

**Comment by NEEHITGOYAL** [comment]
@iamrajiv @plazzy99 @HarshCasper @atarax665 kindly review and merge it and if possible also add hacktoberfest tag

**Comment by NEEHITGOYAL** [comment]
anyone please merge it

**Comment by atarax665** [comment]
@NEEHITGOYAL Sorry for the late response. As I can see you have added README.md for all the sub-folders of all the languages, but we do prefer single README in the main folder which work as an index for the whole lang folder. This is because having readme for all the sub-folders individually will make it quite hard for contributors to edit 2 readmes everytime they contribute and will also make the maintainer's work troublesome. Another main reason of not approving this proposal is that making simultaneous changes to readme often lead to merge conflicts and we try to avoid that here coz most of the newbies have hard time resolving it.

**Comment by NEEHITGOYAL** [comment]
Okk there were readme file already so I thought I should complete it and I assure there will be no merge conflicts because there are changes in only internal readme@atarax665

**Pull request closed without merging**
