### PR TITLE
Reverse Linked List in C

### PR DESCRIPTION
**Pull request by Yash-Thakare22**
Implemented of Reversing a Linked List in C using Iterative and Recursive Method

### CODE REVIEW

**Comment by Yash-Thakare22** [comment]
Pls review the changes in above file @iamrajiv

**Review by iamrajiv — CHANGES_REQUESTED** [review]
@YashThakare please update readme

**Comment by Yash-Thakare22** [comment]
I have updated README pls check

**Comment by Yash-Thakare22** [comment]
Please commit my file . I have done necessary changes @iamrajiv

**Review by siddharth25pandey — APPROVED** [review]
@YashThakare Looks fine to me
Able to merge.
Thanks!

**Comment by Yash-Thakare22** [comment]
@siddharth25pandey Thanks for your review

**Review by iamrajiv — APPROVED** [review]

**Pull request merged**
