### PR TITLE
Painters Partition problem in C

### PR DESCRIPTION
**Pull request by rutujadhanawade**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

yes

### Description

Added painter partition problem in C language.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#1068

### CODE REVIEW

**Comment by rutujadhanawade** [comment]
@iamrajiv @plazzy99 @atarax665 Please review this PR

**Review by iamrajiv — CHANGES_REQUESTED** [review]
@rutujadhanawade Add time and space complexity.

**Comment by rutujadhanawade** [comment]
Done @iamrajiv Please review.

**Review by vatsalkesarwani12 — APPROVED** [review]
👍🏻

**Review by iamrajiv — APPROVED** [review]

**Pull request merged**
