### PR TITLE
feat: Added Bead Sort in C++

### LINKED ISSUE #2072: Bead Sort
## 🚀 Feature
[DWOC Contribution]
Bead Sort in C++

(A clear and concise description of what the feature is.)

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

## Motivation

Bead Sort (also known as Gravity Sort) was inspired from natural phenomenons and was designed keeping in mind objects(or beads) falling under the influence of gravity.

### PR DESCRIPTION
**Pull request by m-code12**
### Fixes
#2072 

### Have you read the [Contributing Guidelines on Pull Requests]
Yes

### Description

(Write your answer here.)

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

### CODE REVIEW

**Comment by m-code12** [comment]
@atarax665 @shraddhavp @anushkrishnav Please review and merge this pr.

**Review by atarax665 — CHANGES_REQUESTED** [review]
The code looks plagiarized. Its is quite similar to [this](https://www.geeksforgeeks.org/bead-sort-natural-sorting-algorithm/)

**Comment by m-code12** [comment]
> The code looks plagiarized. Its is quite similar to [this](https://www.geeksforgeeks.org/bead-sort-natural-sorting-algorithm/)

Okay I'll change the whole code.

**Comment by m-code12** [comment]
> The code looks plagiarized. Its is quite similar to [this](https://www.geeksforgeeks.org/bead-sort-natural-sorting-algorithm/)

Okay I'll change the whole code.

**Comment by m-code12** [comment]
@atarax665 I have changed the whole code, please check it again

**Comment by HarshCasper** [comment]
HI @m-code12 

Unfortunately, plagiarism allegation is true. We do not accept plagiarized code. I will be closing this PR and would like to ask you to attempt at your own and make a PR again.

**Comment by m-code12** [comment]
@HarshCasper I do accept that my code initially was plagiarised but now I have changed the whole code, could you please review it?

**Pull request closed without merging**
