### PR TITLE
Kadane Algorithm in Julia 

### LINKED ISSUE #5308: Kadane Algorithm in Julia
## 💥 Proposal

Kadane Algorithm in Julia

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

YES

### PR DESCRIPTION
**Pull request by Harikrishnan6336**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

YES

### Description

Kadane Algorithm in Julia 

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Fixes #5308

### CODE REVIEW

**Comment by Saviour1001** [comment]
Kadane's algorithm already exists in the Julia folder.

**Comment by HarshCasper** [comment]
> Kadane's algorithm already exists in the Julia folder.

Where exactly?

**Comment by Saviour1001** [comment]
https://github.com/TesseractCoding/NeoAlgo/blob/master/Julia/cp/Maximum_subarray_sum.jl

**Review by ankitaggarwal23 — COMMENTED** [review]
Already present here #3593

**Pull request closed without merging**
