### PR TITLE
Refactor: Reverse Linked list in c++

### PR DESCRIPTION
**Pull request by yashaswibiyahut**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

**Yes**

### Description
Issue number = #283
Reverse Link List in both Recursive and Iterative approach.
Clone of head pointer so that it can easily take the input for 2nd function.
Resolve errors and modify the code.
Take input only once and it will work for both approach.

_Below is the output of above code_.
### Checklist

- [x]  I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#283

### CODE REVIEW

**Comment by yashaswibiyahut** [comment]
C__Users_yashaswi Biyahut_Desktop_Github Projects_NeoAlgo_C-Plus-Plus_ds_Reverse_linked_list exe 8_19_2020 12_56_41 PM (2)
Output of above code.

**Comment by yashaswibiyahut** [comment]
Please review my PR @SKAUL05 @Kajol-Kumari @Abhijit2505 @plazzy99 @siddharth25pandey

**Comment by vatsalkesarwani12** [comment]
edit readme file

**Comment by yashaswibiyahut** [comment]
For Reverse Link list in c++ readme file is already updated @plazzy99. 
Issue number = #283

**Comment by vatsalkesarwani12** [comment]
> For Reverse Link list in c++ readme file is already updated @plazzy99.
> Issue number = #283

 this means the code is already implemented

**Comment by yashaswibiyahut** [comment]
@plazzy99 the code is implemented but the code is not working that`s why it assigned to me so that i can resolve the errors which i already mentioned in the issue template.
You should check the previous code and mine code before closing the PR.

**Comment by siddharth25pandey** [comment]
@yashaswibiyahut Please add the *issue number* in the PR Template

**Comment by yashaswibiyahut** [comment]
Done @siddharth25pandey

**Review by Kajol-Kumari — CHANGES_REQUESTED** [review]
@yashaswibiyahut can you please add one sample input/output below the code section in commented form? Also please change this PR title to `[Fixed] Reverse Linked list in c++`. It will be good to go then :)

**Comment by yashaswibiyahut** [comment]
Changed the PR title and also Added one sample input output in the code section @Kajol-Kumari

**Review by Kajol-Kumari — APPROVED** [review]
LGTM :)

**Review by siddharth25pandey — CHANGES_REQUESTED** [review]
@yashaswibiyahut Instead of adding different types of headers
just write  **<bits/stdc++.h>**

**Comment by yashaswibiyahut** [comment]
Updated @siddharth25pandey

**Review by siddharth25pandey — APPROVED** [review]
@yashaswibiyahut Looks fine to me. just add the **README** file details
Able to merge.
Thanks!

**Comment by yashaswibiyahut** [comment]
Updated Readme file @siddharth25pandey

**Comment by yashaswibiyahut** [comment]
kindly review this @siddharth25pandey @plazzy99 @iamrajiv

**Review by siddharth25pandey — APPROVED** [review]
@yashaswibiyahut LGTM
Able to merge
Thanks!

**Review by iamrajiv — APPROVED** [review]
@yashaswibiyahut LGTM!

**Pull request merged**
