### PR TITLE
Check clear and set bits code added

### LINKED ISSUE #2920: Bit manipulation(Set Clear Check bit)
## 🚀 Feature

Set , Clear , Check bit for C++ Code base.

### Have you read the [Contributing Guidelines on Pull Requests]

Yes

## Pitch

The C++ code base doesn't have it.  Also these are the fundamentals when it comes to bit manipulation.

### PR DESCRIPTION
**Pull request by dhruvinfo28**
### Have you read the [Contributing Guidelines on Pull Requests]

Yes

### Description

closes #2920 . 

### Checklist

- [ Yes] I've read the contribution guidelines.
- [ Yes] I've checked the issue list before deciding what to submit.
- [ Yes] I've edited the `README.md` and link to my code.

### CODE REVIEW

**Comment by dhruvinfo28** [comment]
@bhav09 kindly review,  merge conflicts also resolved

**Review by bhav09 — COMMENTED** [review]
Great! I would like you to do a small modification. Add a new line at the end of this file. Rest, perfect!

**Comment by dhruvinfo28** [comment]
@bhav09 done

**Comment by bhav09** [comment]
Good work!

**Pull request merged**
