### PR TITLE
Added the code for printLinkedList

### LINKED ISSUE #5684: GSSOC-Print LinkedList
## 💥 Proposal

Add the problem of printing the LinkedList in NeoAlgo/Java

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

### PR DESCRIPTION
**Pull request by nancy0119**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Hey, I have solved the issue -5684 printLinkedList. Please merge my PR.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
Fixes : #5684 printLinkedList

### CODE REVIEW

**Comment by gat786** [comment]
Theres no description of what you are implementing in the source code. 
There is no complexity written in the code
There is not an example included. 
It is a completely clueless piece of code if you look it without this pr. Try to give more context to your codes. 
Make suitable comments wherever possible.

**Review by gat786 — CHANGES_REQUESTED** [review]
look the comment I have made and make the required changes. You have also not added the name to readme.

**Comment by nancy0119** [comment]
Ok..I will try to make the required changes.

**Review by ankitaggarwal23 — COMMENTED** [review]
Last Reminder, Read the instructions mentioned on Gssoc discord yesterday. Do the changes as per that.

**Comment by U-c0de** [comment]
@ankitaggarwal23 @gat786  Assign me this issue

**Comment by nancy0119** [comment]
I have tried doing the changes as mentioned earlier. Please merge my PR now and if still some changes are to be made, then please let me know. I will try to resolve it.

**Comment by ankitaggarwal23** [comment]
Closing this due to inactivity. Thank you for your valuable time.😊

**Review by ankitaggarwal23 — COMMENTED** [review]
Closing this due to inactivity. Thank you for your valuable time.😊

**Comment by nancy0119** [comment]
@ankitaggarwal23  Can u explain the reason of closing this.??I have done the changes as were mentioned. I'm beginner in open source...I wanted to learn from this  GSSOC prgm.It would be great if u could help me out :)

**Pull request closed without merging**
