### PR TITLE
Rishikeshrajrxl

### PR DESCRIPTION
**Pull request by Rishikeshrajrxl**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Yes)

### Description

(Write your answer here.)

### Checklist

- [X] I've read the contribution guidelines.
- [X] I've checked the issue list before deciding what to submit.
- [X] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(#400 )

### CODE REVIEW

**Comment by Rishikeshrajrxl** [comment]
please review my contribution. and let me know if  any changes needed.

**Review by siddharth25pandey — CHANGES_REQUESTED** [review]
@Rishikeshrajrxl Please make your code is more precise by adding these points.
* If user don't enter number between 1 to 8, then it must show, some message for valid input.
* Also after doing any operation, please print a successful message of the operation.
* At the Top, make a heading same as topic for more friendly user interface program.

**Comment by Rishikeshrajrxl** [comment]
Ok, I will do it.

**Review by Rishikeshrajrxl — COMMENTED** [review]
I have made all the changed. please review it.

**Review by siddharth25pandey — CHANGES_REQUESTED** [review]
@Rishikeshrajrxl  Seems fantastic but one operation is left.
* Deletion of a node at a given position.
Kindly do the above changes.

**Comment by Rishikeshrajrxl** [comment]
I have made the changes. Kindly review this.

**Review by siddharth25pandey — APPROVED** [review]
@Rishikeshrajrxl  Looks absolutely fine & clean.
Able to merge.
Thanks !

**Comment by Rishikeshrajrxl** [comment]
@plazzy99  please review my code.

**Comment by Rishikeshrajrxl** [comment]
@iamrajiv  please review my work.

**Review by iamrajiv — APPROVED** [review]
@Rishikeshrajrxl LGTM!

**Review by vatsalkesarwani12 — APPROVED** [review]
Code works fine

**Comment by iamrajiv** [comment]
@all-contributors please add @Rishikeshrajrxl for code

**Pull request merged**
