### PR TITLE
Egg Dropping Problem in C++

### PR DESCRIPTION
**Pull request by Bharati2612**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Added Egg Dropping Problem to Dynamic Programming Section of C++.

### Checklist

- [Y] I've read the contribution guidelines.
- [Y] I've checked the issue list before deciding what to submit.
- [Y] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
Issue Number #1455

### CODE REVIEW

**Comment by shraddhavp** [comment]
@Bharati2612  please create a seperate PR  for Egg dropping problem only

**Comment by shraddhavp** [comment]
do create a single PR per problem

**Comment by HarshCasper** [comment]
@Bharati2612 Are you still working on it?

**Comment by Bharati2612** [comment]
> @Bharati2612 Are you still working on it?

I have added the code for this, please review it.

**Comment by Bharati2612** [comment]
> @Bharati2612 Are you still working on it?

@HarshCasper Kindly review the pull request.

**Comment by HarshCasper** [comment]
@Bharati2612 Please make the README changes as well and add a beginner pitch about your Code in your Files.

**Pull request merged**
