### PR TITLE
Euler's Totient funtion in DART 

### LINKED ISSUE #6128: Euler's Totient funtion in DART
## 💥 Proposal

Euler's Totient funtion in DART

### LINKED ISSUE #6210: Euler's Totient function in DART
## 💥 Proposal

Euler's Totient function in DART

### PR DESCRIPTION
**Pull request by ashuvssut**
Euler's Totient funtion in DART

The result of the Euler's Totient Function (F(n)) for a number n 
denotes the number of co-primes of n from 1 to n

In this program:- we find the number of co-primes of n from 1 to n (n is from input) 

Ive read the PR guidelines

### important

In first test case n is a prime. in 2nd test case... it is a composite number

**Both test cases are different**

closes #6210
review https://replit.com/@AshutoshKhandua/PracticalFarSection

### CODE REVIEW

**Comment by ashuvssut** [comment]
@ankitaggarwal23 have a look again😄😄

**Review by ankitaggarwal23 — CHANGES_REQUESTED** [review]
Read the instructions mentioned on Gssoc discord yesterday. Do the changes as per that.

**Comment by ashuvssut** [comment]
# important

In first test case n is a prime.
 in 2nd test case... it is a composite number

**Comment by ashuvssut** [comment]
Updated the description and added extra details in code to support logic

**Review by ankitaggarwal23 — APPROVED** [review]

**Pull request merged**
