### PR TITLE
Ways to reach nth stair added in Java

### PR DESCRIPTION
**Pull request by YASH01009**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

(Yes)

### Description

(Ways to reach nth stair added in Java)

### Checklist

- [Y] I've read the contribution guidelines.
- [Y] I've checked the issue list before deciding what to submit.
- [Y] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Issue #1526 is solved here)

### CODE REVIEW

**Comment by aeyshubh** [comment]
This issue is assigned to me as in issue #1455, i think there are some miss conceptions

**Comment by YASH01009** [comment]
@ShubhamPatel33 Yeah, I actually see that its true but I was assigned the same in #1526

**Comment by aeyshubh** [comment]
Same issue is created twice ,hahaha @YASH01009 .Let's wait for the maintainer's response .

**Comment by shraddhavp** [comment]
@YASH01009  I see this issue was assigned to @ShubhamPatel33  first ,there was some misconception by the mentor I guess no issues will let them know .So will be taking @ShubhamPatel33 's solution for this problem,No worries @YASH01009  you are going great .
Both of you happy coding🎉😊

**Comment by YASH01009** [comment]
@shraddhavp can u pls look into this https://github.com/TesseractCoding/NeoAlgo/issues/1526#issuecomment-746786121 and confirm once again..

**Comment by shraddhavp** [comment]
yes will confirm  after discussing with @Neilblaze,  hence have not closed the PR .Dont worry @YASH01009

**Comment by YASH01009** [comment]
@shraddhavp pls consider if u feel the two issues are two different questions otherwise  things are fine with me.

**Pull request closed without merging**
