### PR TITLE
Added check if a number is power of 2

### PR DESCRIPTION
**Pull request by RaiyanMahin**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

YES.

### Description

Given a number , check whether the number is power of 2 or not.
We can check this by doing some bitwise operation. Bitwise operations are best because they perform the operation in least possible time.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#2989

### CODE REVIEW

**Comment by RaiyanMahin** [comment]
I see that most of the recent PR's got failed in DeepSource Java beta check ! Don't know why :(

**Comment by RaiyanMahin** [comment]
@HarshCasper  Sir , Knidly review

**Comment by RaiyanMahin** [comment]
@iamrajiv @ankitaggarwal23  Kindly review.

**Review by iamrajiv — APPROVED** [review]

**Comment by RaiyanMahin** [comment]
@iamrajiv  Thanks for the approve. is it looks good for merging?

**Comment by RaiyanMahin** [comment]
@iamrajiv  also knidly add labels.

**Review by ankitaggarwal23 — APPROVED** [review]

**Comment by ankitaggarwal23** [comment]
@RaiyanMahin Don't worry about labels we will add labels later. You can continue contributing.

**Pull request merged**
