### PR TITLE
Painter partition in Java

### PR DESCRIPTION
**Pull request by ritvij14**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?
Yes
(Write your answer here.)

### Description
Java code for the Painter Partition problem.
(Write your answer here.)

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
Issue #1068 
(Write your answer here.)

### CODE REVIEW

**Comment by ritvij14** [comment]
@iamrajiv @atarax665 @Kajol-Kumari @siddharth25pandey please review this.

**Review by siddharth25pandey — CHANGES_REQUESTED** [review]
@ritvij14 Well formatted code.
Good to go
Able to merge
Thanks!

**Review by siddharth25pandey — APPROVED** [review]

**Review by Kajol-Kumari — APPROVED** [review]
@ritvij14 please resolve the conflict here. Rest Looks good to go :+1:

**Comment by ritvij14** [comment]
@Kajol-Kumari done. @iamrajiv sir please review

**Review by iamrajiv — APPROVED** [review]

**Pull request merged**
