### PR TITLE
Optimized Bubble Sorting Technique

### PR DESCRIPTION
**Pull request by nutanaarohi123**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

#436 
Bubble Sort Algorithm is the sorting algorithm in which each element is compared to its adjacent element 
and if the first element is greater than the second element, then the swapping occurs.
The swapping occurs until the array is sorted. 

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#436

### CODE REVIEW

**Comment by nutanaarohi123** [comment]
Kindly review this @atarax665 @iamrajiv @Abhijit2505 @HarshCasper

**Comment by nutanaarohi123** [comment]
kindly review @iamrajiv @atarax665 @siddharth25pandey

**Review by iamrajiv — APPROVED** [review]

**Review by Kajol-Kumari — APPROVED** [review]
Functionality is working fine, well formatted and Looks good to go! :+1:

**Review by iamrajiv — CHANGES_REQUESTED** [review]
@nutanaarohi123 Resolve the merge conflicts.

**Comment by nutanaarohi123** [comment]
> @nutanaarohi123 Resolve the merge conflicts.

Resolved @iamrajiv .

**Review by iamrajiv — APPROVED** [review]

**Review by atarax665 — APPROVED** [review]
Nice work, LGTM :)

**Pull request merged**
