### PR TITLE
Implemented Sprague Grundy Theorem In CPP

### PR DESCRIPTION
**Pull request by KartikeySharma**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Sprague-Grundy Theorem says that in a composite game in which 2 players A and B play, if both A and B play optimally (i.e., they don’t make any mistakes), then the player starting first is guaranteed to win if the XOR of the grundy numbers of position in each sub-games at the beginning of the game is non-zero. Otherwise, if the XOR evaluates to zero, then player A will lose definitely, no matter what.

### Checklist

- [Tick] I've read the contribution guidelines.
- [Tick] I've checked the issue list before deciding what to submit.
- [Tick] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Issue #1701

### CODE REVIEW

**Comment by KartikeySharma** [comment]
Pls review @atarax665

**Comment by KartikeySharma** [comment]
Also,pls add the DWOC tag

**Comment by KartikeySharma** [comment]
@atarax665 The 2 later commits were added by mistake. How should I resolve it as I had deleted that version of the repository?

**Comment by atarax665** [comment]
> @atarax665 The 2 later commits were added by mistake. How should I resolve it as I had deleted that version of the repository?

You can always recover the deleted git branch, you may follow this [article](https://medium.com/@zaran.56/how-to-recover-restore-deleted-git-branch-5a068c07bed2). If this doesn't work try following a walk through video from youtube.

**Comment by KartikeySharma** [comment]
ok thanx. If none of the above work I will close this PR and start a new one. Will that be fine?

**Comment by KartikeySharma** [comment]
I am opening a new PR @atarax665 ..so closing this one

**Comment by atarax665** [comment]
Fine👍

**Pull request closed without merging**
