### PR TITLE
Check whether a number is a perfect number or not in JavaScript #5184

### PR DESCRIPTION
**Pull request by Aayushi-Mittal**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes, I have

### Description

To check whether it is a perfect number or not.
Perfect number is a positive integer which is equal to the sum of its proper positive divisors.
For example: 6 is the first perfect number
Proper divisors of 6 are 1, 2, 3
Sum of its proper divisors = 1 + 2 + 3 = 6.
Hence 6 is a perfect number.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

#5184

### CODE REVIEW

**Comment by Aayushi-Mittal** [comment]
@ankitaggarwal23  @HarshCasper Please review my PR.

**Comment by Aayushi-Mittal** [comment]
@ankitaggarwal23 @HarshCasper please review my PR. It's been 6 days now.

**Review by ankitaggarwal23 — CHANGES_REQUESTED** [review]
Few changes:

Use proper code Format
Don't use static inputs use dynamic inputs

**Review by ankitaggarwal23 — CHANGES_REQUESTED** [review]
readme file update missing

**Comment by Aayushi-Mittal** [comment]
@ankitaggarwal23 did the required changes. Please review.

**Review by ankitaggarwal23 — COMMENTED** [review]
Write the output in the way your code is producing

**Comment by Aayushi-Mittal** [comment]
Updated the Sample I/O. Please check now @ankitaggarwal23 .

**Review by ankitaggarwal23 — APPROVED** [review]

**Pull request merged**
