### PR TITLE
upated README.md

### PR DESCRIPTION
**Pull request by jivthesh**
Please read [how to contribute](CONTRIBUTING.md) first!
# Description
Submission description here

Checklist
* [ ] I've checked the issue list __BEFORE__ deciding what to submit
* [ ] I've read the contribution guidelines
* [ ] I've edited the README.md link to my code

## Don't forget to visit our [website](http://www.tesseractcoding.tech)!

Feel free to add this badge after your submission is accepted!

```
<a href=https://github.com/TesseractCoding/NeoAlgo>
   <img src=https://img.shields.io/badge/NeoAlgo-Contributor-brightgreen>
</a>
```

### CODE REVIEW

**Comment by anushkrishnav** [comment]
Hey . There is a minor conflict . Will it be possible for you attend to this conflict and issue a fresh PR . Have a nice day :)

**Comment by jivthesh** [comment]
@anushkrishnav  can u tell me how to do that?

**Comment by anushkrishnav** [comment]
> @anushkrishnav can u tell me how to do that?

no worries I can handle it from my side .
Thank you for your contribution

**Comment by anushkrishnav** [comment]
The file you updated the readme for 
"Queue Implementation.c " No longer exsist

**Pull request merged**
