### PR TITLE
Trapping rain water in Java

### LINKED ISSUE #5078: Trapping rainwater in Java
## 💥 Proposal

Given n non-negative integers representing an elevation map where the width of each bar is 1, compute how much water it can trap after raining.
I am a GSSOC participant and want to implement it in java.
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#reporting-new-issues)?

Yes

### PR DESCRIPTION
**Pull request by Amit366**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes

### Description

Added code for Trapping rain water in java

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

Fixes: #5078

### CODE REVIEW

**Comment by Amit366** [comment]
@atarax665 @ankitaggarwal23 please review.

**Comment by Amit366** [comment]
@HarshCasper please review.

**Review by ankitaggarwal23 — CHANGES_REQUESTED** [review]
Why you added two readme file. remove it

**Comment by Amit366** [comment]
@ankitaggarwal23 I unknowingly changed the c readme file and then commited so again I changed it. That's why 2 readme files are there.

**Comment by ankitaggarwal23** [comment]
> @ankitaggarwal23 I unknowingly changed the c readme file and then commited so again I changed it. That's why 2 readme files are there.

Remove it.

**Comment by Amit366** [comment]
@ankitaggarwal23 Can u tell me how to delete as when I am deleting it the whole readme is getting deleted.

**Comment by Amit366** [comment]
@ankitaggarwal23 please check the new PR #5388

**Pull request closed without merging**
