### PR TITLE
Ticket Auction in c++

### LINKED ISSUE #2418: Ticket Auction Problem
## 🚀 Feature

Concert Tickets Auction
There are n concert tickets available, each with a certain price. Then, m customers arrive, one after another.
Each customer announces the maximum price he or she is willing to pay for a ticket, and after this, they will get a ticket with the nearest possible price such that it does not exceed the maximum price.

## Assignment
Hello maintainers!  
As a participant/CA for GSSoC'21,  
I wish to contribute & resolve this issue with proper indentation, comments & sample I/O in C++.
Kindly assign me this issue under GSSOC '21...
CPP language & C language

### PR DESCRIPTION
**Pull request by Suvraneel**
Ticket Auction problem in CPP language

### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

Yes, I have gone through the Guidelines.

### Description
Concert Tickets Auction
There are n concert tickets available, each with a certain price. Then, m customers arrive, one after another.
Each customer announces the maximum price he or she is willing to pay for a ticket, and after this, they will get a ticket with the nearest possible price such that it does not exceed the maximum price.

### Checklist

- [x] I've read the contribution guidelines.
- [x] I've checked the issue list before deciding what to submit.
- [x] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests
closes #2418

### CODE REVIEW

**Comment by Suvraneel** [comment]
Hello maintainers!
Kindly review this....
@HarshCasper  @iamrajiv  
@bhav09  @siddharth25pandey

**Review by HarshCasper — CHANGES_REQUESTED** [review]
Few changes: 

- Shift sample I/O at the end of the Code
- Use comments above the line of code not beside it 
- Cut down on extra lines of code used

**Comment by Suvraneel** [comment]
@HarshCasper 
resolved the changes suggested 💯

**Comment by Suvraneel** [comment]
@HarshCasper I've no idea why the DeepSource: Java (beta) is failing...

" DeepSource can’t analyze this repository yet, unfortunately. Please check back later! "        :/

**Pull request merged**
