### PR TITLE
KMP Algorithm

### PR DESCRIPTION
**Pull request by ghost**
### Have you read the [Contributing Guidelines on Pull Requests](https://github.com/TesseractCoding/NeoAlgo/blob/master/CONTRIBUTING.md#pull-requests)?

yes

### Description

KMP algorithm for string search

### Checklist

- [X] I've read the contribution guidelines.
- [X] I've checked the issue list before deciding what to submit.
- [X] I've edited the `README.md` and link to my code.

## Related Issues or Pull Requests

(Write your answer here.)

### CODE REVIEW

**Comment by ghost** [comment]
@HarshCasper @iamrajiv @Kajol-Kumari @atarax665 
have a look at that please

**Comment by atarax665** [comment]
@HarshAgarwal-DEV I guess you aren't assigned this issue. Please raise PR only for the issues you are assigned by the mentors.

**Comment by ghost** [comment]
@atarax665  this time you do next time I will keep care 
also, I am raising an issue u assign me first and then merge it is that ok

**Comment by ghost** [comment]
@iamrajiv  please have a look at that

**Comment by siddharth25pandey** [comment]
@HarshAgarwal-DEV Refer [this](https://github.com/TesseractCoding/NeoAlgo/pull/619#issuecomment-676844920)

**Pull request closed without merging**
